/gate/verbose Physic 0
/gate/verbose Cuts 0
/gate/verbose SD 0
/gate/verbose Actions 0
/gate/verbose Actor 0
/gate/verbose Step 0
/gate/verbose Error 0
/gate/verbose Warning 0
/gate/verbose Output 0
/gate/verbose Beam 0
/gate/verbose Volume 0
/gate/verbose Image 0
/gate/verbose Geometry 0
/gate/verbose Core 2
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/gate/geometry/setMaterialDatabase data/AF_GateMaterials.db
/gate/world/setMaterial Air
/gate/world/geometry/setXLength 5.0 m
/gate/world/geometry/setYLength 5.0 m
/gate/world/geometry/setZLength 10.0 m
/gate/world/daughters/name killer
/gate/world/daughters/insert box
/gate/killer/geometry/setXLength 5 m
/gate/killer/geometry/setYLength 5 m
/gate/killer/geometry/setZLength 2 cm
/gate/killer/placement/setTranslation 0 0 2.2 m
/gate/killer/setMaterial Air
/gate/killer/vis/forceSolid
/gate/actor/addActor KillActor kill_actor
/gate/actor/kill_actor/save output/mykiller46.txt
/gate/actor/kill_actor/attachTo killer
/gate/world/daughters/name pre_collimator
/gate/world/daughters/insert box
/gate/pre_collimator/geometry/setXLength 200 mm
/gate/pre_collimator/geometry/setYLength 200 mm
/gate/pre_collimator/geometry/setZLength 46 mm
/gate/pre_collimator/placement/setTranslation 0 0 -3575 mm
/gate/pre_collimator/setMaterial Copper
/gate/pre_collimator/vis/forceWireframe
/gate/pre_collimator/daughters/name pre_hole
/gate/pre_collimator/daughters/insert box
/gate/pre_hole/geometry/setXLength 150 mm
/gate/pre_hole/geometry/setYLength 150 mm
/gate/pre_hole/geometry/setZLength 46 mm
/gate/pre_hole/placement/setTranslation 0 0 0 mm
/gate/pre_hole/setMaterial Air
/gate/pre_hole/vis/forceSolid
/gate/world/daughters/name RF_box
/gate/world/daughters/insert box
/gate/RF_box/setMaterial Air
/gate/RF_box/geometry/setXLength 20 cm
/gate/RF_box/geometry/setYLength 20 cm
/gate/RF_box/geometry/setZLength 6 cm
/gate/RF_box/placement/setTranslation 0 0 -236 cm
/gate/RF_box/vis/forceWireframe
/gate/RF_box/daughters/name RF1
/gate/RF_box/daughters/insert box
/gate/RF1/setMaterial Aluminium
/gate/RF1/geometry/setXLength 0.019000 cm
/gate/RF1/geometry/setYLength 20 cm
/gate/RF1/geometry/setZLength 0.136000 cm
/gate/RF1/placement/setTranslation -9.990500 0 -2.932000 cm
/gate/RF1/vis/forceSolid
/gate/RF1/vis/setColor yellow
/gate/RF1/repeaters/insert linear
/gate/RF1/linear/setRepeatNumber 40
/gate/RF1/linear/setRepeatVector 5 0 0 mm
/gate/RF1/linear/autoCenter false
/gate/RF_box/daughters/name RF2
/gate/RF_box/daughters/insert box
/gate/RF2/setMaterial Aluminium
/gate/RF2/geometry/setXLength 0.003000 cm
/gate/RF2/geometry/setYLength 20 cm
/gate/RF2/geometry/setZLength 0.158000 cm
/gate/RF2/placement/setTranslation -9.979500 0 -2.921000 cm
/gate/RF2/vis/forceSolid
/gate/RF2/vis/setColor yellow
/gate/RF2/repeaters/insert linear
/gate/RF2/linear/setRepeatNumber 40
/gate/RF2/linear/setRepeatVector 5 0 0 mm
/gate/RF2/linear/autoCenter false
/gate/RF_box/daughters/name RF4
/gate/RF_box/daughters/insert box
/gate/RF4/setMaterial Aluminium
/gate/RF4/geometry/setXLength 0.003000 cm
/gate/RF4/geometry/setYLength 20 cm
/gate/RF4/geometry/setZLength 0.204000 cm
/gate/RF4/placement/setTranslation -9.976500 0 -2.898000 cm
/gate/RF4/vis/forceSolid
/gate/RF4/vis/setColor yellow
/gate/RF4/repeaters/insert linear
/gate/RF4/linear/setRepeatNumber 40
/gate/RF4/linear/setRepeatVector 5 0 0 mm
/gate/RF4/linear/autoCenter false
/gate/RF_box/daughters/name RF5
/gate/RF_box/daughters/insert box
/gate/RF5/setMaterial Aluminium
/gate/RF5/geometry/setXLength 0.006000 cm
/gate/RF5/geometry/setYLength 20 cm
/gate/RF5/geometry/setZLength 0.226000 cm
/gate/RF5/placement/setTranslation -9.972000 0 -2.887000 cm
/gate/RF5/vis/forceSolid
/gate/RF5/vis/setColor yellow
/gate/RF5/repeaters/insert linear
/gate/RF5/linear/setRepeatNumber 40
/gate/RF5/linear/setRepeatVector 5 0 0 mm
/gate/RF5/linear/autoCenter false
/gate/RF_box/daughters/name RF6
/gate/RF_box/daughters/insert box
/gate/RF6/setMaterial Aluminium
/gate/RF6/geometry/setXLength 0.003000 cm
/gate/RF6/geometry/setYLength 20 cm
/gate/RF6/geometry/setZLength 0.249000 cm
/gate/RF6/placement/setTranslation -9.967500 0 -2.875500 cm
/gate/RF6/vis/forceSolid
/gate/RF6/vis/setColor yellow
/gate/RF6/repeaters/insert linear
/gate/RF6/linear/setRepeatNumber 40
/gate/RF6/linear/setRepeatVector 5 0 0 mm
/gate/RF6/linear/autoCenter false
/gate/RF_box/daughters/name RF7
/gate/RF_box/daughters/insert box
/gate/RF7/setMaterial Aluminium
/gate/RF7/geometry/setXLength 0.002000 cm
/gate/RF7/geometry/setYLength 20 cm
/gate/RF7/geometry/setZLength 0.272000 cm
/gate/RF7/placement/setTranslation -9.965000 0 -2.864000 cm
/gate/RF7/vis/forceSolid
/gate/RF7/vis/setColor yellow
/gate/RF7/repeaters/insert linear
/gate/RF7/linear/setRepeatNumber 40
/gate/RF7/linear/setRepeatVector 5 0 0 mm
/gate/RF7/linear/autoCenter false
/gate/RF_box/daughters/name RF8
/gate/RF_box/daughters/insert box
/gate/RF8/setMaterial Aluminium
/gate/RF8/geometry/setXLength 0.003000 cm
/gate/RF8/geometry/setYLength 20 cm
/gate/RF8/geometry/setZLength 0.294000 cm
/gate/RF8/placement/setTranslation -9.962500 0 -2.853000 cm
/gate/RF8/vis/forceSolid
/gate/RF8/vis/setColor yellow
/gate/RF8/repeaters/insert linear
/gate/RF8/linear/setRepeatNumber 40
/gate/RF8/linear/setRepeatVector 5 0 0 mm
/gate/RF8/linear/autoCenter false
/gate/RF_box/daughters/name RF9
/gate/RF_box/daughters/insert box
/gate/RF9/setMaterial Aluminium
/gate/RF9/geometry/setXLength 0.003000 cm
/gate/RF9/geometry/setYLength 20 cm
/gate/RF9/geometry/setZLength 0.317000 cm
/gate/RF9/placement/setTranslation -9.959500 0 -2.841500 cm
/gate/RF9/vis/forceSolid
/gate/RF9/vis/setColor yellow
/gate/RF9/repeaters/insert linear
/gate/RF9/linear/setRepeatNumber 40
/gate/RF9/linear/setRepeatVector 5 0 0 mm
/gate/RF9/linear/autoCenter false
/gate/RF_box/daughters/name RF10
/gate/RF_box/daughters/insert box
/gate/RF10/setMaterial Aluminium
/gate/RF10/geometry/setXLength 0.002000 cm
/gate/RF10/geometry/setYLength 20 cm
/gate/RF10/geometry/setZLength 0.340000 cm
/gate/RF10/placement/setTranslation -9.957000 0 -2.830000 cm
/gate/RF10/vis/forceSolid
/gate/RF10/vis/setColor yellow
/gate/RF10/repeaters/insert linear
/gate/RF10/linear/setRepeatNumber 40
/gate/RF10/linear/setRepeatVector 5 0 0 mm
/gate/RF10/linear/autoCenter false
/gate/RF_box/daughters/name RF11
/gate/RF_box/daughters/insert box
/gate/RF11/setMaterial Aluminium
/gate/RF11/geometry/setXLength 0.003000 cm
/gate/RF11/geometry/setYLength 20 cm
/gate/RF11/geometry/setZLength 0.362000 cm
/gate/RF11/placement/setTranslation -9.954500 0 -2.819000 cm
/gate/RF11/vis/forceSolid
/gate/RF11/vis/setColor yellow
/gate/RF11/repeaters/insert linear
/gate/RF11/linear/setRepeatNumber 40
/gate/RF11/linear/setRepeatVector 5 0 0 mm
/gate/RF11/linear/autoCenter false
/gate/RF_box/daughters/name RF12
/gate/RF_box/daughters/insert box
/gate/RF12/setMaterial Aluminium
/gate/RF12/geometry/setXLength 0.002000 cm
/gate/RF12/geometry/setYLength 20 cm
/gate/RF12/geometry/setZLength 0.385000 cm
/gate/RF12/placement/setTranslation -9.952000 0 -2.807500 cm
/gate/RF12/vis/forceSolid
/gate/RF12/vis/setColor yellow
/gate/RF12/repeaters/insert linear
/gate/RF12/linear/setRepeatNumber 40
/gate/RF12/linear/setRepeatVector 5 0 0 mm
/gate/RF12/linear/autoCenter false
/gate/RF_box/daughters/name RF13
/gate/RF_box/daughters/insert box
/gate/RF13/setMaterial Aluminium
/gate/RF13/geometry/setXLength 0.003000 cm
/gate/RF13/geometry/setYLength 20 cm
/gate/RF13/geometry/setZLength 0.407000 cm
/gate/RF13/placement/setTranslation -9.949500 0 -2.796500 cm
/gate/RF13/vis/forceSolid
/gate/RF13/vis/setColor yellow
/gate/RF13/repeaters/insert linear
/gate/RF13/linear/setRepeatNumber 40
/gate/RF13/linear/setRepeatVector 5 0 0 mm
/gate/RF13/linear/autoCenter false
/gate/RF_box/daughters/name RF14
/gate/RF_box/daughters/insert box
/gate/RF14/setMaterial Aluminium
/gate/RF14/geometry/setXLength 0.002000 cm
/gate/RF14/geometry/setYLength 20 cm
/gate/RF14/geometry/setZLength 0.430000 cm
/gate/RF14/placement/setTranslation -9.947000 0 -2.785000 cm
/gate/RF14/vis/forceSolid
/gate/RF14/vis/setColor yellow
/gate/RF14/repeaters/insert linear
/gate/RF14/linear/setRepeatNumber 40
/gate/RF14/linear/setRepeatVector 5 0 0 mm
/gate/RF14/linear/autoCenter false
/gate/RF_box/daughters/name RF15
/gate/RF_box/daughters/insert box
/gate/RF15/setMaterial Aluminium
/gate/RF15/geometry/setXLength 0.002000 cm
/gate/RF15/geometry/setYLength 20 cm
/gate/RF15/geometry/setZLength 0.453000 cm
/gate/RF15/placement/setTranslation -9.945000 0 -2.773500 cm
/gate/RF15/vis/forceSolid
/gate/RF15/vis/setColor yellow
/gate/RF15/repeaters/insert linear
/gate/RF15/linear/setRepeatNumber 40
/gate/RF15/linear/setRepeatVector 5 0 0 mm
/gate/RF15/linear/autoCenter false
/gate/RF_box/daughters/name RF16
/gate/RF_box/daughters/insert box
/gate/RF16/setMaterial Aluminium
/gate/RF16/geometry/setXLength 0.002000 cm
/gate/RF16/geometry/setYLength 20 cm
/gate/RF16/geometry/setZLength 0.475000 cm
/gate/RF16/placement/setTranslation -9.943000 0 -2.762500 cm
/gate/RF16/vis/forceSolid
/gate/RF16/vis/setColor yellow
/gate/RF16/repeaters/insert linear
/gate/RF16/linear/setRepeatNumber 40
/gate/RF16/linear/setRepeatVector 5 0 0 mm
/gate/RF16/linear/autoCenter false
/gate/RF_box/daughters/name RF17
/gate/RF_box/daughters/insert box
/gate/RF17/setMaterial Aluminium
/gate/RF17/geometry/setXLength 0.002000 cm
/gate/RF17/geometry/setYLength 20 cm
/gate/RF17/geometry/setZLength 0.498000 cm
/gate/RF17/placement/setTranslation -9.941000 0 -2.751000 cm
/gate/RF17/vis/forceSolid
/gate/RF17/vis/setColor yellow
/gate/RF17/repeaters/insert linear
/gate/RF17/linear/setRepeatNumber 40
/gate/RF17/linear/setRepeatVector 5 0 0 mm
/gate/RF17/linear/autoCenter false
/gate/RF_box/daughters/name RF18
/gate/RF_box/daughters/insert box
/gate/RF18/setMaterial Aluminium
/gate/RF18/geometry/setXLength 0.002000 cm
/gate/RF18/geometry/setYLength 20 cm
/gate/RF18/geometry/setZLength 0.521000 cm
/gate/RF18/placement/setTranslation -9.939000 0 -2.739500 cm
/gate/RF18/vis/forceSolid
/gate/RF18/vis/setColor yellow
/gate/RF18/repeaters/insert linear
/gate/RF18/linear/setRepeatNumber 40
/gate/RF18/linear/setRepeatVector 5 0 0 mm
/gate/RF18/linear/autoCenter false
/gate/RF_box/daughters/name RF19
/gate/RF_box/daughters/insert box
/gate/RF19/setMaterial Aluminium
/gate/RF19/geometry/setXLength 0.002000 cm
/gate/RF19/geometry/setYLength 20 cm
/gate/RF19/geometry/setZLength 0.543000 cm
/gate/RF19/placement/setTranslation -9.937000 0 -2.728500 cm
/gate/RF19/vis/forceSolid
/gate/RF19/vis/setColor yellow
/gate/RF19/repeaters/insert linear
/gate/RF19/linear/setRepeatNumber 40
/gate/RF19/linear/setRepeatVector 5 0 0 mm
/gate/RF19/linear/autoCenter false
/gate/RF_box/daughters/name RF20
/gate/RF_box/daughters/insert box
/gate/RF20/setMaterial Aluminium
/gate/RF20/geometry/setXLength 0.002000 cm
/gate/RF20/geometry/setYLength 20 cm
/gate/RF20/geometry/setZLength 0.566000 cm
/gate/RF20/placement/setTranslation -9.935000 0 -2.717000 cm
/gate/RF20/vis/forceSolid
/gate/RF20/vis/setColor yellow
/gate/RF20/repeaters/insert linear
/gate/RF20/linear/setRepeatNumber 40
/gate/RF20/linear/setRepeatVector 5 0 0 mm
/gate/RF20/linear/autoCenter false
/gate/RF_box/daughters/name RF21
/gate/RF_box/daughters/insert box
/gate/RF21/setMaterial Aluminium
/gate/RF21/geometry/setXLength 0.002000 cm
/gate/RF21/geometry/setYLength 20 cm
/gate/RF21/geometry/setZLength 0.589000 cm
/gate/RF21/placement/setTranslation -9.933000 0 -2.705500 cm
/gate/RF21/vis/forceSolid
/gate/RF21/vis/setColor yellow
/gate/RF21/repeaters/insert linear
/gate/RF21/linear/setRepeatNumber 40
/gate/RF21/linear/setRepeatVector 5 0 0 mm
/gate/RF21/linear/autoCenter false
/gate/RF_box/daughters/name RF22
/gate/RF_box/daughters/insert box
/gate/RF22/setMaterial Aluminium
/gate/RF22/geometry/setXLength 0.002000 cm
/gate/RF22/geometry/setYLength 20 cm
/gate/RF22/geometry/setZLength 0.611000 cm
/gate/RF22/placement/setTranslation -9.931000 0 -2.694500 cm
/gate/RF22/vis/forceSolid
/gate/RF22/vis/setColor yellow
/gate/RF22/repeaters/insert linear
/gate/RF22/linear/setRepeatNumber 40
/gate/RF22/linear/setRepeatVector 5 0 0 mm
/gate/RF22/linear/autoCenter false
/gate/RF_box/daughters/name RF23
/gate/RF_box/daughters/insert box
/gate/RF23/setMaterial Aluminium
/gate/RF23/geometry/setXLength 0.002000 cm
/gate/RF23/geometry/setYLength 20 cm
/gate/RF23/geometry/setZLength 0.634000 cm
/gate/RF23/placement/setTranslation -9.929000 0 -2.683000 cm
/gate/RF23/vis/forceSolid
/gate/RF23/vis/setColor yellow
/gate/RF23/repeaters/insert linear
/gate/RF23/linear/setRepeatNumber 40
/gate/RF23/linear/setRepeatVector 5 0 0 mm
/gate/RF23/linear/autoCenter false
/gate/RF_box/daughters/name RF24
/gate/RF_box/daughters/insert box
/gate/RF24/setMaterial Aluminium
/gate/RF24/geometry/setXLength 0.001000 cm
/gate/RF24/geometry/setYLength 20 cm
/gate/RF24/geometry/setZLength 0.656000 cm
/gate/RF24/placement/setTranslation -9.927500 0 -2.672000 cm
/gate/RF24/vis/forceSolid
/gate/RF24/vis/setColor yellow
/gate/RF24/repeaters/insert linear
/gate/RF24/linear/setRepeatNumber 40
/gate/RF24/linear/setRepeatVector 5 0 0 mm
/gate/RF24/linear/autoCenter false
/gate/RF_box/daughters/name RF25
/gate/RF_box/daughters/insert box
/gate/RF25/setMaterial Aluminium
/gate/RF25/geometry/setXLength 0.002000 cm
/gate/RF25/geometry/setYLength 20 cm
/gate/RF25/geometry/setZLength 0.679000 cm
/gate/RF25/placement/setTranslation -9.926000 0 -2.660500 cm
/gate/RF25/vis/forceSolid
/gate/RF25/vis/setColor yellow
/gate/RF25/repeaters/insert linear
/gate/RF25/linear/setRepeatNumber 40
/gate/RF25/linear/setRepeatVector 5 0 0 mm
/gate/RF25/linear/autoCenter false
/gate/RF_box/daughters/name RF26
/gate/RF_box/daughters/insert box
/gate/RF26/setMaterial Aluminium
/gate/RF26/geometry/setXLength 0.002000 cm
/gate/RF26/geometry/setYLength 20 cm
/gate/RF26/geometry/setZLength 0.702000 cm
/gate/RF26/placement/setTranslation -9.924000 0 -2.649000 cm
/gate/RF26/vis/forceSolid
/gate/RF26/vis/setColor yellow
/gate/RF26/repeaters/insert linear
/gate/RF26/linear/setRepeatNumber 40
/gate/RF26/linear/setRepeatVector 5 0 0 mm
/gate/RF26/linear/autoCenter false
/gate/RF_box/daughters/name RF27
/gate/RF_box/daughters/insert box
/gate/RF27/setMaterial Aluminium
/gate/RF27/geometry/setXLength 0.001000 cm
/gate/RF27/geometry/setYLength 20 cm
/gate/RF27/geometry/setZLength 0.724000 cm
/gate/RF27/placement/setTranslation -9.922500 0 -2.638000 cm
/gate/RF27/vis/forceSolid
/gate/RF27/vis/setColor yellow
/gate/RF27/repeaters/insert linear
/gate/RF27/linear/setRepeatNumber 40
/gate/RF27/linear/setRepeatVector 5 0 0 mm
/gate/RF27/linear/autoCenter false
/gate/RF_box/daughters/name RF28
/gate/RF_box/daughters/insert box
/gate/RF28/setMaterial Aluminium
/gate/RF28/geometry/setXLength 0.002000 cm
/gate/RF28/geometry/setYLength 20 cm
/gate/RF28/geometry/setZLength 0.747000 cm
/gate/RF28/placement/setTranslation -9.921000 0 -2.626500 cm
/gate/RF28/vis/forceSolid
/gate/RF28/vis/setColor yellow
/gate/RF28/repeaters/insert linear
/gate/RF28/linear/setRepeatNumber 40
/gate/RF28/linear/setRepeatVector 5 0 0 mm
/gate/RF28/linear/autoCenter false
/gate/RF_box/daughters/name RF29
/gate/RF_box/daughters/insert box
/gate/RF29/setMaterial Aluminium
/gate/RF29/geometry/setXLength 0.002000 cm
/gate/RF29/geometry/setYLength 20 cm
/gate/RF29/geometry/setZLength 0.770000 cm
/gate/RF29/placement/setTranslation -9.919000 0 -2.615000 cm
/gate/RF29/vis/forceSolid
/gate/RF29/vis/setColor yellow
/gate/RF29/repeaters/insert linear
/gate/RF29/linear/setRepeatNumber 40
/gate/RF29/linear/setRepeatVector 5 0 0 mm
/gate/RF29/linear/autoCenter false
/gate/RF_box/daughters/name RF30
/gate/RF_box/daughters/insert box
/gate/RF30/setMaterial Aluminium
/gate/RF30/geometry/setXLength 0.001000 cm
/gate/RF30/geometry/setYLength 20 cm
/gate/RF30/geometry/setZLength 0.792000 cm
/gate/RF30/placement/setTranslation -9.917500 0 -2.604000 cm
/gate/RF30/vis/forceSolid
/gate/RF30/vis/setColor yellow
/gate/RF30/repeaters/insert linear
/gate/RF30/linear/setRepeatNumber 40
/gate/RF30/linear/setRepeatVector 5 0 0 mm
/gate/RF30/linear/autoCenter false
/gate/RF_box/daughters/name RF31
/gate/RF_box/daughters/insert box
/gate/RF31/setMaterial Aluminium
/gate/RF31/geometry/setXLength 0.002000 cm
/gate/RF31/geometry/setYLength 20 cm
/gate/RF31/geometry/setZLength 0.815000 cm
/gate/RF31/placement/setTranslation -9.916000 0 -2.592500 cm
/gate/RF31/vis/forceSolid
/gate/RF31/vis/setColor yellow
/gate/RF31/repeaters/insert linear
/gate/RF31/linear/setRepeatNumber 40
/gate/RF31/linear/setRepeatVector 5 0 0 mm
/gate/RF31/linear/autoCenter false
/gate/RF_box/daughters/name RF32
/gate/RF_box/daughters/insert box
/gate/RF32/setMaterial Aluminium
/gate/RF32/geometry/setXLength 0.001000 cm
/gate/RF32/geometry/setYLength 20 cm
/gate/RF32/geometry/setZLength 0.837000 cm
/gate/RF32/placement/setTranslation -9.914500 0 -2.581500 cm
/gate/RF32/vis/forceSolid
/gate/RF32/vis/setColor yellow
/gate/RF32/repeaters/insert linear
/gate/RF32/linear/setRepeatNumber 40
/gate/RF32/linear/setRepeatVector 5 0 0 mm
/gate/RF32/linear/autoCenter false
/gate/RF_box/daughters/name RF33
/gate/RF_box/daughters/insert box
/gate/RF33/setMaterial Aluminium
/gate/RF33/geometry/setXLength 0.002000 cm
/gate/RF33/geometry/setYLength 20 cm
/gate/RF33/geometry/setZLength 0.860000 cm
/gate/RF33/placement/setTranslation -9.913000 0 -2.570000 cm
/gate/RF33/vis/forceSolid
/gate/RF33/vis/setColor yellow
/gate/RF33/repeaters/insert linear
/gate/RF33/linear/setRepeatNumber 40
/gate/RF33/linear/setRepeatVector 5 0 0 mm
/gate/RF33/linear/autoCenter false
/gate/RF_box/daughters/name RF34
/gate/RF_box/daughters/insert box
/gate/RF34/setMaterial Aluminium
/gate/RF34/geometry/setXLength 0.001000 cm
/gate/RF34/geometry/setYLength 20 cm
/gate/RF34/geometry/setZLength 0.883000 cm
/gate/RF34/placement/setTranslation -9.911500 0 -2.558500 cm
/gate/RF34/vis/forceSolid
/gate/RF34/vis/setColor yellow
/gate/RF34/repeaters/insert linear
/gate/RF34/linear/setRepeatNumber 40
/gate/RF34/linear/setRepeatVector 5 0 0 mm
/gate/RF34/linear/autoCenter false
/gate/RF_box/daughters/name RF35
/gate/RF_box/daughters/insert box
/gate/RF35/setMaterial Aluminium
/gate/RF35/geometry/setXLength 0.002000 cm
/gate/RF35/geometry/setYLength 20 cm
/gate/RF35/geometry/setZLength 0.905000 cm
/gate/RF35/placement/setTranslation -9.910000 0 -2.547500 cm
/gate/RF35/vis/forceSolid
/gate/RF35/vis/setColor yellow
/gate/RF35/repeaters/insert linear
/gate/RF35/linear/setRepeatNumber 40
/gate/RF35/linear/setRepeatVector 5 0 0 mm
/gate/RF35/linear/autoCenter false
/gate/RF_box/daughters/name RF36
/gate/RF_box/daughters/insert box
/gate/RF36/setMaterial Aluminium
/gate/RF36/geometry/setXLength 0.001000 cm
/gate/RF36/geometry/setYLength 20 cm
/gate/RF36/geometry/setZLength 0.928000 cm
/gate/RF36/placement/setTranslation -9.908500 0 -2.536000 cm
/gate/RF36/vis/forceSolid
/gate/RF36/vis/setColor yellow
/gate/RF36/repeaters/insert linear
/gate/RF36/linear/setRepeatNumber 40
/gate/RF36/linear/setRepeatVector 5 0 0 mm
/gate/RF36/linear/autoCenter false
/gate/RF_box/daughters/name RF37
/gate/RF_box/daughters/insert box
/gate/RF37/setMaterial Aluminium
/gate/RF37/geometry/setXLength 0.002000 cm
/gate/RF37/geometry/setYLength 20 cm
/gate/RF37/geometry/setZLength 0.951000 cm
/gate/RF37/placement/setTranslation -9.907000 0 -2.524500 cm
/gate/RF37/vis/forceSolid
/gate/RF37/vis/setColor yellow
/gate/RF37/repeaters/insert linear
/gate/RF37/linear/setRepeatNumber 40
/gate/RF37/linear/setRepeatVector 5 0 0 mm
/gate/RF37/linear/autoCenter false
/gate/RF_box/daughters/name RF38
/gate/RF_box/daughters/insert box
/gate/RF38/setMaterial Aluminium
/gate/RF38/geometry/setXLength 0.001000 cm
/gate/RF38/geometry/setYLength 20 cm
/gate/RF38/geometry/setZLength 0.973000 cm
/gate/RF38/placement/setTranslation -9.905500 0 -2.513500 cm
/gate/RF38/vis/forceSolid
/gate/RF38/vis/setColor yellow
/gate/RF38/repeaters/insert linear
/gate/RF38/linear/setRepeatNumber 40
/gate/RF38/linear/setRepeatVector 5 0 0 mm
/gate/RF38/linear/autoCenter false
/gate/RF_box/daughters/name RF39
/gate/RF_box/daughters/insert box
/gate/RF39/setMaterial Aluminium
/gate/RF39/geometry/setXLength 0.002000 cm
/gate/RF39/geometry/setYLength 20 cm
/gate/RF39/geometry/setZLength 0.996000 cm
/gate/RF39/placement/setTranslation -9.904000 0 -2.502000 cm
/gate/RF39/vis/forceSolid
/gate/RF39/vis/setColor yellow
/gate/RF39/repeaters/insert linear
/gate/RF39/linear/setRepeatNumber 40
/gate/RF39/linear/setRepeatVector 5 0 0 mm
/gate/RF39/linear/autoCenter false
/gate/RF_box/daughters/name RF40
/gate/RF_box/daughters/insert box
/gate/RF40/setMaterial Aluminium
/gate/RF40/geometry/setXLength 0.001000 cm
/gate/RF40/geometry/setYLength 20 cm
/gate/RF40/geometry/setZLength 1.019000 cm
/gate/RF40/placement/setTranslation -9.902500 0 -2.490500 cm
/gate/RF40/vis/forceSolid
/gate/RF40/vis/setColor yellow
/gate/RF40/repeaters/insert linear
/gate/RF40/linear/setRepeatNumber 40
/gate/RF40/linear/setRepeatVector 5 0 0 mm
/gate/RF40/linear/autoCenter false
/gate/RF_box/daughters/name RF41
/gate/RF_box/daughters/insert box
/gate/RF41/setMaterial Aluminium
/gate/RF41/geometry/setXLength 0.001000 cm
/gate/RF41/geometry/setYLength 20 cm
/gate/RF41/geometry/setZLength 1.041000 cm
/gate/RF41/placement/setTranslation -9.901500 0 -2.479500 cm
/gate/RF41/vis/forceSolid
/gate/RF41/vis/setColor yellow
/gate/RF41/repeaters/insert linear
/gate/RF41/linear/setRepeatNumber 40
/gate/RF41/linear/setRepeatVector 5 0 0 mm
/gate/RF41/linear/autoCenter false
/gate/RF_box/daughters/name RF42
/gate/RF_box/daughters/insert box
/gate/RF42/setMaterial Aluminium
/gate/RF42/geometry/setXLength 0.002000 cm
/gate/RF42/geometry/setYLength 20 cm
/gate/RF42/geometry/setZLength 1.064000 cm
/gate/RF42/placement/setTranslation -9.900000 0 -2.468000 cm
/gate/RF42/vis/forceSolid
/gate/RF42/vis/setColor yellow
/gate/RF42/repeaters/insert linear
/gate/RF42/linear/setRepeatNumber 40
/gate/RF42/linear/setRepeatVector 5 0 0 mm
/gate/RF42/linear/autoCenter false
/gate/RF_box/daughters/name RF43
/gate/RF_box/daughters/insert box
/gate/RF43/setMaterial Aluminium
/gate/RF43/geometry/setXLength 0.001000 cm
/gate/RF43/geometry/setYLength 20 cm
/gate/RF43/geometry/setZLength 1.086000 cm
/gate/RF43/placement/setTranslation -9.898500 0 -2.457000 cm
/gate/RF43/vis/forceSolid
/gate/RF43/vis/setColor yellow
/gate/RF43/repeaters/insert linear
/gate/RF43/linear/setRepeatNumber 40
/gate/RF43/linear/setRepeatVector 5 0 0 mm
/gate/RF43/linear/autoCenter false
/gate/RF_box/daughters/name RF44
/gate/RF_box/daughters/insert box
/gate/RF44/setMaterial Aluminium
/gate/RF44/geometry/setXLength 0.001000 cm
/gate/RF44/geometry/setYLength 20 cm
/gate/RF44/geometry/setZLength 1.109000 cm
/gate/RF44/placement/setTranslation -9.897500 0 -2.445500 cm
/gate/RF44/vis/forceSolid
/gate/RF44/vis/setColor yellow
/gate/RF44/repeaters/insert linear
/gate/RF44/linear/setRepeatNumber 40
/gate/RF44/linear/setRepeatVector 5 0 0 mm
/gate/RF44/linear/autoCenter false
/gate/RF_box/daughters/name RF45
/gate/RF_box/daughters/insert box
/gate/RF45/setMaterial Aluminium
/gate/RF45/geometry/setXLength 0.002000 cm
/gate/RF45/geometry/setYLength 20 cm
/gate/RF45/geometry/setZLength 1.132000 cm
/gate/RF45/placement/setTranslation -9.896000 0 -2.434000 cm
/gate/RF45/vis/forceSolid
/gate/RF45/vis/setColor yellow
/gate/RF45/repeaters/insert linear
/gate/RF45/linear/setRepeatNumber 40
/gate/RF45/linear/setRepeatVector 5 0 0 mm
/gate/RF45/linear/autoCenter false
/gate/RF_box/daughters/name RF46
/gate/RF_box/daughters/insert box
/gate/RF46/setMaterial Aluminium
/gate/RF46/geometry/setXLength 0.001000 cm
/gate/RF46/geometry/setYLength 20 cm
/gate/RF46/geometry/setZLength 1.154000 cm
/gate/RF46/placement/setTranslation -9.894500 0 -2.423000 cm
/gate/RF46/vis/forceSolid
/gate/RF46/vis/setColor yellow
/gate/RF46/repeaters/insert linear
/gate/RF46/linear/setRepeatNumber 40
/gate/RF46/linear/setRepeatVector 5 0 0 mm
/gate/RF46/linear/autoCenter false
/gate/RF_box/daughters/name RF47
/gate/RF_box/daughters/insert box
/gate/RF47/setMaterial Aluminium
/gate/RF47/geometry/setXLength 0.001000 cm
/gate/RF47/geometry/setYLength 20 cm
/gate/RF47/geometry/setZLength 1.177000 cm
/gate/RF47/placement/setTranslation -9.893500 0 -2.411500 cm
/gate/RF47/vis/forceSolid
/gate/RF47/vis/setColor yellow
/gate/RF47/repeaters/insert linear
/gate/RF47/linear/setRepeatNumber 40
/gate/RF47/linear/setRepeatVector 5 0 0 mm
/gate/RF47/linear/autoCenter false
/gate/RF_box/daughters/name RF48
/gate/RF_box/daughters/insert box
/gate/RF48/setMaterial Aluminium
/gate/RF48/geometry/setXLength 0.001000 cm
/gate/RF48/geometry/setYLength 20 cm
/gate/RF48/geometry/setZLength 1.200000 cm
/gate/RF48/placement/setTranslation -9.892500 0 -2.400000 cm
/gate/RF48/vis/forceSolid
/gate/RF48/vis/setColor yellow
/gate/RF48/repeaters/insert linear
/gate/RF48/linear/setRepeatNumber 40
/gate/RF48/linear/setRepeatVector 5 0 0 mm
/gate/RF48/linear/autoCenter false
/gate/RF_box/daughters/name RF49
/gate/RF_box/daughters/insert box
/gate/RF49/setMaterial Aluminium
/gate/RF49/geometry/setXLength 0.002000 cm
/gate/RF49/geometry/setYLength 20 cm
/gate/RF49/geometry/setZLength 1.222000 cm
/gate/RF49/placement/setTranslation -9.891000 0 -2.389000 cm
/gate/RF49/vis/forceSolid
/gate/RF49/vis/setColor yellow
/gate/RF49/repeaters/insert linear
/gate/RF49/linear/setRepeatNumber 40
/gate/RF49/linear/setRepeatVector 5 0 0 mm
/gate/RF49/linear/autoCenter false
/gate/RF_box/daughters/name RF50
/gate/RF_box/daughters/insert box
/gate/RF50/setMaterial Aluminium
/gate/RF50/geometry/setXLength 0.001000 cm
/gate/RF50/geometry/setYLength 20 cm
/gate/RF50/geometry/setZLength 1.245000 cm
/gate/RF50/placement/setTranslation -9.889500 0 -2.377500 cm
/gate/RF50/vis/forceSolid
/gate/RF50/vis/setColor yellow
/gate/RF50/repeaters/insert linear
/gate/RF50/linear/setRepeatNumber 40
/gate/RF50/linear/setRepeatVector 5 0 0 mm
/gate/RF50/linear/autoCenter false
/gate/RF_box/daughters/name RF51
/gate/RF_box/daughters/insert box
/gate/RF51/setMaterial Aluminium
/gate/RF51/geometry/setXLength 0.001000 cm
/gate/RF51/geometry/setYLength 20 cm
/gate/RF51/geometry/setZLength 1.268000 cm
/gate/RF51/placement/setTranslation -9.888500 0 -2.366000 cm
/gate/RF51/vis/forceSolid
/gate/RF51/vis/setColor yellow
/gate/RF51/repeaters/insert linear
/gate/RF51/linear/setRepeatNumber 40
/gate/RF51/linear/setRepeatVector 5 0 0 mm
/gate/RF51/linear/autoCenter false
/gate/RF_box/daughters/name RF52
/gate/RF_box/daughters/insert box
/gate/RF52/setMaterial Aluminium
/gate/RF52/geometry/setXLength 0.001000 cm
/gate/RF52/geometry/setYLength 20 cm
/gate/RF52/geometry/setZLength 1.290000 cm
/gate/RF52/placement/setTranslation -9.887500 0 -2.355000 cm
/gate/RF52/vis/forceSolid
/gate/RF52/vis/setColor yellow
/gate/RF52/repeaters/insert linear
/gate/RF52/linear/setRepeatNumber 40
/gate/RF52/linear/setRepeatVector 5 0 0 mm
/gate/RF52/linear/autoCenter false
/gate/RF_box/daughters/name RF53
/gate/RF_box/daughters/insert box
/gate/RF53/setMaterial Aluminium
/gate/RF53/geometry/setXLength 0.001000 cm
/gate/RF53/geometry/setYLength 20 cm
/gate/RF53/geometry/setZLength 1.313000 cm
/gate/RF53/placement/setTranslation -9.886500 0 -2.343500 cm
/gate/RF53/vis/forceSolid
/gate/RF53/vis/setColor yellow
/gate/RF53/repeaters/insert linear
/gate/RF53/linear/setRepeatNumber 40
/gate/RF53/linear/setRepeatVector 5 0 0 mm
/gate/RF53/linear/autoCenter false
/gate/RF_box/daughters/name RF54
/gate/RF_box/daughters/insert box
/gate/RF54/setMaterial Aluminium
/gate/RF54/geometry/setXLength 0.002000 cm
/gate/RF54/geometry/setYLength 20 cm
/gate/RF54/geometry/setZLength 1.335000 cm
/gate/RF54/placement/setTranslation -9.885000 0 -2.332500 cm
/gate/RF54/vis/forceSolid
/gate/RF54/vis/setColor yellow
/gate/RF54/repeaters/insert linear
/gate/RF54/linear/setRepeatNumber 40
/gate/RF54/linear/setRepeatVector 5 0 0 mm
/gate/RF54/linear/autoCenter false
/gate/RF_box/daughters/name RF55
/gate/RF_box/daughters/insert box
/gate/RF55/setMaterial Aluminium
/gate/RF55/geometry/setXLength 0.001000 cm
/gate/RF55/geometry/setYLength 20 cm
/gate/RF55/geometry/setZLength 1.358000 cm
/gate/RF55/placement/setTranslation -9.883500 0 -2.321000 cm
/gate/RF55/vis/forceSolid
/gate/RF55/vis/setColor yellow
/gate/RF55/repeaters/insert linear
/gate/RF55/linear/setRepeatNumber 40
/gate/RF55/linear/setRepeatVector 5 0 0 mm
/gate/RF55/linear/autoCenter false
/gate/RF_box/daughters/name RF56
/gate/RF_box/daughters/insert box
/gate/RF56/setMaterial Aluminium
/gate/RF56/geometry/setXLength 0.001000 cm
/gate/RF56/geometry/setYLength 20 cm
/gate/RF56/geometry/setZLength 1.381000 cm
/gate/RF56/placement/setTranslation -9.882500 0 -2.309500 cm
/gate/RF56/vis/forceSolid
/gate/RF56/vis/setColor yellow
/gate/RF56/repeaters/insert linear
/gate/RF56/linear/setRepeatNumber 40
/gate/RF56/linear/setRepeatVector 5 0 0 mm
/gate/RF56/linear/autoCenter false
/gate/RF_box/daughters/name RF57
/gate/RF_box/daughters/insert box
/gate/RF57/setMaterial Aluminium
/gate/RF57/geometry/setXLength 0.001000 cm
/gate/RF57/geometry/setYLength 20 cm
/gate/RF57/geometry/setZLength 1.403000 cm
/gate/RF57/placement/setTranslation -9.881500 0 -2.298500 cm
/gate/RF57/vis/forceSolid
/gate/RF57/vis/setColor yellow
/gate/RF57/repeaters/insert linear
/gate/RF57/linear/setRepeatNumber 40
/gate/RF57/linear/setRepeatVector 5 0 0 mm
/gate/RF57/linear/autoCenter false
/gate/RF_box/daughters/name RF58
/gate/RF_box/daughters/insert box
/gate/RF58/setMaterial Aluminium
/gate/RF58/geometry/setXLength 0.001000 cm
/gate/RF58/geometry/setYLength 20 cm
/gate/RF58/geometry/setZLength 1.426000 cm
/gate/RF58/placement/setTranslation -9.880500 0 -2.287000 cm
/gate/RF58/vis/forceSolid
/gate/RF58/vis/setColor yellow
/gate/RF58/repeaters/insert linear
/gate/RF58/linear/setRepeatNumber 40
/gate/RF58/linear/setRepeatVector 5 0 0 mm
/gate/RF58/linear/autoCenter false
/gate/RF_box/daughters/name RF59
/gate/RF_box/daughters/insert box
/gate/RF59/setMaterial Aluminium
/gate/RF59/geometry/setXLength 0.001000 cm
/gate/RF59/geometry/setYLength 20 cm
/gate/RF59/geometry/setZLength 1.449000 cm
/gate/RF59/placement/setTranslation -9.879500 0 -2.275500 cm
/gate/RF59/vis/forceSolid
/gate/RF59/vis/setColor yellow
/gate/RF59/repeaters/insert linear
/gate/RF59/linear/setRepeatNumber 40
/gate/RF59/linear/setRepeatVector 5 0 0 mm
/gate/RF59/linear/autoCenter false
/gate/RF_box/daughters/name RF60
/gate/RF_box/daughters/insert box
/gate/RF60/setMaterial Aluminium
/gate/RF60/geometry/setXLength 0.002000 cm
/gate/RF60/geometry/setYLength 20 cm
/gate/RF60/geometry/setZLength 1.471000 cm
/gate/RF60/placement/setTranslation -9.878000 0 -2.264500 cm
/gate/RF60/vis/forceSolid
/gate/RF60/vis/setColor yellow
/gate/RF60/repeaters/insert linear
/gate/RF60/linear/setRepeatNumber 40
/gate/RF60/linear/setRepeatVector 5 0 0 mm
/gate/RF60/linear/autoCenter false
/gate/RF_box/daughters/name RF61
/gate/RF_box/daughters/insert box
/gate/RF61/setMaterial Aluminium
/gate/RF61/geometry/setXLength 0.001000 cm
/gate/RF61/geometry/setYLength 20 cm
/gate/RF61/geometry/setZLength 1.494000 cm
/gate/RF61/placement/setTranslation -9.876500 0 -2.253000 cm
/gate/RF61/vis/forceSolid
/gate/RF61/vis/setColor yellow
/gate/RF61/repeaters/insert linear
/gate/RF61/linear/setRepeatNumber 40
/gate/RF61/linear/setRepeatVector 5 0 0 mm
/gate/RF61/linear/autoCenter false
/gate/RF_box/daughters/name RF62
/gate/RF_box/daughters/insert box
/gate/RF62/setMaterial Aluminium
/gate/RF62/geometry/setXLength 0.001000 cm
/gate/RF62/geometry/setYLength 20 cm
/gate/RF62/geometry/setZLength 1.517000 cm
/gate/RF62/placement/setTranslation -9.875500 0 -2.241500 cm
/gate/RF62/vis/forceSolid
/gate/RF62/vis/setColor yellow
/gate/RF62/repeaters/insert linear
/gate/RF62/linear/setRepeatNumber 40
/gate/RF62/linear/setRepeatVector 5 0 0 mm
/gate/RF62/linear/autoCenter false
/gate/RF_box/daughters/name RF63
/gate/RF_box/daughters/insert box
/gate/RF63/setMaterial Aluminium
/gate/RF63/geometry/setXLength 0.001000 cm
/gate/RF63/geometry/setYLength 20 cm
/gate/RF63/geometry/setZLength 1.539000 cm
/gate/RF63/placement/setTranslation -9.874500 0 -2.230500 cm
/gate/RF63/vis/forceSolid
/gate/RF63/vis/setColor yellow
/gate/RF63/repeaters/insert linear
/gate/RF63/linear/setRepeatNumber 40
/gate/RF63/linear/setRepeatVector 5 0 0 mm
/gate/RF63/linear/autoCenter false
/gate/RF_box/daughters/name RF64
/gate/RF_box/daughters/insert box
/gate/RF64/setMaterial Aluminium
/gate/RF64/geometry/setXLength 0.001000 cm
/gate/RF64/geometry/setYLength 20 cm
/gate/RF64/geometry/setZLength 1.562000 cm
/gate/RF64/placement/setTranslation -9.873500 0 -2.219000 cm
/gate/RF64/vis/forceSolid
/gate/RF64/vis/setColor yellow
/gate/RF64/repeaters/insert linear
/gate/RF64/linear/setRepeatNumber 40
/gate/RF64/linear/setRepeatVector 5 0 0 mm
/gate/RF64/linear/autoCenter false
/gate/RF_box/daughters/name RF65
/gate/RF_box/daughters/insert box
/gate/RF65/setMaterial Aluminium
/gate/RF65/geometry/setXLength 0.001000 cm
/gate/RF65/geometry/setYLength 20 cm
/gate/RF65/geometry/setZLength 1.584000 cm
/gate/RF65/placement/setTranslation -9.872500 0 -2.208000 cm
/gate/RF65/vis/forceSolid
/gate/RF65/vis/setColor yellow
/gate/RF65/repeaters/insert linear
/gate/RF65/linear/setRepeatNumber 40
/gate/RF65/linear/setRepeatVector 5 0 0 mm
/gate/RF65/linear/autoCenter false
/gate/RF_box/daughters/name RF66
/gate/RF_box/daughters/insert box
/gate/RF66/setMaterial Aluminium
/gate/RF66/geometry/setXLength 0.001000 cm
/gate/RF66/geometry/setYLength 20 cm
/gate/RF66/geometry/setZLength 1.607000 cm
/gate/RF66/placement/setTranslation -9.871500 0 -2.196500 cm
/gate/RF66/vis/forceSolid
/gate/RF66/vis/setColor yellow
/gate/RF66/repeaters/insert linear
/gate/RF66/linear/setRepeatNumber 40
/gate/RF66/linear/setRepeatVector 5 0 0 mm
/gate/RF66/linear/autoCenter false
/gate/RF_box/daughters/name RF67
/gate/RF_box/daughters/insert box
/gate/RF67/setMaterial Aluminium
/gate/RF67/geometry/setXLength 0.001000 cm
/gate/RF67/geometry/setYLength 20 cm
/gate/RF67/geometry/setZLength 1.630000 cm
/gate/RF67/placement/setTranslation -9.870500 0 -2.185000 cm
/gate/RF67/vis/forceSolid
/gate/RF67/vis/setColor yellow
/gate/RF67/repeaters/insert linear
/gate/RF67/linear/setRepeatNumber 40
/gate/RF67/linear/setRepeatVector 5 0 0 mm
/gate/RF67/linear/autoCenter false
/gate/RF_box/daughters/name RF68
/gate/RF_box/daughters/insert box
/gate/RF68/setMaterial Aluminium
/gate/RF68/geometry/setXLength 0.001000 cm
/gate/RF68/geometry/setYLength 20 cm
/gate/RF68/geometry/setZLength 1.652000 cm
/gate/RF68/placement/setTranslation -9.869500 0 -2.174000 cm
/gate/RF68/vis/forceSolid
/gate/RF68/vis/setColor yellow
/gate/RF68/repeaters/insert linear
/gate/RF68/linear/setRepeatNumber 40
/gate/RF68/linear/setRepeatVector 5 0 0 mm
/gate/RF68/linear/autoCenter false
/gate/RF_box/daughters/name RF69
/gate/RF_box/daughters/insert box
/gate/RF69/setMaterial Aluminium
/gate/RF69/geometry/setXLength 0.001000 cm
/gate/RF69/geometry/setYLength 20 cm
/gate/RF69/geometry/setZLength 1.675000 cm
/gate/RF69/placement/setTranslation -9.868500 0 -2.162500 cm
/gate/RF69/vis/forceSolid
/gate/RF69/vis/setColor yellow
/gate/RF69/repeaters/insert linear
/gate/RF69/linear/setRepeatNumber 40
/gate/RF69/linear/setRepeatVector 5 0 0 mm
/gate/RF69/linear/autoCenter false
/gate/RF_box/daughters/name RF70
/gate/RF_box/daughters/insert box
/gate/RF70/setMaterial Aluminium
/gate/RF70/geometry/setXLength 0.001000 cm
/gate/RF70/geometry/setYLength 20 cm
/gate/RF70/geometry/setZLength 1.698000 cm
/gate/RF70/placement/setTranslation -9.867500 0 -2.151000 cm
/gate/RF70/vis/forceSolid
/gate/RF70/vis/setColor yellow
/gate/RF70/repeaters/insert linear
/gate/RF70/linear/setRepeatNumber 40
/gate/RF70/linear/setRepeatVector 5 0 0 mm
/gate/RF70/linear/autoCenter false
/gate/RF_box/daughters/name RF71
/gate/RF_box/daughters/insert box
/gate/RF71/setMaterial Aluminium
/gate/RF71/geometry/setXLength 0.002000 cm
/gate/RF71/geometry/setYLength 20 cm
/gate/RF71/geometry/setZLength 1.720000 cm
/gate/RF71/placement/setTranslation -9.866000 0 -2.140000 cm
/gate/RF71/vis/forceSolid
/gate/RF71/vis/setColor yellow
/gate/RF71/repeaters/insert linear
/gate/RF71/linear/setRepeatNumber 40
/gate/RF71/linear/setRepeatVector 5 0 0 mm
/gate/RF71/linear/autoCenter false
/gate/RF_box/daughters/name RF72
/gate/RF_box/daughters/insert box
/gate/RF72/setMaterial Aluminium
/gate/RF72/geometry/setXLength 0.001000 cm
/gate/RF72/geometry/setYLength 20 cm
/gate/RF72/geometry/setZLength 1.743000 cm
/gate/RF72/placement/setTranslation -9.864500 0 -2.128500 cm
/gate/RF72/vis/forceSolid
/gate/RF72/vis/setColor yellow
/gate/RF72/repeaters/insert linear
/gate/RF72/linear/setRepeatNumber 40
/gate/RF72/linear/setRepeatVector 5 0 0 mm
/gate/RF72/linear/autoCenter false
/gate/RF_box/daughters/name RF73
/gate/RF_box/daughters/insert box
/gate/RF73/setMaterial Aluminium
/gate/RF73/geometry/setXLength 0.001000 cm
/gate/RF73/geometry/setYLength 20 cm
/gate/RF73/geometry/setZLength 1.766000 cm
/gate/RF73/placement/setTranslation -9.863500 0 -2.117000 cm
/gate/RF73/vis/forceSolid
/gate/RF73/vis/setColor yellow
/gate/RF73/repeaters/insert linear
/gate/RF73/linear/setRepeatNumber 40
/gate/RF73/linear/setRepeatVector 5 0 0 mm
/gate/RF73/linear/autoCenter false
/gate/RF_box/daughters/name RF74
/gate/RF_box/daughters/insert box
/gate/RF74/setMaterial Aluminium
/gate/RF74/geometry/setXLength 0.001000 cm
/gate/RF74/geometry/setYLength 20 cm
/gate/RF74/geometry/setZLength 1.788000 cm
/gate/RF74/placement/setTranslation -9.862500 0 -2.106000 cm
/gate/RF74/vis/forceSolid
/gate/RF74/vis/setColor yellow
/gate/RF74/repeaters/insert linear
/gate/RF74/linear/setRepeatNumber 40
/gate/RF74/linear/setRepeatVector 5 0 0 mm
/gate/RF74/linear/autoCenter false
/gate/RF_box/daughters/name RF75
/gate/RF_box/daughters/insert box
/gate/RF75/setMaterial Aluminium
/gate/RF75/geometry/setXLength 0.001000 cm
/gate/RF75/geometry/setYLength 20 cm
/gate/RF75/geometry/setZLength 1.811000 cm
/gate/RF75/placement/setTranslation -9.861500 0 -2.094500 cm
/gate/RF75/vis/forceSolid
/gate/RF75/vis/setColor yellow
/gate/RF75/repeaters/insert linear
/gate/RF75/linear/setRepeatNumber 40
/gate/RF75/linear/setRepeatVector 5 0 0 mm
/gate/RF75/linear/autoCenter false
/gate/RF_box/daughters/name RF76
/gate/RF_box/daughters/insert box
/gate/RF76/setMaterial Aluminium
/gate/RF76/geometry/setXLength 0.001000 cm
/gate/RF76/geometry/setYLength 20 cm
/gate/RF76/geometry/setZLength 1.833000 cm
/gate/RF76/placement/setTranslation -9.860500 0 -2.083500 cm
/gate/RF76/vis/forceSolid
/gate/RF76/vis/setColor yellow
/gate/RF76/repeaters/insert linear
/gate/RF76/linear/setRepeatNumber 40
/gate/RF76/linear/setRepeatVector 5 0 0 mm
/gate/RF76/linear/autoCenter false
/gate/RF_box/daughters/name RF77
/gate/RF_box/daughters/insert box
/gate/RF77/setMaterial Aluminium
/gate/RF77/geometry/setXLength 0.001000 cm
/gate/RF77/geometry/setYLength 20 cm
/gate/RF77/geometry/setZLength 1.856000 cm
/gate/RF77/placement/setTranslation -9.859500 0 -2.072000 cm
/gate/RF77/vis/forceSolid
/gate/RF77/vis/setColor yellow
/gate/RF77/repeaters/insert linear
/gate/RF77/linear/setRepeatNumber 40
/gate/RF77/linear/setRepeatVector 5 0 0 mm
/gate/RF77/linear/autoCenter false
/gate/RF_box/daughters/name RF78
/gate/RF_box/daughters/insert box
/gate/RF78/setMaterial Aluminium
/gate/RF78/geometry/setXLength 0.001000 cm
/gate/RF78/geometry/setYLength 20 cm
/gate/RF78/geometry/setZLength 1.879000 cm
/gate/RF78/placement/setTranslation -9.858500 0 -2.060500 cm
/gate/RF78/vis/forceSolid
/gate/RF78/vis/setColor yellow
/gate/RF78/repeaters/insert linear
/gate/RF78/linear/setRepeatNumber 40
/gate/RF78/linear/setRepeatVector 5 0 0 mm
/gate/RF78/linear/autoCenter false
/gate/RF_box/daughters/name RF79
/gate/RF_box/daughters/insert box
/gate/RF79/setMaterial Aluminium
/gate/RF79/geometry/setXLength 0.001000 cm
/gate/RF79/geometry/setYLength 20 cm
/gate/RF79/geometry/setZLength 1.901000 cm
/gate/RF79/placement/setTranslation -9.857500 0 -2.049500 cm
/gate/RF79/vis/forceSolid
/gate/RF79/vis/setColor yellow
/gate/RF79/repeaters/insert linear
/gate/RF79/linear/setRepeatNumber 40
/gate/RF79/linear/setRepeatVector 5 0 0 mm
/gate/RF79/linear/autoCenter false
/gate/RF_box/daughters/name RF80
/gate/RF_box/daughters/insert box
/gate/RF80/setMaterial Aluminium
/gate/RF80/geometry/setXLength 0.001000 cm
/gate/RF80/geometry/setYLength 20 cm
/gate/RF80/geometry/setZLength 1.924000 cm
/gate/RF80/placement/setTranslation -9.856500 0 -2.038000 cm
/gate/RF80/vis/forceSolid
/gate/RF80/vis/setColor yellow
/gate/RF80/repeaters/insert linear
/gate/RF80/linear/setRepeatNumber 40
/gate/RF80/linear/setRepeatVector 5 0 0 mm
/gate/RF80/linear/autoCenter false
/gate/RF_box/daughters/name RF81
/gate/RF_box/daughters/insert box
/gate/RF81/setMaterial Aluminium
/gate/RF81/geometry/setXLength 0.001000 cm
/gate/RF81/geometry/setYLength 20 cm
/gate/RF81/geometry/setZLength 1.947000 cm
/gate/RF81/placement/setTranslation -9.855500 0 -2.026500 cm
/gate/RF81/vis/forceSolid
/gate/RF81/vis/setColor yellow
/gate/RF81/repeaters/insert linear
/gate/RF81/linear/setRepeatNumber 40
/gate/RF81/linear/setRepeatVector 5 0 0 mm
/gate/RF81/linear/autoCenter false
/gate/RF_box/daughters/name RF82
/gate/RF_box/daughters/insert box
/gate/RF82/setMaterial Aluminium
/gate/RF82/geometry/setXLength 0.001000 cm
/gate/RF82/geometry/setYLength 20 cm
/gate/RF82/geometry/setZLength 1.969000 cm
/gate/RF82/placement/setTranslation -9.854500 0 -2.015500 cm
/gate/RF82/vis/forceSolid
/gate/RF82/vis/setColor yellow
/gate/RF82/repeaters/insert linear
/gate/RF82/linear/setRepeatNumber 40
/gate/RF82/linear/setRepeatVector 5 0 0 mm
/gate/RF82/linear/autoCenter false
/gate/RF_box/daughters/name RF83
/gate/RF_box/daughters/insert box
/gate/RF83/setMaterial Aluminium
/gate/RF83/geometry/setXLength 0.001000 cm
/gate/RF83/geometry/setYLength 20 cm
/gate/RF83/geometry/setZLength 1.992000 cm
/gate/RF83/placement/setTranslation -9.853500 0 -2.004000 cm
/gate/RF83/vis/forceSolid
/gate/RF83/vis/setColor yellow
/gate/RF83/repeaters/insert linear
/gate/RF83/linear/setRepeatNumber 40
/gate/RF83/linear/setRepeatVector 5 0 0 mm
/gate/RF83/linear/autoCenter false
/gate/RF_box/daughters/name RF84
/gate/RF_box/daughters/insert box
/gate/RF84/setMaterial Aluminium
/gate/RF84/geometry/setXLength 0.001000 cm
/gate/RF84/geometry/setYLength 20 cm
/gate/RF84/geometry/setZLength 2.014000 cm
/gate/RF84/placement/setTranslation -9.852500 0 -1.993000 cm
/gate/RF84/vis/forceSolid
/gate/RF84/vis/setColor yellow
/gate/RF84/repeaters/insert linear
/gate/RF84/linear/setRepeatNumber 40
/gate/RF84/linear/setRepeatVector 5 0 0 mm
/gate/RF84/linear/autoCenter false
/gate/RF_box/daughters/name RF85
/gate/RF_box/daughters/insert box
/gate/RF85/setMaterial Aluminium
/gate/RF85/geometry/setXLength 0.001000 cm
/gate/RF85/geometry/setYLength 20 cm
/gate/RF85/geometry/setZLength 2.037000 cm
/gate/RF85/placement/setTranslation -9.851500 0 -1.981500 cm
/gate/RF85/vis/forceSolid
/gate/RF85/vis/setColor yellow
/gate/RF85/repeaters/insert linear
/gate/RF85/linear/setRepeatNumber 40
/gate/RF85/linear/setRepeatVector 5 0 0 mm
/gate/RF85/linear/autoCenter false
/gate/RF_box/daughters/name RF86
/gate/RF_box/daughters/insert box
/gate/RF86/setMaterial Aluminium
/gate/RF86/geometry/setXLength 0.001000 cm
/gate/RF86/geometry/setYLength 20 cm
/gate/RF86/geometry/setZLength 2.060000 cm
/gate/RF86/placement/setTranslation -9.850500 0 -1.970000 cm
/gate/RF86/vis/forceSolid
/gate/RF86/vis/setColor yellow
/gate/RF86/repeaters/insert linear
/gate/RF86/linear/setRepeatNumber 40
/gate/RF86/linear/setRepeatVector 5 0 0 mm
/gate/RF86/linear/autoCenter false
/gate/RF_box/daughters/name RF87
/gate/RF_box/daughters/insert box
/gate/RF87/setMaterial Aluminium
/gate/RF87/geometry/setXLength 0.001000 cm
/gate/RF87/geometry/setYLength 20 cm
/gate/RF87/geometry/setZLength 2.082000 cm
/gate/RF87/placement/setTranslation -9.849500 0 -1.959000 cm
/gate/RF87/vis/forceSolid
/gate/RF87/vis/setColor yellow
/gate/RF87/repeaters/insert linear
/gate/RF87/linear/setRepeatNumber 40
/gate/RF87/linear/setRepeatVector 5 0 0 mm
/gate/RF87/linear/autoCenter false
/gate/RF_box/daughters/name RF88
/gate/RF_box/daughters/insert box
/gate/RF88/setMaterial Aluminium
/gate/RF88/geometry/setXLength 0.001000 cm
/gate/RF88/geometry/setYLength 20 cm
/gate/RF88/geometry/setZLength 2.105000 cm
/gate/RF88/placement/setTranslation -9.848500 0 -1.947500 cm
/gate/RF88/vis/forceSolid
/gate/RF88/vis/setColor yellow
/gate/RF88/repeaters/insert linear
/gate/RF88/linear/setRepeatNumber 40
/gate/RF88/linear/setRepeatVector 5 0 0 mm
/gate/RF88/linear/autoCenter false
/gate/RF_box/daughters/name RF89
/gate/RF_box/daughters/insert box
/gate/RF89/setMaterial Aluminium
/gate/RF89/geometry/setXLength 0.001000 cm
/gate/RF89/geometry/setYLength 20 cm
/gate/RF89/geometry/setZLength 2.128000 cm
/gate/RF89/placement/setTranslation -9.847500 0 -1.936000 cm
/gate/RF89/vis/forceSolid
/gate/RF89/vis/setColor yellow
/gate/RF89/repeaters/insert linear
/gate/RF89/linear/setRepeatNumber 40
/gate/RF89/linear/setRepeatVector 5 0 0 mm
/gate/RF89/linear/autoCenter false
/gate/RF_box/daughters/name RF90
/gate/RF_box/daughters/insert box
/gate/RF90/setMaterial Aluminium
/gate/RF90/geometry/setXLength 0.001000 cm
/gate/RF90/geometry/setYLength 20 cm
/gate/RF90/geometry/setZLength 2.150000 cm
/gate/RF90/placement/setTranslation -9.846500 0 -1.925000 cm
/gate/RF90/vis/forceSolid
/gate/RF90/vis/setColor yellow
/gate/RF90/repeaters/insert linear
/gate/RF90/linear/setRepeatNumber 40
/gate/RF90/linear/setRepeatVector 5 0 0 mm
/gate/RF90/linear/autoCenter false
/gate/RF_box/daughters/name RF91
/gate/RF_box/daughters/insert box
/gate/RF91/setMaterial Aluminium
/gate/RF91/geometry/setXLength 0.001000 cm
/gate/RF91/geometry/setYLength 20 cm
/gate/RF91/geometry/setZLength 2.173000 cm
/gate/RF91/placement/setTranslation -9.845500 0 -1.913500 cm
/gate/RF91/vis/forceSolid
/gate/RF91/vis/setColor yellow
/gate/RF91/repeaters/insert linear
/gate/RF91/linear/setRepeatNumber 40
/gate/RF91/linear/setRepeatVector 5 0 0 mm
/gate/RF91/linear/autoCenter false
/gate/RF_box/daughters/name RF92
/gate/RF_box/daughters/insert box
/gate/RF92/setMaterial Aluminium
/gate/RF92/geometry/setXLength 0.001000 cm
/gate/RF92/geometry/setYLength 20 cm
/gate/RF92/geometry/setZLength 2.196000 cm
/gate/RF92/placement/setTranslation -9.844500 0 -1.902000 cm
/gate/RF92/vis/forceSolid
/gate/RF92/vis/setColor yellow
/gate/RF92/repeaters/insert linear
/gate/RF92/linear/setRepeatNumber 40
/gate/RF92/linear/setRepeatVector 5 0 0 mm
/gate/RF92/linear/autoCenter false
/gate/RF_box/daughters/name RF93
/gate/RF_box/daughters/insert box
/gate/RF93/setMaterial Aluminium
/gate/RF93/geometry/setXLength 0.001000 cm
/gate/RF93/geometry/setYLength 20 cm
/gate/RF93/geometry/setZLength 2.218000 cm
/gate/RF93/placement/setTranslation -9.843500 0 -1.891000 cm
/gate/RF93/vis/forceSolid
/gate/RF93/vis/setColor yellow
/gate/RF93/repeaters/insert linear
/gate/RF93/linear/setRepeatNumber 40
/gate/RF93/linear/setRepeatVector 5 0 0 mm
/gate/RF93/linear/autoCenter false
/gate/RF_box/daughters/name RF94
/gate/RF_box/daughters/insert box
/gate/RF94/setMaterial Aluminium
/gate/RF94/geometry/setXLength 0.001000 cm
/gate/RF94/geometry/setYLength 20 cm
/gate/RF94/geometry/setZLength 2.241000 cm
/gate/RF94/placement/setTranslation -9.842500 0 -1.879500 cm
/gate/RF94/vis/forceSolid
/gate/RF94/vis/setColor yellow
/gate/RF94/repeaters/insert linear
/gate/RF94/linear/setRepeatNumber 40
/gate/RF94/linear/setRepeatVector 5 0 0 mm
/gate/RF94/linear/autoCenter false
/gate/RF_box/daughters/name RF95
/gate/RF_box/daughters/insert box
/gate/RF95/setMaterial Aluminium
/gate/RF95/geometry/setXLength 0.001000 cm
/gate/RF95/geometry/setYLength 20 cm
/gate/RF95/geometry/setZLength 2.263000 cm
/gate/RF95/placement/setTranslation -9.841500 0 -1.868500 cm
/gate/RF95/vis/forceSolid
/gate/RF95/vis/setColor yellow
/gate/RF95/repeaters/insert linear
/gate/RF95/linear/setRepeatNumber 40
/gate/RF95/linear/setRepeatVector 5 0 0 mm
/gate/RF95/linear/autoCenter false
/gate/RF_box/daughters/name RF96
/gate/RF_box/daughters/insert box
/gate/RF96/setMaterial Aluminium
/gate/RF96/geometry/setXLength 0.001000 cm
/gate/RF96/geometry/setYLength 20 cm
/gate/RF96/geometry/setZLength 2.286000 cm
/gate/RF96/placement/setTranslation -9.840500 0 -1.857000 cm
/gate/RF96/vis/forceSolid
/gate/RF96/vis/setColor yellow
/gate/RF96/repeaters/insert linear
/gate/RF96/linear/setRepeatNumber 40
/gate/RF96/linear/setRepeatVector 5 0 0 mm
/gate/RF96/linear/autoCenter false
/gate/RF_box/daughters/name RF97
/gate/RF_box/daughters/insert box
/gate/RF97/setMaterial Aluminium
/gate/RF97/geometry/setXLength 0.001000 cm
/gate/RF97/geometry/setYLength 20 cm
/gate/RF97/geometry/setZLength 2.309000 cm
/gate/RF97/placement/setTranslation -9.839500 0 -1.845500 cm
/gate/RF97/vis/forceSolid
/gate/RF97/vis/setColor yellow
/gate/RF97/repeaters/insert linear
/gate/RF97/linear/setRepeatNumber 40
/gate/RF97/linear/setRepeatVector 5 0 0 mm
/gate/RF97/linear/autoCenter false
/gate/RF_box/daughters/name RF98
/gate/RF_box/daughters/insert box
/gate/RF98/setMaterial Aluminium
/gate/RF98/geometry/setXLength 0.001000 cm
/gate/RF98/geometry/setYLength 20 cm
/gate/RF98/geometry/setZLength 2.331000 cm
/gate/RF98/placement/setTranslation -9.838500 0 -1.834500 cm
/gate/RF98/vis/forceSolid
/gate/RF98/vis/setColor yellow
/gate/RF98/repeaters/insert linear
/gate/RF98/linear/setRepeatNumber 40
/gate/RF98/linear/setRepeatVector 5 0 0 mm
/gate/RF98/linear/autoCenter false
/gate/RF_box/daughters/name RF99
/gate/RF_box/daughters/insert box
/gate/RF99/setMaterial Aluminium
/gate/RF99/geometry/setXLength 0.001000 cm
/gate/RF99/geometry/setYLength 20 cm
/gate/RF99/geometry/setZLength 2.354000 cm
/gate/RF99/placement/setTranslation -9.837500 0 -1.823000 cm
/gate/RF99/vis/forceSolid
/gate/RF99/vis/setColor yellow
/gate/RF99/repeaters/insert linear
/gate/RF99/linear/setRepeatNumber 40
/gate/RF99/linear/setRepeatVector 5 0 0 mm
/gate/RF99/linear/autoCenter false
/gate/RF_box/daughters/name RF100
/gate/RF_box/daughters/insert box
/gate/RF100/setMaterial Aluminium
/gate/RF100/geometry/setXLength 0.001000 cm
/gate/RF100/geometry/setYLength 20 cm
/gate/RF100/geometry/setZLength 2.377000 cm
/gate/RF100/placement/setTranslation -9.836500 0 -1.811500 cm
/gate/RF100/vis/forceSolid
/gate/RF100/vis/setColor yellow
/gate/RF100/repeaters/insert linear
/gate/RF100/linear/setRepeatNumber 40
/gate/RF100/linear/setRepeatVector 5 0 0 mm
/gate/RF100/linear/autoCenter false
/gate/RF_box/daughters/name RF101
/gate/RF_box/daughters/insert box
/gate/RF101/setMaterial Aluminium
/gate/RF101/geometry/setXLength 0.001000 cm
/gate/RF101/geometry/setYLength 20 cm
/gate/RF101/geometry/setZLength 2.399000 cm
/gate/RF101/placement/setTranslation -9.835500 0 -1.800500 cm
/gate/RF101/vis/forceSolid
/gate/RF101/vis/setColor yellow
/gate/RF101/repeaters/insert linear
/gate/RF101/linear/setRepeatNumber 40
/gate/RF101/linear/setRepeatVector 5 0 0 mm
/gate/RF101/linear/autoCenter false
/gate/RF_box/daughters/name RF102
/gate/RF_box/daughters/insert box
/gate/RF102/setMaterial Aluminium
/gate/RF102/geometry/setXLength 0.001000 cm
/gate/RF102/geometry/setYLength 20 cm
/gate/RF102/geometry/setZLength 2.422000 cm
/gate/RF102/placement/setTranslation -9.834500 0 -1.789000 cm
/gate/RF102/vis/forceSolid
/gate/RF102/vis/setColor yellow
/gate/RF102/repeaters/insert linear
/gate/RF102/linear/setRepeatNumber 40
/gate/RF102/linear/setRepeatVector 5 0 0 mm
/gate/RF102/linear/autoCenter false
/gate/RF_box/daughters/name RF103
/gate/RF_box/daughters/insert box
/gate/RF103/setMaterial Aluminium
/gate/RF103/geometry/setXLength 0.001000 cm
/gate/RF103/geometry/setYLength 20 cm
/gate/RF103/geometry/setZLength 2.445000 cm
/gate/RF103/placement/setTranslation -9.833500 0 -1.777500 cm
/gate/RF103/vis/forceSolid
/gate/RF103/vis/setColor yellow
/gate/RF103/repeaters/insert linear
/gate/RF103/linear/setRepeatNumber 40
/gate/RF103/linear/setRepeatVector 5 0 0 mm
/gate/RF103/linear/autoCenter false
/gate/RF_box/daughters/name RF104
/gate/RF_box/daughters/insert box
/gate/RF104/setMaterial Aluminium
/gate/RF104/geometry/setXLength 0.001000 cm
/gate/RF104/geometry/setYLength 20 cm
/gate/RF104/geometry/setZLength 2.467000 cm
/gate/RF104/placement/setTranslation -9.832500 0 -1.766500 cm
/gate/RF104/vis/forceSolid
/gate/RF104/vis/setColor yellow
/gate/RF104/repeaters/insert linear
/gate/RF104/linear/setRepeatNumber 40
/gate/RF104/linear/setRepeatVector 5 0 0 mm
/gate/RF104/linear/autoCenter false
/gate/RF_box/daughters/name RF105
/gate/RF_box/daughters/insert box
/gate/RF105/setMaterial Aluminium
/gate/RF105/geometry/setXLength 0.001000 cm
/gate/RF105/geometry/setYLength 20 cm
/gate/RF105/geometry/setZLength 2.490000 cm
/gate/RF105/placement/setTranslation -9.831500 0 -1.755000 cm
/gate/RF105/vis/forceSolid
/gate/RF105/vis/setColor yellow
/gate/RF105/repeaters/insert linear
/gate/RF105/linear/setRepeatNumber 40
/gate/RF105/linear/setRepeatVector 5 0 0 mm
/gate/RF105/linear/autoCenter false
/gate/RF_box/daughters/name RF107
/gate/RF_box/daughters/insert box
/gate/RF107/setMaterial Aluminium
/gate/RF107/geometry/setXLength 0.001000 cm
/gate/RF107/geometry/setYLength 20 cm
/gate/RF107/geometry/setZLength 2.535000 cm
/gate/RF107/placement/setTranslation -9.830500 0 -1.732500 cm
/gate/RF107/vis/forceSolid
/gate/RF107/vis/setColor yellow
/gate/RF107/repeaters/insert linear
/gate/RF107/linear/setRepeatNumber 40
/gate/RF107/linear/setRepeatVector 5 0 0 mm
/gate/RF107/linear/autoCenter false
/gate/RF_box/daughters/name RF108
/gate/RF_box/daughters/insert box
/gate/RF108/setMaterial Aluminium
/gate/RF108/geometry/setXLength 0.001000 cm
/gate/RF108/geometry/setYLength 20 cm
/gate/RF108/geometry/setZLength 2.558000 cm
/gate/RF108/placement/setTranslation -9.829500 0 -1.721000 cm
/gate/RF108/vis/forceSolid
/gate/RF108/vis/setColor yellow
/gate/RF108/repeaters/insert linear
/gate/RF108/linear/setRepeatNumber 40
/gate/RF108/linear/setRepeatVector 5 0 0 mm
/gate/RF108/linear/autoCenter false
/gate/RF_box/daughters/name RF109
/gate/RF_box/daughters/insert box
/gate/RF109/setMaterial Aluminium
/gate/RF109/geometry/setXLength 0.001000 cm
/gate/RF109/geometry/setYLength 20 cm
/gate/RF109/geometry/setZLength 2.580000 cm
/gate/RF109/placement/setTranslation -9.828500 0 -1.710000 cm
/gate/RF109/vis/forceSolid
/gate/RF109/vis/setColor yellow
/gate/RF109/repeaters/insert linear
/gate/RF109/linear/setRepeatNumber 40
/gate/RF109/linear/setRepeatVector 5 0 0 mm
/gate/RF109/linear/autoCenter false
/gate/RF_box/daughters/name RF110
/gate/RF_box/daughters/insert box
/gate/RF110/setMaterial Aluminium
/gate/RF110/geometry/setXLength 0.001000 cm
/gate/RF110/geometry/setYLength 20 cm
/gate/RF110/geometry/setZLength 2.603000 cm
/gate/RF110/placement/setTranslation -9.827500 0 -1.698500 cm
/gate/RF110/vis/forceSolid
/gate/RF110/vis/setColor yellow
/gate/RF110/repeaters/insert linear
/gate/RF110/linear/setRepeatNumber 40
/gate/RF110/linear/setRepeatVector 5 0 0 mm
/gate/RF110/linear/autoCenter false
/gate/RF_box/daughters/name RF111
/gate/RF_box/daughters/insert box
/gate/RF111/setMaterial Aluminium
/gate/RF111/geometry/setXLength 0.001000 cm
/gate/RF111/geometry/setYLength 20 cm
/gate/RF111/geometry/setZLength 2.626000 cm
/gate/RF111/placement/setTranslation -9.826500 0 -1.687000 cm
/gate/RF111/vis/forceSolid
/gate/RF111/vis/setColor yellow
/gate/RF111/repeaters/insert linear
/gate/RF111/linear/setRepeatNumber 40
/gate/RF111/linear/setRepeatVector 5 0 0 mm
/gate/RF111/linear/autoCenter false
/gate/RF_box/daughters/name RF112
/gate/RF_box/daughters/insert box
/gate/RF112/setMaterial Aluminium
/gate/RF112/geometry/setXLength 0.001000 cm
/gate/RF112/geometry/setYLength 20 cm
/gate/RF112/geometry/setZLength 2.648000 cm
/gate/RF112/placement/setTranslation -9.825500 0 -1.676000 cm
/gate/RF112/vis/forceSolid
/gate/RF112/vis/setColor yellow
/gate/RF112/repeaters/insert linear
/gate/RF112/linear/setRepeatNumber 40
/gate/RF112/linear/setRepeatVector 5 0 0 mm
/gate/RF112/linear/autoCenter false
/gate/RF_box/daughters/name RF113
/gate/RF_box/daughters/insert box
/gate/RF113/setMaterial Aluminium
/gate/RF113/geometry/setXLength 0.001000 cm
/gate/RF113/geometry/setYLength 20 cm
/gate/RF113/geometry/setZLength 2.671000 cm
/gate/RF113/placement/setTranslation -9.824500 0 -1.664500 cm
/gate/RF113/vis/forceSolid
/gate/RF113/vis/setColor yellow
/gate/RF113/repeaters/insert linear
/gate/RF113/linear/setRepeatNumber 40
/gate/RF113/linear/setRepeatVector 5 0 0 mm
/gate/RF113/linear/autoCenter false
/gate/RF_box/daughters/name RF114
/gate/RF_box/daughters/insert box
/gate/RF114/setMaterial Aluminium
/gate/RF114/geometry/setXLength 0.001000 cm
/gate/RF114/geometry/setYLength 20 cm
/gate/RF114/geometry/setZLength 2.694000 cm
/gate/RF114/placement/setTranslation -9.823500 0 -1.653000 cm
/gate/RF114/vis/forceSolid
/gate/RF114/vis/setColor yellow
/gate/RF114/repeaters/insert linear
/gate/RF114/linear/setRepeatNumber 40
/gate/RF114/linear/setRepeatVector 5 0 0 mm
/gate/RF114/linear/autoCenter false
/gate/RF_box/daughters/name RF115
/gate/RF_box/daughters/insert box
/gate/RF115/setMaterial Aluminium
/gate/RF115/geometry/setXLength 0.001000 cm
/gate/RF115/geometry/setYLength 20 cm
/gate/RF115/geometry/setZLength 2.716000 cm
/gate/RF115/placement/setTranslation -9.822500 0 -1.642000 cm
/gate/RF115/vis/forceSolid
/gate/RF115/vis/setColor yellow
/gate/RF115/repeaters/insert linear
/gate/RF115/linear/setRepeatNumber 40
/gate/RF115/linear/setRepeatVector 5 0 0 mm
/gate/RF115/linear/autoCenter false
/gate/RF_box/daughters/name RF116
/gate/RF_box/daughters/insert box
/gate/RF116/setMaterial Aluminium
/gate/RF116/geometry/setXLength 0.001000 cm
/gate/RF116/geometry/setYLength 20 cm
/gate/RF116/geometry/setZLength 2.739000 cm
/gate/RF116/placement/setTranslation -9.821500 0 -1.630500 cm
/gate/RF116/vis/forceSolid
/gate/RF116/vis/setColor yellow
/gate/RF116/repeaters/insert linear
/gate/RF116/linear/setRepeatNumber 40
/gate/RF116/linear/setRepeatVector 5 0 0 mm
/gate/RF116/linear/autoCenter false
/gate/RF_box/daughters/name RF117
/gate/RF_box/daughters/insert box
/gate/RF117/setMaterial Aluminium
/gate/RF117/geometry/setXLength 0.001000 cm
/gate/RF117/geometry/setYLength 20 cm
/gate/RF117/geometry/setZLength 2.761000 cm
/gate/RF117/placement/setTranslation -9.820500 0 -1.619500 cm
/gate/RF117/vis/forceSolid
/gate/RF117/vis/setColor yellow
/gate/RF117/repeaters/insert linear
/gate/RF117/linear/setRepeatNumber 40
/gate/RF117/linear/setRepeatVector 5 0 0 mm
/gate/RF117/linear/autoCenter false
/gate/RF_box/daughters/name RF118
/gate/RF_box/daughters/insert box
/gate/RF118/setMaterial Aluminium
/gate/RF118/geometry/setXLength 0.001000 cm
/gate/RF118/geometry/setYLength 20 cm
/gate/RF118/geometry/setZLength 2.784000 cm
/gate/RF118/placement/setTranslation -9.819500 0 -1.608000 cm
/gate/RF118/vis/forceSolid
/gate/RF118/vis/setColor yellow
/gate/RF118/repeaters/insert linear
/gate/RF118/linear/setRepeatNumber 40
/gate/RF118/linear/setRepeatVector 5 0 0 mm
/gate/RF118/linear/autoCenter false
/gate/RF_box/daughters/name RF120
/gate/RF_box/daughters/insert box
/gate/RF120/setMaterial Aluminium
/gate/RF120/geometry/setXLength 0.001000 cm
/gate/RF120/geometry/setYLength 20 cm
/gate/RF120/geometry/setZLength 2.829000 cm
/gate/RF120/placement/setTranslation -9.818500 0 -1.585500 cm
/gate/RF120/vis/forceSolid
/gate/RF120/vis/setColor yellow
/gate/RF120/repeaters/insert linear
/gate/RF120/linear/setRepeatNumber 40
/gate/RF120/linear/setRepeatVector 5 0 0 mm
/gate/RF120/linear/autoCenter false
/gate/RF_box/daughters/name RF121
/gate/RF_box/daughters/insert box
/gate/RF121/setMaterial Aluminium
/gate/RF121/geometry/setXLength 0.001000 cm
/gate/RF121/geometry/setYLength 20 cm
/gate/RF121/geometry/setZLength 2.852000 cm
/gate/RF121/placement/setTranslation -9.817500 0 -1.574000 cm
/gate/RF121/vis/forceSolid
/gate/RF121/vis/setColor yellow
/gate/RF121/repeaters/insert linear
/gate/RF121/linear/setRepeatNumber 40
/gate/RF121/linear/setRepeatVector 5 0 0 mm
/gate/RF121/linear/autoCenter false
/gate/RF_box/daughters/name RF122
/gate/RF_box/daughters/insert box
/gate/RF122/setMaterial Aluminium
/gate/RF122/geometry/setXLength 0.001000 cm
/gate/RF122/geometry/setYLength 20 cm
/gate/RF122/geometry/setZLength 2.875000 cm
/gate/RF122/placement/setTranslation -9.816500 0 -1.562500 cm
/gate/RF122/vis/forceSolid
/gate/RF122/vis/setColor yellow
/gate/RF122/repeaters/insert linear
/gate/RF122/linear/setRepeatNumber 40
/gate/RF122/linear/setRepeatVector 5 0 0 mm
/gate/RF122/linear/autoCenter false
/gate/RF_box/daughters/name RF123
/gate/RF_box/daughters/insert box
/gate/RF123/setMaterial Aluminium
/gate/RF123/geometry/setXLength 0.001000 cm
/gate/RF123/geometry/setYLength 20 cm
/gate/RF123/geometry/setZLength 2.897000 cm
/gate/RF123/placement/setTranslation -9.815500 0 -1.551500 cm
/gate/RF123/vis/forceSolid
/gate/RF123/vis/setColor yellow
/gate/RF123/repeaters/insert linear
/gate/RF123/linear/setRepeatNumber 40
/gate/RF123/linear/setRepeatVector 5 0 0 mm
/gate/RF123/linear/autoCenter false
/gate/RF_box/daughters/name RF124
/gate/RF_box/daughters/insert box
/gate/RF124/setMaterial Aluminium
/gate/RF124/geometry/setXLength 0.001000 cm
/gate/RF124/geometry/setYLength 20 cm
/gate/RF124/geometry/setZLength 2.920000 cm
/gate/RF124/placement/setTranslation -9.814500 0 -1.540000 cm
/gate/RF124/vis/forceSolid
/gate/RF124/vis/setColor yellow
/gate/RF124/repeaters/insert linear
/gate/RF124/linear/setRepeatNumber 40
/gate/RF124/linear/setRepeatVector 5 0 0 mm
/gate/RF124/linear/autoCenter false
/gate/RF_box/daughters/name RF125
/gate/RF_box/daughters/insert box
/gate/RF125/setMaterial Aluminium
/gate/RF125/geometry/setXLength 0.001000 cm
/gate/RF125/geometry/setYLength 20 cm
/gate/RF125/geometry/setZLength 2.943000 cm
/gate/RF125/placement/setTranslation -9.813500 0 -1.528500 cm
/gate/RF125/vis/forceSolid
/gate/RF125/vis/setColor yellow
/gate/RF125/repeaters/insert linear
/gate/RF125/linear/setRepeatNumber 40
/gate/RF125/linear/setRepeatVector 5 0 0 mm
/gate/RF125/linear/autoCenter false
/gate/RF_box/daughters/name RF126
/gate/RF_box/daughters/insert box
/gate/RF126/setMaterial Aluminium
/gate/RF126/geometry/setXLength 0.001000 cm
/gate/RF126/geometry/setYLength 20 cm
/gate/RF126/geometry/setZLength 2.965000 cm
/gate/RF126/placement/setTranslation -9.812500 0 -1.517500 cm
/gate/RF126/vis/forceSolid
/gate/RF126/vis/setColor yellow
/gate/RF126/repeaters/insert linear
/gate/RF126/linear/setRepeatNumber 40
/gate/RF126/linear/setRepeatVector 5 0 0 mm
/gate/RF126/linear/autoCenter false
/gate/RF_box/daughters/name RF127
/gate/RF_box/daughters/insert box
/gate/RF127/setMaterial Aluminium
/gate/RF127/geometry/setXLength 0.001000 cm
/gate/RF127/geometry/setYLength 20 cm
/gate/RF127/geometry/setZLength 2.988000 cm
/gate/RF127/placement/setTranslation -9.811500 0 -1.506000 cm
/gate/RF127/vis/forceSolid
/gate/RF127/vis/setColor yellow
/gate/RF127/repeaters/insert linear
/gate/RF127/linear/setRepeatNumber 40
/gate/RF127/linear/setRepeatVector 5 0 0 mm
/gate/RF127/linear/autoCenter false
/gate/RF_box/daughters/name RF129
/gate/RF_box/daughters/insert box
/gate/RF129/setMaterial Aluminium
/gate/RF129/geometry/setXLength 0.001000 cm
/gate/RF129/geometry/setYLength 20 cm
/gate/RF129/geometry/setZLength 3.033000 cm
/gate/RF129/placement/setTranslation -9.810500 0 -1.483500 cm
/gate/RF129/vis/forceSolid
/gate/RF129/vis/setColor yellow
/gate/RF129/repeaters/insert linear
/gate/RF129/linear/setRepeatNumber 40
/gate/RF129/linear/setRepeatVector 5 0 0 mm
/gate/RF129/linear/autoCenter false
/gate/RF_box/daughters/name RF130
/gate/RF_box/daughters/insert box
/gate/RF130/setMaterial Aluminium
/gate/RF130/geometry/setXLength 0.001000 cm
/gate/RF130/geometry/setYLength 20 cm
/gate/RF130/geometry/setZLength 3.056000 cm
/gate/RF130/placement/setTranslation -9.809500 0 -1.472000 cm
/gate/RF130/vis/forceSolid
/gate/RF130/vis/setColor yellow
/gate/RF130/repeaters/insert linear
/gate/RF130/linear/setRepeatNumber 40
/gate/RF130/linear/setRepeatVector 5 0 0 mm
/gate/RF130/linear/autoCenter false
/gate/RF_box/daughters/name RF131
/gate/RF_box/daughters/insert box
/gate/RF131/setMaterial Aluminium
/gate/RF131/geometry/setXLength 0.001000 cm
/gate/RF131/geometry/setYLength 20 cm
/gate/RF131/geometry/setZLength 3.078000 cm
/gate/RF131/placement/setTranslation -9.808500 0 -1.461000 cm
/gate/RF131/vis/forceSolid
/gate/RF131/vis/setColor yellow
/gate/RF131/repeaters/insert linear
/gate/RF131/linear/setRepeatNumber 40
/gate/RF131/linear/setRepeatVector 5 0 0 mm
/gate/RF131/linear/autoCenter false
/gate/RF_box/daughters/name RF132
/gate/RF_box/daughters/insert box
/gate/RF132/setMaterial Aluminium
/gate/RF132/geometry/setXLength 0.001000 cm
/gate/RF132/geometry/setYLength 20 cm
/gate/RF132/geometry/setZLength 3.101000 cm
/gate/RF132/placement/setTranslation -9.807500 0 -1.449500 cm
/gate/RF132/vis/forceSolid
/gate/RF132/vis/setColor yellow
/gate/RF132/repeaters/insert linear
/gate/RF132/linear/setRepeatNumber 40
/gate/RF132/linear/setRepeatVector 5 0 0 mm
/gate/RF132/linear/autoCenter false
/gate/RF_box/daughters/name RF133
/gate/RF_box/daughters/insert box
/gate/RF133/setMaterial Aluminium
/gate/RF133/geometry/setXLength 0.001000 cm
/gate/RF133/geometry/setYLength 20 cm
/gate/RF133/geometry/setZLength 3.124000 cm
/gate/RF133/placement/setTranslation -9.806500 0 -1.438000 cm
/gate/RF133/vis/forceSolid
/gate/RF133/vis/setColor yellow
/gate/RF133/repeaters/insert linear
/gate/RF133/linear/setRepeatNumber 40
/gate/RF133/linear/setRepeatVector 5 0 0 mm
/gate/RF133/linear/autoCenter false
/gate/RF_box/daughters/name RF134
/gate/RF_box/daughters/insert box
/gate/RF134/setMaterial Aluminium
/gate/RF134/geometry/setXLength 0.001000 cm
/gate/RF134/geometry/setYLength 20 cm
/gate/RF134/geometry/setZLength 3.146000 cm
/gate/RF134/placement/setTranslation -9.805500 0 -1.427000 cm
/gate/RF134/vis/forceSolid
/gate/RF134/vis/setColor yellow
/gate/RF134/repeaters/insert linear
/gate/RF134/linear/setRepeatNumber 40
/gate/RF134/linear/setRepeatVector 5 0 0 mm
/gate/RF134/linear/autoCenter false
/gate/RF_box/daughters/name RF135
/gate/RF_box/daughters/insert box
/gate/RF135/setMaterial Aluminium
/gate/RF135/geometry/setXLength 0.001000 cm
/gate/RF135/geometry/setYLength 20 cm
/gate/RF135/geometry/setZLength 3.169000 cm
/gate/RF135/placement/setTranslation -9.804500 0 -1.415500 cm
/gate/RF135/vis/forceSolid
/gate/RF135/vis/setColor yellow
/gate/RF135/repeaters/insert linear
/gate/RF135/linear/setRepeatNumber 40
/gate/RF135/linear/setRepeatVector 5 0 0 mm
/gate/RF135/linear/autoCenter false
/gate/RF_box/daughters/name RF137
/gate/RF_box/daughters/insert box
/gate/RF137/setMaterial Aluminium
/gate/RF137/geometry/setXLength 0.001000 cm
/gate/RF137/geometry/setYLength 20 cm
/gate/RF137/geometry/setZLength 3.214000 cm
/gate/RF137/placement/setTranslation -9.803500 0 -1.393000 cm
/gate/RF137/vis/forceSolid
/gate/RF137/vis/setColor yellow
/gate/RF137/repeaters/insert linear
/gate/RF137/linear/setRepeatNumber 40
/gate/RF137/linear/setRepeatVector 5 0 0 mm
/gate/RF137/linear/autoCenter false
/gate/RF_box/daughters/name RF138
/gate/RF_box/daughters/insert box
/gate/RF138/setMaterial Aluminium
/gate/RF138/geometry/setXLength 0.001000 cm
/gate/RF138/geometry/setYLength 20 cm
/gate/RF138/geometry/setZLength 3.237000 cm
/gate/RF138/placement/setTranslation -9.802500 0 -1.381500 cm
/gate/RF138/vis/forceSolid
/gate/RF138/vis/setColor yellow
/gate/RF138/repeaters/insert linear
/gate/RF138/linear/setRepeatNumber 40
/gate/RF138/linear/setRepeatVector 5 0 0 mm
/gate/RF138/linear/autoCenter false
/gate/RF_box/daughters/name RF139
/gate/RF_box/daughters/insert box
/gate/RF139/setMaterial Aluminium
/gate/RF139/geometry/setXLength 0.001000 cm
/gate/RF139/geometry/setYLength 20 cm
/gate/RF139/geometry/setZLength 3.259000 cm
/gate/RF139/placement/setTranslation -9.801500 0 -1.370500 cm
/gate/RF139/vis/forceSolid
/gate/RF139/vis/setColor yellow
/gate/RF139/repeaters/insert linear
/gate/RF139/linear/setRepeatNumber 40
/gate/RF139/linear/setRepeatVector 5 0 0 mm
/gate/RF139/linear/autoCenter false
/gate/RF_box/daughters/name RF140
/gate/RF_box/daughters/insert box
/gate/RF140/setMaterial Aluminium
/gate/RF140/geometry/setXLength 0.001000 cm
/gate/RF140/geometry/setYLength 20 cm
/gate/RF140/geometry/setZLength 3.282000 cm
/gate/RF140/placement/setTranslation -9.800500 0 -1.359000 cm
/gate/RF140/vis/forceSolid
/gate/RF140/vis/setColor yellow
/gate/RF140/repeaters/insert linear
/gate/RF140/linear/setRepeatNumber 40
/gate/RF140/linear/setRepeatVector 5 0 0 mm
/gate/RF140/linear/autoCenter false
/gate/RF_box/daughters/name RF141
/gate/RF_box/daughters/insert box
/gate/RF141/setMaterial Aluminium
/gate/RF141/geometry/setXLength 0.001000 cm
/gate/RF141/geometry/setYLength 20 cm
/gate/RF141/geometry/setZLength 3.305000 cm
/gate/RF141/placement/setTranslation -9.799500 0 -1.347500 cm
/gate/RF141/vis/forceSolid
/gate/RF141/vis/setColor yellow
/gate/RF141/repeaters/insert linear
/gate/RF141/linear/setRepeatNumber 40
/gate/RF141/linear/setRepeatVector 5 0 0 mm
/gate/RF141/linear/autoCenter false
/gate/RF_box/daughters/name RF142
/gate/RF_box/daughters/insert box
/gate/RF142/setMaterial Aluminium
/gate/RF142/geometry/setXLength 0.001000 cm
/gate/RF142/geometry/setYLength 20 cm
/gate/RF142/geometry/setZLength 3.327000 cm
/gate/RF142/placement/setTranslation -9.798500 0 -1.336500 cm
/gate/RF142/vis/forceSolid
/gate/RF142/vis/setColor yellow
/gate/RF142/repeaters/insert linear
/gate/RF142/linear/setRepeatNumber 40
/gate/RF142/linear/setRepeatVector 5 0 0 mm
/gate/RF142/linear/autoCenter false
/gate/RF_box/daughters/name RF144
/gate/RF_box/daughters/insert box
/gate/RF144/setMaterial Aluminium
/gate/RF144/geometry/setXLength 0.001000 cm
/gate/RF144/geometry/setYLength 20 cm
/gate/RF144/geometry/setZLength 3.373000 cm
/gate/RF144/placement/setTranslation -9.797500 0 -1.313500 cm
/gate/RF144/vis/forceSolid
/gate/RF144/vis/setColor yellow
/gate/RF144/repeaters/insert linear
/gate/RF144/linear/setRepeatNumber 40
/gate/RF144/linear/setRepeatVector 5 0 0 mm
/gate/RF144/linear/autoCenter false
/gate/RF_box/daughters/name RF145
/gate/RF_box/daughters/insert box
/gate/RF145/setMaterial Aluminium
/gate/RF145/geometry/setXLength 0.001000 cm
/gate/RF145/geometry/setYLength 20 cm
/gate/RF145/geometry/setZLength 3.395000 cm
/gate/RF145/placement/setTranslation -9.796500 0 -1.302500 cm
/gate/RF145/vis/forceSolid
/gate/RF145/vis/setColor yellow
/gate/RF145/repeaters/insert linear
/gate/RF145/linear/setRepeatNumber 40
/gate/RF145/linear/setRepeatVector 5 0 0 mm
/gate/RF145/linear/autoCenter false
/gate/RF_box/daughters/name RF146
/gate/RF_box/daughters/insert box
/gate/RF146/setMaterial Aluminium
/gate/RF146/geometry/setXLength 0.001000 cm
/gate/RF146/geometry/setYLength 20 cm
/gate/RF146/geometry/setZLength 3.418000 cm
/gate/RF146/placement/setTranslation -9.795500 0 -1.291000 cm
/gate/RF146/vis/forceSolid
/gate/RF146/vis/setColor yellow
/gate/RF146/repeaters/insert linear
/gate/RF146/linear/setRepeatNumber 40
/gate/RF146/linear/setRepeatVector 5 0 0 mm
/gate/RF146/linear/autoCenter false
/gate/RF_box/daughters/name RF147
/gate/RF_box/daughters/insert box
/gate/RF147/setMaterial Aluminium
/gate/RF147/geometry/setXLength 0.001000 cm
/gate/RF147/geometry/setYLength 20 cm
/gate/RF147/geometry/setZLength 3.440000 cm
/gate/RF147/placement/setTranslation -9.794500 0 -1.280000 cm
/gate/RF147/vis/forceSolid
/gate/RF147/vis/setColor yellow
/gate/RF147/repeaters/insert linear
/gate/RF147/linear/setRepeatNumber 40
/gate/RF147/linear/setRepeatVector 5 0 0 mm
/gate/RF147/linear/autoCenter false
/gate/RF_box/daughters/name RF148
/gate/RF_box/daughters/insert box
/gate/RF148/setMaterial Aluminium
/gate/RF148/geometry/setXLength 0.001000 cm
/gate/RF148/geometry/setYLength 20 cm
/gate/RF148/geometry/setZLength 3.463000 cm
/gate/RF148/placement/setTranslation -9.793500 0 -1.268500 cm
/gate/RF148/vis/forceSolid
/gate/RF148/vis/setColor yellow
/gate/RF148/repeaters/insert linear
/gate/RF148/linear/setRepeatNumber 40
/gate/RF148/linear/setRepeatVector 5 0 0 mm
/gate/RF148/linear/autoCenter false
/gate/RF_box/daughters/name RF150
/gate/RF_box/daughters/insert box
/gate/RF150/setMaterial Aluminium
/gate/RF150/geometry/setXLength 0.001000 cm
/gate/RF150/geometry/setYLength 20 cm
/gate/RF150/geometry/setZLength 3.508000 cm
/gate/RF150/placement/setTranslation -9.792500 0 -1.246000 cm
/gate/RF150/vis/forceSolid
/gate/RF150/vis/setColor yellow
/gate/RF150/repeaters/insert linear
/gate/RF150/linear/setRepeatNumber 40
/gate/RF150/linear/setRepeatVector 5 0 0 mm
/gate/RF150/linear/autoCenter false
/gate/RF_box/daughters/name RF151
/gate/RF_box/daughters/insert box
/gate/RF151/setMaterial Aluminium
/gate/RF151/geometry/setXLength 0.001000 cm
/gate/RF151/geometry/setYLength 20 cm
/gate/RF151/geometry/setZLength 3.531000 cm
/gate/RF151/placement/setTranslation -9.791500 0 -1.234500 cm
/gate/RF151/vis/forceSolid
/gate/RF151/vis/setColor yellow
/gate/RF151/repeaters/insert linear
/gate/RF151/linear/setRepeatNumber 40
/gate/RF151/linear/setRepeatVector 5 0 0 mm
/gate/RF151/linear/autoCenter false
/gate/RF_box/daughters/name RF152
/gate/RF_box/daughters/insert box
/gate/RF152/setMaterial Aluminium
/gate/RF152/geometry/setXLength 0.001000 cm
/gate/RF152/geometry/setYLength 20 cm
/gate/RF152/geometry/setZLength 3.554000 cm
/gate/RF152/placement/setTranslation -9.790500 0 -1.223000 cm
/gate/RF152/vis/forceSolid
/gate/RF152/vis/setColor yellow
/gate/RF152/repeaters/insert linear
/gate/RF152/linear/setRepeatNumber 40
/gate/RF152/linear/setRepeatVector 5 0 0 mm
/gate/RF152/linear/autoCenter false
/gate/RF_box/daughters/name RF153
/gate/RF_box/daughters/insert box
/gate/RF153/setMaterial Aluminium
/gate/RF153/geometry/setXLength 0.001000 cm
/gate/RF153/geometry/setYLength 20 cm
/gate/RF153/geometry/setZLength 3.576000 cm
/gate/RF153/placement/setTranslation -9.789500 0 -1.212000 cm
/gate/RF153/vis/forceSolid
/gate/RF153/vis/setColor yellow
/gate/RF153/repeaters/insert linear
/gate/RF153/linear/setRepeatNumber 40
/gate/RF153/linear/setRepeatVector 5 0 0 mm
/gate/RF153/linear/autoCenter false
/gate/RF_box/daughters/name RF154
/gate/RF_box/daughters/insert box
/gate/RF154/setMaterial Aluminium
/gate/RF154/geometry/setXLength 0.001000 cm
/gate/RF154/geometry/setYLength 20 cm
/gate/RF154/geometry/setZLength 3.599000 cm
/gate/RF154/placement/setTranslation -9.788500 0 -1.200500 cm
/gate/RF154/vis/forceSolid
/gate/RF154/vis/setColor yellow
/gate/RF154/repeaters/insert linear
/gate/RF154/linear/setRepeatNumber 40
/gate/RF154/linear/setRepeatVector 5 0 0 mm
/gate/RF154/linear/autoCenter false
/gate/RF_box/daughters/name RF156
/gate/RF_box/daughters/insert box
/gate/RF156/setMaterial Aluminium
/gate/RF156/geometry/setXLength 0.001000 cm
/gate/RF156/geometry/setYLength 20 cm
/gate/RF156/geometry/setZLength 3.644000 cm
/gate/RF156/placement/setTranslation -9.787500 0 -1.178000 cm
/gate/RF156/vis/forceSolid
/gate/RF156/vis/setColor yellow
/gate/RF156/repeaters/insert linear
/gate/RF156/linear/setRepeatNumber 40
/gate/RF156/linear/setRepeatVector 5 0 0 mm
/gate/RF156/linear/autoCenter false
/gate/RF_box/daughters/name RF157
/gate/RF_box/daughters/insert box
/gate/RF157/setMaterial Aluminium
/gate/RF157/geometry/setXLength 0.001000 cm
/gate/RF157/geometry/setYLength 20 cm
/gate/RF157/geometry/setZLength 3.667000 cm
/gate/RF157/placement/setTranslation -9.786500 0 -1.166500 cm
/gate/RF157/vis/forceSolid
/gate/RF157/vis/setColor yellow
/gate/RF157/repeaters/insert linear
/gate/RF157/linear/setRepeatNumber 40
/gate/RF157/linear/setRepeatVector 5 0 0 mm
/gate/RF157/linear/autoCenter false
/gate/RF_box/daughters/name RF158
/gate/RF_box/daughters/insert box
/gate/RF158/setMaterial Aluminium
/gate/RF158/geometry/setXLength 0.001000 cm
/gate/RF158/geometry/setYLength 20 cm
/gate/RF158/geometry/setZLength 3.689000 cm
/gate/RF158/placement/setTranslation -9.785500 0 -1.155500 cm
/gate/RF158/vis/forceSolid
/gate/RF158/vis/setColor yellow
/gate/RF158/repeaters/insert linear
/gate/RF158/linear/setRepeatNumber 40
/gate/RF158/linear/setRepeatVector 5 0 0 mm
/gate/RF158/linear/autoCenter false
/gate/RF_box/daughters/name RF159
/gate/RF_box/daughters/insert box
/gate/RF159/setMaterial Aluminium
/gate/RF159/geometry/setXLength 0.001000 cm
/gate/RF159/geometry/setYLength 20 cm
/gate/RF159/geometry/setZLength 3.712000 cm
/gate/RF159/placement/setTranslation -9.784500 0 -1.144000 cm
/gate/RF159/vis/forceSolid
/gate/RF159/vis/setColor yellow
/gate/RF159/repeaters/insert linear
/gate/RF159/linear/setRepeatNumber 40
/gate/RF159/linear/setRepeatVector 5 0 0 mm
/gate/RF159/linear/autoCenter false
/gate/RF_box/daughters/name RF161
/gate/RF_box/daughters/insert box
/gate/RF161/setMaterial Aluminium
/gate/RF161/geometry/setXLength 0.001000 cm
/gate/RF161/geometry/setYLength 20 cm
/gate/RF161/geometry/setZLength 3.757000 cm
/gate/RF161/placement/setTranslation -9.783500 0 -1.121500 cm
/gate/RF161/vis/forceSolid
/gate/RF161/vis/setColor yellow
/gate/RF161/repeaters/insert linear
/gate/RF161/linear/setRepeatNumber 40
/gate/RF161/linear/setRepeatVector 5 0 0 mm
/gate/RF161/linear/autoCenter false
/gate/RF_box/daughters/name RF162
/gate/RF_box/daughters/insert box
/gate/RF162/setMaterial Aluminium
/gate/RF162/geometry/setXLength 0.001000 cm
/gate/RF162/geometry/setYLength 20 cm
/gate/RF162/geometry/setZLength 3.780000 cm
/gate/RF162/placement/setTranslation -9.782500 0 -1.110000 cm
/gate/RF162/vis/forceSolid
/gate/RF162/vis/setColor yellow
/gate/RF162/repeaters/insert linear
/gate/RF162/linear/setRepeatNumber 40
/gate/RF162/linear/setRepeatVector 5 0 0 mm
/gate/RF162/linear/autoCenter false
/gate/RF_box/daughters/name RF163
/gate/RF_box/daughters/insert box
/gate/RF163/setMaterial Aluminium
/gate/RF163/geometry/setXLength 0.001000 cm
/gate/RF163/geometry/setYLength 20 cm
/gate/RF163/geometry/setZLength 3.803000 cm
/gate/RF163/placement/setTranslation -9.781500 0 -1.098500 cm
/gate/RF163/vis/forceSolid
/gate/RF163/vis/setColor yellow
/gate/RF163/repeaters/insert linear
/gate/RF163/linear/setRepeatNumber 40
/gate/RF163/linear/setRepeatVector 5 0 0 mm
/gate/RF163/linear/autoCenter false
/gate/RF_box/daughters/name RF164
/gate/RF_box/daughters/insert box
/gate/RF164/setMaterial Aluminium
/gate/RF164/geometry/setXLength 0.001000 cm
/gate/RF164/geometry/setYLength 20 cm
/gate/RF164/geometry/setZLength 3.825000 cm
/gate/RF164/placement/setTranslation -9.780500 0 -1.087500 cm
/gate/RF164/vis/forceSolid
/gate/RF164/vis/setColor yellow
/gate/RF164/repeaters/insert linear
/gate/RF164/linear/setRepeatNumber 40
/gate/RF164/linear/setRepeatVector 5 0 0 mm
/gate/RF164/linear/autoCenter false
/gate/RF_box/daughters/name RF165
/gate/RF_box/daughters/insert box
/gate/RF165/setMaterial Aluminium
/gate/RF165/geometry/setXLength 0.001000 cm
/gate/RF165/geometry/setYLength 20 cm
/gate/RF165/geometry/setZLength 3.848000 cm
/gate/RF165/placement/setTranslation -9.779500 0 -1.076000 cm
/gate/RF165/vis/forceSolid
/gate/RF165/vis/setColor yellow
/gate/RF165/repeaters/insert linear
/gate/RF165/linear/setRepeatNumber 40
/gate/RF165/linear/setRepeatVector 5 0 0 mm
/gate/RF165/linear/autoCenter false
/gate/RF_box/daughters/name RF167
/gate/RF_box/daughters/insert box
/gate/RF167/setMaterial Aluminium
/gate/RF167/geometry/setXLength 0.001000 cm
/gate/RF167/geometry/setYLength 20 cm
/gate/RF167/geometry/setZLength 3.893000 cm
/gate/RF167/placement/setTranslation -9.778500 0 -1.053500 cm
/gate/RF167/vis/forceSolid
/gate/RF167/vis/setColor yellow
/gate/RF167/repeaters/insert linear
/gate/RF167/linear/setRepeatNumber 40
/gate/RF167/linear/setRepeatVector 5 0 0 mm
/gate/RF167/linear/autoCenter false
/gate/RF_box/daughters/name RF168
/gate/RF_box/daughters/insert box
/gate/RF168/setMaterial Aluminium
/gate/RF168/geometry/setXLength 0.001000 cm
/gate/RF168/geometry/setYLength 20 cm
/gate/RF168/geometry/setZLength 3.916000 cm
/gate/RF168/placement/setTranslation -9.777500 0 -1.042000 cm
/gate/RF168/vis/forceSolid
/gate/RF168/vis/setColor yellow
/gate/RF168/repeaters/insert linear
/gate/RF168/linear/setRepeatNumber 40
/gate/RF168/linear/setRepeatVector 5 0 0 mm
/gate/RF168/linear/autoCenter false
/gate/RF_box/daughters/name RF169
/gate/RF_box/daughters/insert box
/gate/RF169/setMaterial Aluminium
/gate/RF169/geometry/setXLength 0.001000 cm
/gate/RF169/geometry/setYLength 20 cm
/gate/RF169/geometry/setZLength 3.938000 cm
/gate/RF169/placement/setTranslation -9.776500 0 -1.031000 cm
/gate/RF169/vis/forceSolid
/gate/RF169/vis/setColor yellow
/gate/RF169/repeaters/insert linear
/gate/RF169/linear/setRepeatNumber 40
/gate/RF169/linear/setRepeatVector 5 0 0 mm
/gate/RF169/linear/autoCenter false
/gate/RF_box/daughters/name RF170
/gate/RF_box/daughters/insert box
/gate/RF170/setMaterial Aluminium
/gate/RF170/geometry/setXLength 0.001000 cm
/gate/RF170/geometry/setYLength 20 cm
/gate/RF170/geometry/setZLength 3.961000 cm
/gate/RF170/placement/setTranslation -9.775500 0 -1.019500 cm
/gate/RF170/vis/forceSolid
/gate/RF170/vis/setColor yellow
/gate/RF170/repeaters/insert linear
/gate/RF170/linear/setRepeatNumber 40
/gate/RF170/linear/setRepeatVector 5 0 0 mm
/gate/RF170/linear/autoCenter false
/gate/RF_box/daughters/name RF172
/gate/RF_box/daughters/insert box
/gate/RF172/setMaterial Aluminium
/gate/RF172/geometry/setXLength 0.001000 cm
/gate/RF172/geometry/setYLength 20 cm
/gate/RF172/geometry/setZLength 4.006000 cm
/gate/RF172/placement/setTranslation -9.774500 0 -0.997000 cm
/gate/RF172/vis/forceSolid
/gate/RF172/vis/setColor yellow
/gate/RF172/repeaters/insert linear
/gate/RF172/linear/setRepeatNumber 40
/gate/RF172/linear/setRepeatVector 5 0 0 mm
/gate/RF172/linear/autoCenter false
/gate/RF_box/daughters/name RF173
/gate/RF_box/daughters/insert box
/gate/RF173/setMaterial Aluminium
/gate/RF173/geometry/setXLength 0.001000 cm
/gate/RF173/geometry/setYLength 20 cm
/gate/RF173/geometry/setZLength 4.029000 cm
/gate/RF173/placement/setTranslation -9.773500 0 -0.985500 cm
/gate/RF173/vis/forceSolid
/gate/RF173/vis/setColor yellow
/gate/RF173/repeaters/insert linear
/gate/RF173/linear/setRepeatNumber 40
/gate/RF173/linear/setRepeatVector 5 0 0 mm
/gate/RF173/linear/autoCenter false
/gate/RF_box/daughters/name RF174
/gate/RF_box/daughters/insert box
/gate/RF174/setMaterial Aluminium
/gate/RF174/geometry/setXLength 0.001000 cm
/gate/RF174/geometry/setYLength 20 cm
/gate/RF174/geometry/setZLength 4.052000 cm
/gate/RF174/placement/setTranslation -9.772500 0 -0.974000 cm
/gate/RF174/vis/forceSolid
/gate/RF174/vis/setColor yellow
/gate/RF174/repeaters/insert linear
/gate/RF174/linear/setRepeatNumber 40
/gate/RF174/linear/setRepeatVector 5 0 0 mm
/gate/RF174/linear/autoCenter false
/gate/RF_box/daughters/name RF175
/gate/RF_box/daughters/insert box
/gate/RF175/setMaterial Aluminium
/gate/RF175/geometry/setXLength 0.001000 cm
/gate/RF175/geometry/setYLength 20 cm
/gate/RF175/geometry/setZLength 4.074000 cm
/gate/RF175/placement/setTranslation -9.771500 0 -0.963000 cm
/gate/RF175/vis/forceSolid
/gate/RF175/vis/setColor yellow
/gate/RF175/repeaters/insert linear
/gate/RF175/linear/setRepeatNumber 40
/gate/RF175/linear/setRepeatVector 5 0 0 mm
/gate/RF175/linear/autoCenter false
/gate/RF_box/daughters/name RF177
/gate/RF_box/daughters/insert box
/gate/RF177/setMaterial Aluminium
/gate/RF177/geometry/setXLength 0.001000 cm
/gate/RF177/geometry/setYLength 20 cm
/gate/RF177/geometry/setZLength 4.120000 cm
/gate/RF177/placement/setTranslation -9.770500 0 -0.940000 cm
/gate/RF177/vis/forceSolid
/gate/RF177/vis/setColor yellow
/gate/RF177/repeaters/insert linear
/gate/RF177/linear/setRepeatNumber 40
/gate/RF177/linear/setRepeatVector 5 0 0 mm
/gate/RF177/linear/autoCenter false
/gate/RF_box/daughters/name RF178
/gate/RF_box/daughters/insert box
/gate/RF178/setMaterial Aluminium
/gate/RF178/geometry/setXLength 0.001000 cm
/gate/RF178/geometry/setYLength 20 cm
/gate/RF178/geometry/setZLength 4.142000 cm
/gate/RF178/placement/setTranslation -9.769500 0 -0.929000 cm
/gate/RF178/vis/forceSolid
/gate/RF178/vis/setColor yellow
/gate/RF178/repeaters/insert linear
/gate/RF178/linear/setRepeatNumber 40
/gate/RF178/linear/setRepeatVector 5 0 0 mm
/gate/RF178/linear/autoCenter false
/gate/RF_box/daughters/name RF179
/gate/RF_box/daughters/insert box
/gate/RF179/setMaterial Aluminium
/gate/RF179/geometry/setXLength 0.001000 cm
/gate/RF179/geometry/setYLength 20 cm
/gate/RF179/geometry/setZLength 4.165000 cm
/gate/RF179/placement/setTranslation -9.768500 0 -0.917500 cm
/gate/RF179/vis/forceSolid
/gate/RF179/vis/setColor yellow
/gate/RF179/repeaters/insert linear
/gate/RF179/linear/setRepeatNumber 40
/gate/RF179/linear/setRepeatVector 5 0 0 mm
/gate/RF179/linear/autoCenter false
/gate/RF_box/daughters/name RF181
/gate/RF_box/daughters/insert box
/gate/RF181/setMaterial Aluminium
/gate/RF181/geometry/setXLength 0.001000 cm
/gate/RF181/geometry/setYLength 20 cm
/gate/RF181/geometry/setZLength 4.210000 cm
/gate/RF181/placement/setTranslation -9.767500 0 -0.895000 cm
/gate/RF181/vis/forceSolid
/gate/RF181/vis/setColor yellow
/gate/RF181/repeaters/insert linear
/gate/RF181/linear/setRepeatNumber 40
/gate/RF181/linear/setRepeatVector 5 0 0 mm
/gate/RF181/linear/autoCenter false
/gate/RF_box/daughters/name RF182
/gate/RF_box/daughters/insert box
/gate/RF182/setMaterial Aluminium
/gate/RF182/geometry/setXLength 0.001000 cm
/gate/RF182/geometry/setYLength 20 cm
/gate/RF182/geometry/setZLength 4.233000 cm
/gate/RF182/placement/setTranslation -9.766500 0 -0.883500 cm
/gate/RF182/vis/forceSolid
/gate/RF182/vis/setColor yellow
/gate/RF182/repeaters/insert linear
/gate/RF182/linear/setRepeatNumber 40
/gate/RF182/linear/setRepeatVector 5 0 0 mm
/gate/RF182/linear/autoCenter false
/gate/RF_box/daughters/name RF183
/gate/RF_box/daughters/insert box
/gate/RF183/setMaterial Aluminium
/gate/RF183/geometry/setXLength 0.001000 cm
/gate/RF183/geometry/setYLength 20 cm
/gate/RF183/geometry/setZLength 4.255000 cm
/gate/RF183/placement/setTranslation -9.765500 0 -0.872500 cm
/gate/RF183/vis/forceSolid
/gate/RF183/vis/setColor yellow
/gate/RF183/repeaters/insert linear
/gate/RF183/linear/setRepeatNumber 40
/gate/RF183/linear/setRepeatVector 5 0 0 mm
/gate/RF183/linear/autoCenter false
/gate/RF_box/daughters/name RF184
/gate/RF_box/daughters/insert box
/gate/RF184/setMaterial Aluminium
/gate/RF184/geometry/setXLength 0.001000 cm
/gate/RF184/geometry/setYLength 20 cm
/gate/RF184/geometry/setZLength 4.278000 cm
/gate/RF184/placement/setTranslation -9.764500 0 -0.861000 cm
/gate/RF184/vis/forceSolid
/gate/RF184/vis/setColor yellow
/gate/RF184/repeaters/insert linear
/gate/RF184/linear/setRepeatNumber 40
/gate/RF184/linear/setRepeatVector 5 0 0 mm
/gate/RF184/linear/autoCenter false
/gate/RF_box/daughters/name RF186
/gate/RF_box/daughters/insert box
/gate/RF186/setMaterial Aluminium
/gate/RF186/geometry/setXLength 0.001000 cm
/gate/RF186/geometry/setYLength 20 cm
/gate/RF186/geometry/setZLength 4.323000 cm
/gate/RF186/placement/setTranslation -9.763500 0 -0.838500 cm
/gate/RF186/vis/forceSolid
/gate/RF186/vis/setColor yellow
/gate/RF186/repeaters/insert linear
/gate/RF186/linear/setRepeatNumber 40
/gate/RF186/linear/setRepeatVector 5 0 0 mm
/gate/RF186/linear/autoCenter false
/gate/RF_box/daughters/name RF187
/gate/RF_box/daughters/insert box
/gate/RF187/setMaterial Aluminium
/gate/RF187/geometry/setXLength 0.001000 cm
/gate/RF187/geometry/setYLength 20 cm
/gate/RF187/geometry/setZLength 4.346000 cm
/gate/RF187/placement/setTranslation -9.762500 0 -0.827000 cm
/gate/RF187/vis/forceSolid
/gate/RF187/vis/setColor yellow
/gate/RF187/repeaters/insert linear
/gate/RF187/linear/setRepeatNumber 40
/gate/RF187/linear/setRepeatVector 5 0 0 mm
/gate/RF187/linear/autoCenter false
/gate/RF_box/daughters/name RF188
/gate/RF_box/daughters/insert box
/gate/RF188/setMaterial Aluminium
/gate/RF188/geometry/setXLength 0.001000 cm
/gate/RF188/geometry/setYLength 20 cm
/gate/RF188/geometry/setZLength 4.368000 cm
/gate/RF188/placement/setTranslation -9.761500 0 -0.816000 cm
/gate/RF188/vis/forceSolid
/gate/RF188/vis/setColor yellow
/gate/RF188/repeaters/insert linear
/gate/RF188/linear/setRepeatNumber 40
/gate/RF188/linear/setRepeatVector 5 0 0 mm
/gate/RF188/linear/autoCenter false
/gate/RF_box/daughters/name RF189
/gate/RF_box/daughters/insert box
/gate/RF189/setMaterial Aluminium
/gate/RF189/geometry/setXLength 0.001000 cm
/gate/RF189/geometry/setYLength 20 cm
/gate/RF189/geometry/setZLength 4.391000 cm
/gate/RF189/placement/setTranslation -9.760500 0 -0.804500 cm
/gate/RF189/vis/forceSolid
/gate/RF189/vis/setColor yellow
/gate/RF189/repeaters/insert linear
/gate/RF189/linear/setRepeatNumber 40
/gate/RF189/linear/setRepeatVector 5 0 0 mm
/gate/RF189/linear/autoCenter false
/gate/RF_box/daughters/name RF191
/gate/RF_box/daughters/insert box
/gate/RF191/setMaterial Aluminium
/gate/RF191/geometry/setXLength 0.001000 cm
/gate/RF191/geometry/setYLength 20 cm
/gate/RF191/geometry/setZLength 4.436000 cm
/gate/RF191/placement/setTranslation -9.759500 0 -0.782000 cm
/gate/RF191/vis/forceSolid
/gate/RF191/vis/setColor yellow
/gate/RF191/repeaters/insert linear
/gate/RF191/linear/setRepeatNumber 40
/gate/RF191/linear/setRepeatVector 5 0 0 mm
/gate/RF191/linear/autoCenter false
/gate/RF_box/daughters/name RF192
/gate/RF_box/daughters/insert box
/gate/RF192/setMaterial Aluminium
/gate/RF192/geometry/setXLength 0.001000 cm
/gate/RF192/geometry/setYLength 20 cm
/gate/RF192/geometry/setZLength 4.459000 cm
/gate/RF192/placement/setTranslation -9.758500 0 -0.770500 cm
/gate/RF192/vis/forceSolid
/gate/RF192/vis/setColor yellow
/gate/RF192/repeaters/insert linear
/gate/RF192/linear/setRepeatNumber 40
/gate/RF192/linear/setRepeatVector 5 0 0 mm
/gate/RF192/linear/autoCenter false
/gate/RF_box/daughters/name RF193
/gate/RF_box/daughters/insert box
/gate/RF193/setMaterial Aluminium
/gate/RF193/geometry/setXLength 0.001000 cm
/gate/RF193/geometry/setYLength 20 cm
/gate/RF193/geometry/setZLength 4.482000 cm
/gate/RF193/placement/setTranslation -9.757500 0 -0.759000 cm
/gate/RF193/vis/forceSolid
/gate/RF193/vis/setColor yellow
/gate/RF193/repeaters/insert linear
/gate/RF193/linear/setRepeatNumber 40
/gate/RF193/linear/setRepeatVector 5 0 0 mm
/gate/RF193/linear/autoCenter false
/gate/RF_box/daughters/name RF195
/gate/RF_box/daughters/insert box
/gate/RF195/setMaterial Aluminium
/gate/RF195/geometry/setXLength 0.001000 cm
/gate/RF195/geometry/setYLength 20 cm
/gate/RF195/geometry/setZLength 4.527000 cm
/gate/RF195/placement/setTranslation -9.756500 0 -0.736500 cm
/gate/RF195/vis/forceSolid
/gate/RF195/vis/setColor yellow
/gate/RF195/repeaters/insert linear
/gate/RF195/linear/setRepeatNumber 40
/gate/RF195/linear/setRepeatVector 5 0 0 mm
/gate/RF195/linear/autoCenter false
/gate/RF_box/daughters/name RF196
/gate/RF_box/daughters/insert box
/gate/RF196/setMaterial Aluminium
/gate/RF196/geometry/setXLength 0.001000 cm
/gate/RF196/geometry/setYLength 20 cm
/gate/RF196/geometry/setZLength 4.550000 cm
/gate/RF196/placement/setTranslation -9.755500 0 -0.725000 cm
/gate/RF196/vis/forceSolid
/gate/RF196/vis/setColor yellow
/gate/RF196/repeaters/insert linear
/gate/RF196/linear/setRepeatNumber 40
/gate/RF196/linear/setRepeatVector 5 0 0 mm
/gate/RF196/linear/autoCenter false
/gate/RF_box/daughters/name RF197
/gate/RF_box/daughters/insert box
/gate/RF197/setMaterial Aluminium
/gate/RF197/geometry/setXLength 0.001000 cm
/gate/RF197/geometry/setYLength 20 cm
/gate/RF197/geometry/setZLength 4.572000 cm
/gate/RF197/placement/setTranslation -9.754500 0 -0.714000 cm
/gate/RF197/vis/forceSolid
/gate/RF197/vis/setColor yellow
/gate/RF197/repeaters/insert linear
/gate/RF197/linear/setRepeatNumber 40
/gate/RF197/linear/setRepeatVector 5 0 0 mm
/gate/RF197/linear/autoCenter false
/gate/RF_box/daughters/name RF198
/gate/RF_box/daughters/insert box
/gate/RF198/setMaterial Aluminium
/gate/RF198/geometry/setXLength 0.001000 cm
/gate/RF198/geometry/setYLength 20 cm
/gate/RF198/geometry/setZLength 4.595000 cm
/gate/RF198/placement/setTranslation -9.753500 0 -0.702500 cm
/gate/RF198/vis/forceSolid
/gate/RF198/vis/setColor yellow
/gate/RF198/repeaters/insert linear
/gate/RF198/linear/setRepeatNumber 40
/gate/RF198/linear/setRepeatVector 5 0 0 mm
/gate/RF198/linear/autoCenter false
/gate/RF_box/daughters/name RF201
/gate/RF_box/daughters/insert box
/gate/RF201/setMaterial Aluminium
/gate/RF201/geometry/setXLength 0.006000 cm
/gate/RF201/geometry/setYLength 20 cm
/gate/RF201/geometry/setZLength 4.663000 cm
/gate/RF201/placement/setTranslation -9.750000 0 -0.668500 cm
/gate/RF201/vis/forceSolid
/gate/RF201/vis/setColor yellow
/gate/RF201/repeaters/insert linear
/gate/RF201/linear/setRepeatNumber 40
/gate/RF201/linear/setRepeatVector 5 0 0 mm
/gate/RF201/linear/autoCenter false
/gate/RF_box/daughters/name RF204
/gate/RF_box/daughters/insert box
/gate/RF204/setMaterial Aluminium
/gate/RF204/geometry/setXLength 0.001000 cm
/gate/RF204/geometry/setYLength 20 cm
/gate/RF204/geometry/setZLength 4.595000 cm
/gate/RF204/placement/setTranslation -9.746500 0 -0.702500 cm
/gate/RF204/vis/forceSolid
/gate/RF204/vis/setColor yellow
/gate/RF204/repeaters/insert linear
/gate/RF204/linear/setRepeatNumber 40
/gate/RF204/linear/setRepeatVector 5 0 0 mm
/gate/RF204/linear/autoCenter false
/gate/RF_box/daughters/name RF205
/gate/RF_box/daughters/insert box
/gate/RF205/setMaterial Aluminium
/gate/RF205/geometry/setXLength 0.001000 cm
/gate/RF205/geometry/setYLength 20 cm
/gate/RF205/geometry/setZLength 4.572000 cm
/gate/RF205/placement/setTranslation -9.745500 0 -0.714000 cm
/gate/RF205/vis/forceSolid
/gate/RF205/vis/setColor yellow
/gate/RF205/repeaters/insert linear
/gate/RF205/linear/setRepeatNumber 40
/gate/RF205/linear/setRepeatVector 5 0 0 mm
/gate/RF205/linear/autoCenter false
/gate/RF_box/daughters/name RF206
/gate/RF_box/daughters/insert box
/gate/RF206/setMaterial Aluminium
/gate/RF206/geometry/setXLength 0.001000 cm
/gate/RF206/geometry/setYLength 20 cm
/gate/RF206/geometry/setZLength 4.550000 cm
/gate/RF206/placement/setTranslation -9.744500 0 -0.725000 cm
/gate/RF206/vis/forceSolid
/gate/RF206/vis/setColor yellow
/gate/RF206/repeaters/insert linear
/gate/RF206/linear/setRepeatNumber 40
/gate/RF206/linear/setRepeatVector 5 0 0 mm
/gate/RF206/linear/autoCenter false
/gate/RF_box/daughters/name RF207
/gate/RF_box/daughters/insert box
/gate/RF207/setMaterial Aluminium
/gate/RF207/geometry/setXLength 0.001000 cm
/gate/RF207/geometry/setYLength 20 cm
/gate/RF207/geometry/setZLength 4.527000 cm
/gate/RF207/placement/setTranslation -9.743500 0 -0.736500 cm
/gate/RF207/vis/forceSolid
/gate/RF207/vis/setColor yellow
/gate/RF207/repeaters/insert linear
/gate/RF207/linear/setRepeatNumber 40
/gate/RF207/linear/setRepeatVector 5 0 0 mm
/gate/RF207/linear/autoCenter false
/gate/RF_box/daughters/name RF209
/gate/RF_box/daughters/insert box
/gate/RF209/setMaterial Aluminium
/gate/RF209/geometry/setXLength 0.001000 cm
/gate/RF209/geometry/setYLength 20 cm
/gate/RF209/geometry/setZLength 4.482000 cm
/gate/RF209/placement/setTranslation -9.742500 0 -0.759000 cm
/gate/RF209/vis/forceSolid
/gate/RF209/vis/setColor yellow
/gate/RF209/repeaters/insert linear
/gate/RF209/linear/setRepeatNumber 40
/gate/RF209/linear/setRepeatVector 5 0 0 mm
/gate/RF209/linear/autoCenter false
/gate/RF_box/daughters/name RF210
/gate/RF_box/daughters/insert box
/gate/RF210/setMaterial Aluminium
/gate/RF210/geometry/setXLength 0.001000 cm
/gate/RF210/geometry/setYLength 20 cm
/gate/RF210/geometry/setZLength 4.459000 cm
/gate/RF210/placement/setTranslation -9.741500 0 -0.770500 cm
/gate/RF210/vis/forceSolid
/gate/RF210/vis/setColor yellow
/gate/RF210/repeaters/insert linear
/gate/RF210/linear/setRepeatNumber 40
/gate/RF210/linear/setRepeatVector 5 0 0 mm
/gate/RF210/linear/autoCenter false
/gate/RF_box/daughters/name RF211
/gate/RF_box/daughters/insert box
/gate/RF211/setMaterial Aluminium
/gate/RF211/geometry/setXLength 0.001000 cm
/gate/RF211/geometry/setYLength 20 cm
/gate/RF211/geometry/setZLength 4.436000 cm
/gate/RF211/placement/setTranslation -9.740500 0 -0.782000 cm
/gate/RF211/vis/forceSolid
/gate/RF211/vis/setColor yellow
/gate/RF211/repeaters/insert linear
/gate/RF211/linear/setRepeatNumber 40
/gate/RF211/linear/setRepeatVector 5 0 0 mm
/gate/RF211/linear/autoCenter false
/gate/RF_box/daughters/name RF213
/gate/RF_box/daughters/insert box
/gate/RF213/setMaterial Aluminium
/gate/RF213/geometry/setXLength 0.001000 cm
/gate/RF213/geometry/setYLength 20 cm
/gate/RF213/geometry/setZLength 4.391000 cm
/gate/RF213/placement/setTranslation -9.739500 0 -0.804500 cm
/gate/RF213/vis/forceSolid
/gate/RF213/vis/setColor yellow
/gate/RF213/repeaters/insert linear
/gate/RF213/linear/setRepeatNumber 40
/gate/RF213/linear/setRepeatVector 5 0 0 mm
/gate/RF213/linear/autoCenter false
/gate/RF_box/daughters/name RF214
/gate/RF_box/daughters/insert box
/gate/RF214/setMaterial Aluminium
/gate/RF214/geometry/setXLength 0.001000 cm
/gate/RF214/geometry/setYLength 20 cm
/gate/RF214/geometry/setZLength 4.368000 cm
/gate/RF214/placement/setTranslation -9.738500 0 -0.816000 cm
/gate/RF214/vis/forceSolid
/gate/RF214/vis/setColor yellow
/gate/RF214/repeaters/insert linear
/gate/RF214/linear/setRepeatNumber 40
/gate/RF214/linear/setRepeatVector 5 0 0 mm
/gate/RF214/linear/autoCenter false
/gate/RF_box/daughters/name RF215
/gate/RF_box/daughters/insert box
/gate/RF215/setMaterial Aluminium
/gate/RF215/geometry/setXLength 0.001000 cm
/gate/RF215/geometry/setYLength 20 cm
/gate/RF215/geometry/setZLength 4.346000 cm
/gate/RF215/placement/setTranslation -9.737500 0 -0.827000 cm
/gate/RF215/vis/forceSolid
/gate/RF215/vis/setColor yellow
/gate/RF215/repeaters/insert linear
/gate/RF215/linear/setRepeatNumber 40
/gate/RF215/linear/setRepeatVector 5 0 0 mm
/gate/RF215/linear/autoCenter false
/gate/RF_box/daughters/name RF216
/gate/RF_box/daughters/insert box
/gate/RF216/setMaterial Aluminium
/gate/RF216/geometry/setXLength 0.001000 cm
/gate/RF216/geometry/setYLength 20 cm
/gate/RF216/geometry/setZLength 4.323000 cm
/gate/RF216/placement/setTranslation -9.736500 0 -0.838500 cm
/gate/RF216/vis/forceSolid
/gate/RF216/vis/setColor yellow
/gate/RF216/repeaters/insert linear
/gate/RF216/linear/setRepeatNumber 40
/gate/RF216/linear/setRepeatVector 5 0 0 mm
/gate/RF216/linear/autoCenter false
/gate/RF_box/daughters/name RF218
/gate/RF_box/daughters/insert box
/gate/RF218/setMaterial Aluminium
/gate/RF218/geometry/setXLength 0.001000 cm
/gate/RF218/geometry/setYLength 20 cm
/gate/RF218/geometry/setZLength 4.278000 cm
/gate/RF218/placement/setTranslation -9.735500 0 -0.861000 cm
/gate/RF218/vis/forceSolid
/gate/RF218/vis/setColor yellow
/gate/RF218/repeaters/insert linear
/gate/RF218/linear/setRepeatNumber 40
/gate/RF218/linear/setRepeatVector 5 0 0 mm
/gate/RF218/linear/autoCenter false
/gate/RF_box/daughters/name RF219
/gate/RF_box/daughters/insert box
/gate/RF219/setMaterial Aluminium
/gate/RF219/geometry/setXLength 0.001000 cm
/gate/RF219/geometry/setYLength 20 cm
/gate/RF219/geometry/setZLength 4.255000 cm
/gate/RF219/placement/setTranslation -9.734500 0 -0.872500 cm
/gate/RF219/vis/forceSolid
/gate/RF219/vis/setColor yellow
/gate/RF219/repeaters/insert linear
/gate/RF219/linear/setRepeatNumber 40
/gate/RF219/linear/setRepeatVector 5 0 0 mm
/gate/RF219/linear/autoCenter false
/gate/RF_box/daughters/name RF220
/gate/RF_box/daughters/insert box
/gate/RF220/setMaterial Aluminium
/gate/RF220/geometry/setXLength 0.001000 cm
/gate/RF220/geometry/setYLength 20 cm
/gate/RF220/geometry/setZLength 4.233000 cm
/gate/RF220/placement/setTranslation -9.733500 0 -0.883500 cm
/gate/RF220/vis/forceSolid
/gate/RF220/vis/setColor yellow
/gate/RF220/repeaters/insert linear
/gate/RF220/linear/setRepeatNumber 40
/gate/RF220/linear/setRepeatVector 5 0 0 mm
/gate/RF220/linear/autoCenter false
/gate/RF_box/daughters/name RF221
/gate/RF_box/daughters/insert box
/gate/RF221/setMaterial Aluminium
/gate/RF221/geometry/setXLength 0.001000 cm
/gate/RF221/geometry/setYLength 20 cm
/gate/RF221/geometry/setZLength 4.210000 cm
/gate/RF221/placement/setTranslation -9.732500 0 -0.895000 cm
/gate/RF221/vis/forceSolid
/gate/RF221/vis/setColor yellow
/gate/RF221/repeaters/insert linear
/gate/RF221/linear/setRepeatNumber 40
/gate/RF221/linear/setRepeatVector 5 0 0 mm
/gate/RF221/linear/autoCenter false
/gate/RF_box/daughters/name RF223
/gate/RF_box/daughters/insert box
/gate/RF223/setMaterial Aluminium
/gate/RF223/geometry/setXLength 0.001000 cm
/gate/RF223/geometry/setYLength 20 cm
/gate/RF223/geometry/setZLength 4.165000 cm
/gate/RF223/placement/setTranslation -9.731500 0 -0.917500 cm
/gate/RF223/vis/forceSolid
/gate/RF223/vis/setColor yellow
/gate/RF223/repeaters/insert linear
/gate/RF223/linear/setRepeatNumber 40
/gate/RF223/linear/setRepeatVector 5 0 0 mm
/gate/RF223/linear/autoCenter false
/gate/RF_box/daughters/name RF224
/gate/RF_box/daughters/insert box
/gate/RF224/setMaterial Aluminium
/gate/RF224/geometry/setXLength 0.001000 cm
/gate/RF224/geometry/setYLength 20 cm
/gate/RF224/geometry/setZLength 4.142000 cm
/gate/RF224/placement/setTranslation -9.730500 0 -0.929000 cm
/gate/RF224/vis/forceSolid
/gate/RF224/vis/setColor yellow
/gate/RF224/repeaters/insert linear
/gate/RF224/linear/setRepeatNumber 40
/gate/RF224/linear/setRepeatVector 5 0 0 mm
/gate/RF224/linear/autoCenter false
/gate/RF_box/daughters/name RF225
/gate/RF_box/daughters/insert box
/gate/RF225/setMaterial Aluminium
/gate/RF225/geometry/setXLength 0.001000 cm
/gate/RF225/geometry/setYLength 20 cm
/gate/RF225/geometry/setZLength 4.120000 cm
/gate/RF225/placement/setTranslation -9.729500 0 -0.940000 cm
/gate/RF225/vis/forceSolid
/gate/RF225/vis/setColor yellow
/gate/RF225/repeaters/insert linear
/gate/RF225/linear/setRepeatNumber 40
/gate/RF225/linear/setRepeatVector 5 0 0 mm
/gate/RF225/linear/autoCenter false
/gate/RF_box/daughters/name RF227
/gate/RF_box/daughters/insert box
/gate/RF227/setMaterial Aluminium
/gate/RF227/geometry/setXLength 0.001000 cm
/gate/RF227/geometry/setYLength 20 cm
/gate/RF227/geometry/setZLength 4.074000 cm
/gate/RF227/placement/setTranslation -9.728500 0 -0.963000 cm
/gate/RF227/vis/forceSolid
/gate/RF227/vis/setColor yellow
/gate/RF227/repeaters/insert linear
/gate/RF227/linear/setRepeatNumber 40
/gate/RF227/linear/setRepeatVector 5 0 0 mm
/gate/RF227/linear/autoCenter false
/gate/RF_box/daughters/name RF228
/gate/RF_box/daughters/insert box
/gate/RF228/setMaterial Aluminium
/gate/RF228/geometry/setXLength 0.001000 cm
/gate/RF228/geometry/setYLength 20 cm
/gate/RF228/geometry/setZLength 4.052000 cm
/gate/RF228/placement/setTranslation -9.727500 0 -0.974000 cm
/gate/RF228/vis/forceSolid
/gate/RF228/vis/setColor yellow
/gate/RF228/repeaters/insert linear
/gate/RF228/linear/setRepeatNumber 40
/gate/RF228/linear/setRepeatVector 5 0 0 mm
/gate/RF228/linear/autoCenter false
/gate/RF_box/daughters/name RF229
/gate/RF_box/daughters/insert box
/gate/RF229/setMaterial Aluminium
/gate/RF229/geometry/setXLength 0.001000 cm
/gate/RF229/geometry/setYLength 20 cm
/gate/RF229/geometry/setZLength 4.029000 cm
/gate/RF229/placement/setTranslation -9.726500 0 -0.985500 cm
/gate/RF229/vis/forceSolid
/gate/RF229/vis/setColor yellow
/gate/RF229/repeaters/insert linear
/gate/RF229/linear/setRepeatNumber 40
/gate/RF229/linear/setRepeatVector 5 0 0 mm
/gate/RF229/linear/autoCenter false
/gate/RF_box/daughters/name RF230
/gate/RF_box/daughters/insert box
/gate/RF230/setMaterial Aluminium
/gate/RF230/geometry/setXLength 0.001000 cm
/gate/RF230/geometry/setYLength 20 cm
/gate/RF230/geometry/setZLength 4.006000 cm
/gate/RF230/placement/setTranslation -9.725500 0 -0.997000 cm
/gate/RF230/vis/forceSolid
/gate/RF230/vis/setColor yellow
/gate/RF230/repeaters/insert linear
/gate/RF230/linear/setRepeatNumber 40
/gate/RF230/linear/setRepeatVector 5 0 0 mm
/gate/RF230/linear/autoCenter false
/gate/RF_box/daughters/name RF232
/gate/RF_box/daughters/insert box
/gate/RF232/setMaterial Aluminium
/gate/RF232/geometry/setXLength 0.001000 cm
/gate/RF232/geometry/setYLength 20 cm
/gate/RF232/geometry/setZLength 3.961000 cm
/gate/RF232/placement/setTranslation -9.724500 0 -1.019500 cm
/gate/RF232/vis/forceSolid
/gate/RF232/vis/setColor yellow
/gate/RF232/repeaters/insert linear
/gate/RF232/linear/setRepeatNumber 40
/gate/RF232/linear/setRepeatVector 5 0 0 mm
/gate/RF232/linear/autoCenter false
/gate/RF_box/daughters/name RF233
/gate/RF_box/daughters/insert box
/gate/RF233/setMaterial Aluminium
/gate/RF233/geometry/setXLength 0.001000 cm
/gate/RF233/geometry/setYLength 20 cm
/gate/RF233/geometry/setZLength 3.938000 cm
/gate/RF233/placement/setTranslation -9.723500 0 -1.031000 cm
/gate/RF233/vis/forceSolid
/gate/RF233/vis/setColor yellow
/gate/RF233/repeaters/insert linear
/gate/RF233/linear/setRepeatNumber 40
/gate/RF233/linear/setRepeatVector 5 0 0 mm
/gate/RF233/linear/autoCenter false
/gate/RF_box/daughters/name RF234
/gate/RF_box/daughters/insert box
/gate/RF234/setMaterial Aluminium
/gate/RF234/geometry/setXLength 0.001000 cm
/gate/RF234/geometry/setYLength 20 cm
/gate/RF234/geometry/setZLength 3.916000 cm
/gate/RF234/placement/setTranslation -9.722500 0 -1.042000 cm
/gate/RF234/vis/forceSolid
/gate/RF234/vis/setColor yellow
/gate/RF234/repeaters/insert linear
/gate/RF234/linear/setRepeatNumber 40
/gate/RF234/linear/setRepeatVector 5 0 0 mm
/gate/RF234/linear/autoCenter false
/gate/RF_box/daughters/name RF235
/gate/RF_box/daughters/insert box
/gate/RF235/setMaterial Aluminium
/gate/RF235/geometry/setXLength 0.001000 cm
/gate/RF235/geometry/setYLength 20 cm
/gate/RF235/geometry/setZLength 3.893000 cm
/gate/RF235/placement/setTranslation -9.721500 0 -1.053500 cm
/gate/RF235/vis/forceSolid
/gate/RF235/vis/setColor yellow
/gate/RF235/repeaters/insert linear
/gate/RF235/linear/setRepeatNumber 40
/gate/RF235/linear/setRepeatVector 5 0 0 mm
/gate/RF235/linear/autoCenter false
/gate/RF_box/daughters/name RF237
/gate/RF_box/daughters/insert box
/gate/RF237/setMaterial Aluminium
/gate/RF237/geometry/setXLength 0.001000 cm
/gate/RF237/geometry/setYLength 20 cm
/gate/RF237/geometry/setZLength 3.848000 cm
/gate/RF237/placement/setTranslation -9.720500 0 -1.076000 cm
/gate/RF237/vis/forceSolid
/gate/RF237/vis/setColor yellow
/gate/RF237/repeaters/insert linear
/gate/RF237/linear/setRepeatNumber 40
/gate/RF237/linear/setRepeatVector 5 0 0 mm
/gate/RF237/linear/autoCenter false
/gate/RF_box/daughters/name RF238
/gate/RF_box/daughters/insert box
/gate/RF238/setMaterial Aluminium
/gate/RF238/geometry/setXLength 0.001000 cm
/gate/RF238/geometry/setYLength 20 cm
/gate/RF238/geometry/setZLength 3.825000 cm
/gate/RF238/placement/setTranslation -9.719500 0 -1.087500 cm
/gate/RF238/vis/forceSolid
/gate/RF238/vis/setColor yellow
/gate/RF238/repeaters/insert linear
/gate/RF238/linear/setRepeatNumber 40
/gate/RF238/linear/setRepeatVector 5 0 0 mm
/gate/RF238/linear/autoCenter false
/gate/RF_box/daughters/name RF239
/gate/RF_box/daughters/insert box
/gate/RF239/setMaterial Aluminium
/gate/RF239/geometry/setXLength 0.001000 cm
/gate/RF239/geometry/setYLength 20 cm
/gate/RF239/geometry/setZLength 3.803000 cm
/gate/RF239/placement/setTranslation -9.718500 0 -1.098500 cm
/gate/RF239/vis/forceSolid
/gate/RF239/vis/setColor yellow
/gate/RF239/repeaters/insert linear
/gate/RF239/linear/setRepeatNumber 40
/gate/RF239/linear/setRepeatVector 5 0 0 mm
/gate/RF239/linear/autoCenter false
/gate/RF_box/daughters/name RF240
/gate/RF_box/daughters/insert box
/gate/RF240/setMaterial Aluminium
/gate/RF240/geometry/setXLength 0.001000 cm
/gate/RF240/geometry/setYLength 20 cm
/gate/RF240/geometry/setZLength 3.780000 cm
/gate/RF240/placement/setTranslation -9.717500 0 -1.110000 cm
/gate/RF240/vis/forceSolid
/gate/RF240/vis/setColor yellow
/gate/RF240/repeaters/insert linear
/gate/RF240/linear/setRepeatNumber 40
/gate/RF240/linear/setRepeatVector 5 0 0 mm
/gate/RF240/linear/autoCenter false
/gate/RF_box/daughters/name RF241
/gate/RF_box/daughters/insert box
/gate/RF241/setMaterial Aluminium
/gate/RF241/geometry/setXLength 0.001000 cm
/gate/RF241/geometry/setYLength 20 cm
/gate/RF241/geometry/setZLength 3.757000 cm
/gate/RF241/placement/setTranslation -9.716500 0 -1.121500 cm
/gate/RF241/vis/forceSolid
/gate/RF241/vis/setColor yellow
/gate/RF241/repeaters/insert linear
/gate/RF241/linear/setRepeatNumber 40
/gate/RF241/linear/setRepeatVector 5 0 0 mm
/gate/RF241/linear/autoCenter false
/gate/RF_box/daughters/name RF243
/gate/RF_box/daughters/insert box
/gate/RF243/setMaterial Aluminium
/gate/RF243/geometry/setXLength 0.001000 cm
/gate/RF243/geometry/setYLength 20 cm
/gate/RF243/geometry/setZLength 3.712000 cm
/gate/RF243/placement/setTranslation -9.715500 0 -1.144000 cm
/gate/RF243/vis/forceSolid
/gate/RF243/vis/setColor yellow
/gate/RF243/repeaters/insert linear
/gate/RF243/linear/setRepeatNumber 40
/gate/RF243/linear/setRepeatVector 5 0 0 mm
/gate/RF243/linear/autoCenter false
/gate/RF_box/daughters/name RF244
/gate/RF_box/daughters/insert box
/gate/RF244/setMaterial Aluminium
/gate/RF244/geometry/setXLength 0.001000 cm
/gate/RF244/geometry/setYLength 20 cm
/gate/RF244/geometry/setZLength 3.689000 cm
/gate/RF244/placement/setTranslation -9.714500 0 -1.155500 cm
/gate/RF244/vis/forceSolid
/gate/RF244/vis/setColor yellow
/gate/RF244/repeaters/insert linear
/gate/RF244/linear/setRepeatNumber 40
/gate/RF244/linear/setRepeatVector 5 0 0 mm
/gate/RF244/linear/autoCenter false
/gate/RF_box/daughters/name RF245
/gate/RF_box/daughters/insert box
/gate/RF245/setMaterial Aluminium
/gate/RF245/geometry/setXLength 0.001000 cm
/gate/RF245/geometry/setYLength 20 cm
/gate/RF245/geometry/setZLength 3.667000 cm
/gate/RF245/placement/setTranslation -9.713500 0 -1.166500 cm
/gate/RF245/vis/forceSolid
/gate/RF245/vis/setColor yellow
/gate/RF245/repeaters/insert linear
/gate/RF245/linear/setRepeatNumber 40
/gate/RF245/linear/setRepeatVector 5 0 0 mm
/gate/RF245/linear/autoCenter false
/gate/RF_box/daughters/name RF246
/gate/RF_box/daughters/insert box
/gate/RF246/setMaterial Aluminium
/gate/RF246/geometry/setXLength 0.001000 cm
/gate/RF246/geometry/setYLength 20 cm
/gate/RF246/geometry/setZLength 3.644000 cm
/gate/RF246/placement/setTranslation -9.712500 0 -1.178000 cm
/gate/RF246/vis/forceSolid
/gate/RF246/vis/setColor yellow
/gate/RF246/repeaters/insert linear
/gate/RF246/linear/setRepeatNumber 40
/gate/RF246/linear/setRepeatVector 5 0 0 mm
/gate/RF246/linear/autoCenter false
/gate/RF_box/daughters/name RF248
/gate/RF_box/daughters/insert box
/gate/RF248/setMaterial Aluminium
/gate/RF248/geometry/setXLength 0.001000 cm
/gate/RF248/geometry/setYLength 20 cm
/gate/RF248/geometry/setZLength 3.599000 cm
/gate/RF248/placement/setTranslation -9.711500 0 -1.200500 cm
/gate/RF248/vis/forceSolid
/gate/RF248/vis/setColor yellow
/gate/RF248/repeaters/insert linear
/gate/RF248/linear/setRepeatNumber 40
/gate/RF248/linear/setRepeatVector 5 0 0 mm
/gate/RF248/linear/autoCenter false
/gate/RF_box/daughters/name RF249
/gate/RF_box/daughters/insert box
/gate/RF249/setMaterial Aluminium
/gate/RF249/geometry/setXLength 0.001000 cm
/gate/RF249/geometry/setYLength 20 cm
/gate/RF249/geometry/setZLength 3.576000 cm
/gate/RF249/placement/setTranslation -9.710500 0 -1.212000 cm
/gate/RF249/vis/forceSolid
/gate/RF249/vis/setColor yellow
/gate/RF249/repeaters/insert linear
/gate/RF249/linear/setRepeatNumber 40
/gate/RF249/linear/setRepeatVector 5 0 0 mm
/gate/RF249/linear/autoCenter false
/gate/RF_box/daughters/name RF250
/gate/RF_box/daughters/insert box
/gate/RF250/setMaterial Aluminium
/gate/RF250/geometry/setXLength 0.001000 cm
/gate/RF250/geometry/setYLength 20 cm
/gate/RF250/geometry/setZLength 3.554000 cm
/gate/RF250/placement/setTranslation -9.709500 0 -1.223000 cm
/gate/RF250/vis/forceSolid
/gate/RF250/vis/setColor yellow
/gate/RF250/repeaters/insert linear
/gate/RF250/linear/setRepeatNumber 40
/gate/RF250/linear/setRepeatVector 5 0 0 mm
/gate/RF250/linear/autoCenter false
/gate/RF_box/daughters/name RF251
/gate/RF_box/daughters/insert box
/gate/RF251/setMaterial Aluminium
/gate/RF251/geometry/setXLength 0.001000 cm
/gate/RF251/geometry/setYLength 20 cm
/gate/RF251/geometry/setZLength 3.531000 cm
/gate/RF251/placement/setTranslation -9.708500 0 -1.234500 cm
/gate/RF251/vis/forceSolid
/gate/RF251/vis/setColor yellow
/gate/RF251/repeaters/insert linear
/gate/RF251/linear/setRepeatNumber 40
/gate/RF251/linear/setRepeatVector 5 0 0 mm
/gate/RF251/linear/autoCenter false
/gate/RF_box/daughters/name RF252
/gate/RF_box/daughters/insert box
/gate/RF252/setMaterial Aluminium
/gate/RF252/geometry/setXLength 0.001000 cm
/gate/RF252/geometry/setYLength 20 cm
/gate/RF252/geometry/setZLength 3.508000 cm
/gate/RF252/placement/setTranslation -9.707500 0 -1.246000 cm
/gate/RF252/vis/forceSolid
/gate/RF252/vis/setColor yellow
/gate/RF252/repeaters/insert linear
/gate/RF252/linear/setRepeatNumber 40
/gate/RF252/linear/setRepeatVector 5 0 0 mm
/gate/RF252/linear/autoCenter false
/gate/RF_box/daughters/name RF254
/gate/RF_box/daughters/insert box
/gate/RF254/setMaterial Aluminium
/gate/RF254/geometry/setXLength 0.001000 cm
/gate/RF254/geometry/setYLength 20 cm
/gate/RF254/geometry/setZLength 3.463000 cm
/gate/RF254/placement/setTranslation -9.706500 0 -1.268500 cm
/gate/RF254/vis/forceSolid
/gate/RF254/vis/setColor yellow
/gate/RF254/repeaters/insert linear
/gate/RF254/linear/setRepeatNumber 40
/gate/RF254/linear/setRepeatVector 5 0 0 mm
/gate/RF254/linear/autoCenter false
/gate/RF_box/daughters/name RF255
/gate/RF_box/daughters/insert box
/gate/RF255/setMaterial Aluminium
/gate/RF255/geometry/setXLength 0.001000 cm
/gate/RF255/geometry/setYLength 20 cm
/gate/RF255/geometry/setZLength 3.440000 cm
/gate/RF255/placement/setTranslation -9.705500 0 -1.280000 cm
/gate/RF255/vis/forceSolid
/gate/RF255/vis/setColor yellow
/gate/RF255/repeaters/insert linear
/gate/RF255/linear/setRepeatNumber 40
/gate/RF255/linear/setRepeatVector 5 0 0 mm
/gate/RF255/linear/autoCenter false
/gate/RF_box/daughters/name RF256
/gate/RF_box/daughters/insert box
/gate/RF256/setMaterial Aluminium
/gate/RF256/geometry/setXLength 0.001000 cm
/gate/RF256/geometry/setYLength 20 cm
/gate/RF256/geometry/setZLength 3.418000 cm
/gate/RF256/placement/setTranslation -9.704500 0 -1.291000 cm
/gate/RF256/vis/forceSolid
/gate/RF256/vis/setColor yellow
/gate/RF256/repeaters/insert linear
/gate/RF256/linear/setRepeatNumber 40
/gate/RF256/linear/setRepeatVector 5 0 0 mm
/gate/RF256/linear/autoCenter false
/gate/RF_box/daughters/name RF257
/gate/RF_box/daughters/insert box
/gate/RF257/setMaterial Aluminium
/gate/RF257/geometry/setXLength 0.001000 cm
/gate/RF257/geometry/setYLength 20 cm
/gate/RF257/geometry/setZLength 3.395000 cm
/gate/RF257/placement/setTranslation -9.703500 0 -1.302500 cm
/gate/RF257/vis/forceSolid
/gate/RF257/vis/setColor yellow
/gate/RF257/repeaters/insert linear
/gate/RF257/linear/setRepeatNumber 40
/gate/RF257/linear/setRepeatVector 5 0 0 mm
/gate/RF257/linear/autoCenter false
/gate/RF_box/daughters/name RF258
/gate/RF_box/daughters/insert box
/gate/RF258/setMaterial Aluminium
/gate/RF258/geometry/setXLength 0.001000 cm
/gate/RF258/geometry/setYLength 20 cm
/gate/RF258/geometry/setZLength 3.373000 cm
/gate/RF258/placement/setTranslation -9.702500 0 -1.313500 cm
/gate/RF258/vis/forceSolid
/gate/RF258/vis/setColor yellow
/gate/RF258/repeaters/insert linear
/gate/RF258/linear/setRepeatNumber 40
/gate/RF258/linear/setRepeatVector 5 0 0 mm
/gate/RF258/linear/autoCenter false
/gate/RF_box/daughters/name RF260
/gate/RF_box/daughters/insert box
/gate/RF260/setMaterial Aluminium
/gate/RF260/geometry/setXLength 0.001000 cm
/gate/RF260/geometry/setYLength 20 cm
/gate/RF260/geometry/setZLength 3.327000 cm
/gate/RF260/placement/setTranslation -9.701500 0 -1.336500 cm
/gate/RF260/vis/forceSolid
/gate/RF260/vis/setColor yellow
/gate/RF260/repeaters/insert linear
/gate/RF260/linear/setRepeatNumber 40
/gate/RF260/linear/setRepeatVector 5 0 0 mm
/gate/RF260/linear/autoCenter false
/gate/RF_box/daughters/name RF261
/gate/RF_box/daughters/insert box
/gate/RF261/setMaterial Aluminium
/gate/RF261/geometry/setXLength 0.001000 cm
/gate/RF261/geometry/setYLength 20 cm
/gate/RF261/geometry/setZLength 3.305000 cm
/gate/RF261/placement/setTranslation -9.700500 0 -1.347500 cm
/gate/RF261/vis/forceSolid
/gate/RF261/vis/setColor yellow
/gate/RF261/repeaters/insert linear
/gate/RF261/linear/setRepeatNumber 40
/gate/RF261/linear/setRepeatVector 5 0 0 mm
/gate/RF261/linear/autoCenter false
/gate/RF_box/daughters/name RF262
/gate/RF_box/daughters/insert box
/gate/RF262/setMaterial Aluminium
/gate/RF262/geometry/setXLength 0.001000 cm
/gate/RF262/geometry/setYLength 20 cm
/gate/RF262/geometry/setZLength 3.282000 cm
/gate/RF262/placement/setTranslation -9.699500 0 -1.359000 cm
/gate/RF262/vis/forceSolid
/gate/RF262/vis/setColor yellow
/gate/RF262/repeaters/insert linear
/gate/RF262/linear/setRepeatNumber 40
/gate/RF262/linear/setRepeatVector 5 0 0 mm
/gate/RF262/linear/autoCenter false
/gate/RF_box/daughters/name RF263
/gate/RF_box/daughters/insert box
/gate/RF263/setMaterial Aluminium
/gate/RF263/geometry/setXLength 0.001000 cm
/gate/RF263/geometry/setYLength 20 cm
/gate/RF263/geometry/setZLength 3.259000 cm
/gate/RF263/placement/setTranslation -9.698500 0 -1.370500 cm
/gate/RF263/vis/forceSolid
/gate/RF263/vis/setColor yellow
/gate/RF263/repeaters/insert linear
/gate/RF263/linear/setRepeatNumber 40
/gate/RF263/linear/setRepeatVector 5 0 0 mm
/gate/RF263/linear/autoCenter false
/gate/RF_box/daughters/name RF264
/gate/RF_box/daughters/insert box
/gate/RF264/setMaterial Aluminium
/gate/RF264/geometry/setXLength 0.001000 cm
/gate/RF264/geometry/setYLength 20 cm
/gate/RF264/geometry/setZLength 3.237000 cm
/gate/RF264/placement/setTranslation -9.697500 0 -1.381500 cm
/gate/RF264/vis/forceSolid
/gate/RF264/vis/setColor yellow
/gate/RF264/repeaters/insert linear
/gate/RF264/linear/setRepeatNumber 40
/gate/RF264/linear/setRepeatVector 5 0 0 mm
/gate/RF264/linear/autoCenter false
/gate/RF_box/daughters/name RF265
/gate/RF_box/daughters/insert box
/gate/RF265/setMaterial Aluminium
/gate/RF265/geometry/setXLength 0.001000 cm
/gate/RF265/geometry/setYLength 20 cm
/gate/RF265/geometry/setZLength 3.214000 cm
/gate/RF265/placement/setTranslation -9.696500 0 -1.393000 cm
/gate/RF265/vis/forceSolid
/gate/RF265/vis/setColor yellow
/gate/RF265/repeaters/insert linear
/gate/RF265/linear/setRepeatNumber 40
/gate/RF265/linear/setRepeatVector 5 0 0 mm
/gate/RF265/linear/autoCenter false
/gate/RF_box/daughters/name RF267
/gate/RF_box/daughters/insert box
/gate/RF267/setMaterial Aluminium
/gate/RF267/geometry/setXLength 0.001000 cm
/gate/RF267/geometry/setYLength 20 cm
/gate/RF267/geometry/setZLength 3.169000 cm
/gate/RF267/placement/setTranslation -9.695500 0 -1.415500 cm
/gate/RF267/vis/forceSolid
/gate/RF267/vis/setColor yellow
/gate/RF267/repeaters/insert linear
/gate/RF267/linear/setRepeatNumber 40
/gate/RF267/linear/setRepeatVector 5 0 0 mm
/gate/RF267/linear/autoCenter false
/gate/RF_box/daughters/name RF268
/gate/RF_box/daughters/insert box
/gate/RF268/setMaterial Aluminium
/gate/RF268/geometry/setXLength 0.001000 cm
/gate/RF268/geometry/setYLength 20 cm
/gate/RF268/geometry/setZLength 3.146000 cm
/gate/RF268/placement/setTranslation -9.694500 0 -1.427000 cm
/gate/RF268/vis/forceSolid
/gate/RF268/vis/setColor yellow
/gate/RF268/repeaters/insert linear
/gate/RF268/linear/setRepeatNumber 40
/gate/RF268/linear/setRepeatVector 5 0 0 mm
/gate/RF268/linear/autoCenter false
/gate/RF_box/daughters/name RF269
/gate/RF_box/daughters/insert box
/gate/RF269/setMaterial Aluminium
/gate/RF269/geometry/setXLength 0.001000 cm
/gate/RF269/geometry/setYLength 20 cm
/gate/RF269/geometry/setZLength 3.124000 cm
/gate/RF269/placement/setTranslation -9.693500 0 -1.438000 cm
/gate/RF269/vis/forceSolid
/gate/RF269/vis/setColor yellow
/gate/RF269/repeaters/insert linear
/gate/RF269/linear/setRepeatNumber 40
/gate/RF269/linear/setRepeatVector 5 0 0 mm
/gate/RF269/linear/autoCenter false
/gate/RF_box/daughters/name RF270
/gate/RF_box/daughters/insert box
/gate/RF270/setMaterial Aluminium
/gate/RF270/geometry/setXLength 0.001000 cm
/gate/RF270/geometry/setYLength 20 cm
/gate/RF270/geometry/setZLength 3.101000 cm
/gate/RF270/placement/setTranslation -9.692500 0 -1.449500 cm
/gate/RF270/vis/forceSolid
/gate/RF270/vis/setColor yellow
/gate/RF270/repeaters/insert linear
/gate/RF270/linear/setRepeatNumber 40
/gate/RF270/linear/setRepeatVector 5 0 0 mm
/gate/RF270/linear/autoCenter false
/gate/RF_box/daughters/name RF271
/gate/RF_box/daughters/insert box
/gate/RF271/setMaterial Aluminium
/gate/RF271/geometry/setXLength 0.001000 cm
/gate/RF271/geometry/setYLength 20 cm
/gate/RF271/geometry/setZLength 3.078000 cm
/gate/RF271/placement/setTranslation -9.691500 0 -1.461000 cm
/gate/RF271/vis/forceSolid
/gate/RF271/vis/setColor yellow
/gate/RF271/repeaters/insert linear
/gate/RF271/linear/setRepeatNumber 40
/gate/RF271/linear/setRepeatVector 5 0 0 mm
/gate/RF271/linear/autoCenter false
/gate/RF_box/daughters/name RF272
/gate/RF_box/daughters/insert box
/gate/RF272/setMaterial Aluminium
/gate/RF272/geometry/setXLength 0.001000 cm
/gate/RF272/geometry/setYLength 20 cm
/gate/RF272/geometry/setZLength 3.056000 cm
/gate/RF272/placement/setTranslation -9.690500 0 -1.472000 cm
/gate/RF272/vis/forceSolid
/gate/RF272/vis/setColor yellow
/gate/RF272/repeaters/insert linear
/gate/RF272/linear/setRepeatNumber 40
/gate/RF272/linear/setRepeatVector 5 0 0 mm
/gate/RF272/linear/autoCenter false
/gate/RF_box/daughters/name RF273
/gate/RF_box/daughters/insert box
/gate/RF273/setMaterial Aluminium
/gate/RF273/geometry/setXLength 0.001000 cm
/gate/RF273/geometry/setYLength 20 cm
/gate/RF273/geometry/setZLength 3.033000 cm
/gate/RF273/placement/setTranslation -9.689500 0 -1.483500 cm
/gate/RF273/vis/forceSolid
/gate/RF273/vis/setColor yellow
/gate/RF273/repeaters/insert linear
/gate/RF273/linear/setRepeatNumber 40
/gate/RF273/linear/setRepeatVector 5 0 0 mm
/gate/RF273/linear/autoCenter false
/gate/RF_box/daughters/name RF275
/gate/RF_box/daughters/insert box
/gate/RF275/setMaterial Aluminium
/gate/RF275/geometry/setXLength 0.001000 cm
/gate/RF275/geometry/setYLength 20 cm
/gate/RF275/geometry/setZLength 2.988000 cm
/gate/RF275/placement/setTranslation -9.688500 0 -1.506000 cm
/gate/RF275/vis/forceSolid
/gate/RF275/vis/setColor yellow
/gate/RF275/repeaters/insert linear
/gate/RF275/linear/setRepeatNumber 40
/gate/RF275/linear/setRepeatVector 5 0 0 mm
/gate/RF275/linear/autoCenter false
/gate/RF_box/daughters/name RF276
/gate/RF_box/daughters/insert box
/gate/RF276/setMaterial Aluminium
/gate/RF276/geometry/setXLength 0.001000 cm
/gate/RF276/geometry/setYLength 20 cm
/gate/RF276/geometry/setZLength 2.965000 cm
/gate/RF276/placement/setTranslation -9.687500 0 -1.517500 cm
/gate/RF276/vis/forceSolid
/gate/RF276/vis/setColor yellow
/gate/RF276/repeaters/insert linear
/gate/RF276/linear/setRepeatNumber 40
/gate/RF276/linear/setRepeatVector 5 0 0 mm
/gate/RF276/linear/autoCenter false
/gate/RF_box/daughters/name RF277
/gate/RF_box/daughters/insert box
/gate/RF277/setMaterial Aluminium
/gate/RF277/geometry/setXLength 0.001000 cm
/gate/RF277/geometry/setYLength 20 cm
/gate/RF277/geometry/setZLength 2.943000 cm
/gate/RF277/placement/setTranslation -9.686500 0 -1.528500 cm
/gate/RF277/vis/forceSolid
/gate/RF277/vis/setColor yellow
/gate/RF277/repeaters/insert linear
/gate/RF277/linear/setRepeatNumber 40
/gate/RF277/linear/setRepeatVector 5 0 0 mm
/gate/RF277/linear/autoCenter false
/gate/RF_box/daughters/name RF278
/gate/RF_box/daughters/insert box
/gate/RF278/setMaterial Aluminium
/gate/RF278/geometry/setXLength 0.001000 cm
/gate/RF278/geometry/setYLength 20 cm
/gate/RF278/geometry/setZLength 2.920000 cm
/gate/RF278/placement/setTranslation -9.685500 0 -1.540000 cm
/gate/RF278/vis/forceSolid
/gate/RF278/vis/setColor yellow
/gate/RF278/repeaters/insert linear
/gate/RF278/linear/setRepeatNumber 40
/gate/RF278/linear/setRepeatVector 5 0 0 mm
/gate/RF278/linear/autoCenter false
/gate/RF_box/daughters/name RF279
/gate/RF_box/daughters/insert box
/gate/RF279/setMaterial Aluminium
/gate/RF279/geometry/setXLength 0.001000 cm
/gate/RF279/geometry/setYLength 20 cm
/gate/RF279/geometry/setZLength 2.897000 cm
/gate/RF279/placement/setTranslation -9.684500 0 -1.551500 cm
/gate/RF279/vis/forceSolid
/gate/RF279/vis/setColor yellow
/gate/RF279/repeaters/insert linear
/gate/RF279/linear/setRepeatNumber 40
/gate/RF279/linear/setRepeatVector 5 0 0 mm
/gate/RF279/linear/autoCenter false
/gate/RF_box/daughters/name RF280
/gate/RF_box/daughters/insert box
/gate/RF280/setMaterial Aluminium
/gate/RF280/geometry/setXLength 0.001000 cm
/gate/RF280/geometry/setYLength 20 cm
/gate/RF280/geometry/setZLength 2.875000 cm
/gate/RF280/placement/setTranslation -9.683500 0 -1.562500 cm
/gate/RF280/vis/forceSolid
/gate/RF280/vis/setColor yellow
/gate/RF280/repeaters/insert linear
/gate/RF280/linear/setRepeatNumber 40
/gate/RF280/linear/setRepeatVector 5 0 0 mm
/gate/RF280/linear/autoCenter false
/gate/RF_box/daughters/name RF281
/gate/RF_box/daughters/insert box
/gate/RF281/setMaterial Aluminium
/gate/RF281/geometry/setXLength 0.001000 cm
/gate/RF281/geometry/setYLength 20 cm
/gate/RF281/geometry/setZLength 2.852000 cm
/gate/RF281/placement/setTranslation -9.682500 0 -1.574000 cm
/gate/RF281/vis/forceSolid
/gate/RF281/vis/setColor yellow
/gate/RF281/repeaters/insert linear
/gate/RF281/linear/setRepeatNumber 40
/gate/RF281/linear/setRepeatVector 5 0 0 mm
/gate/RF281/linear/autoCenter false
/gate/RF_box/daughters/name RF282
/gate/RF_box/daughters/insert box
/gate/RF282/setMaterial Aluminium
/gate/RF282/geometry/setXLength 0.001000 cm
/gate/RF282/geometry/setYLength 20 cm
/gate/RF282/geometry/setZLength 2.829000 cm
/gate/RF282/placement/setTranslation -9.681500 0 -1.585500 cm
/gate/RF282/vis/forceSolid
/gate/RF282/vis/setColor yellow
/gate/RF282/repeaters/insert linear
/gate/RF282/linear/setRepeatNumber 40
/gate/RF282/linear/setRepeatVector 5 0 0 mm
/gate/RF282/linear/autoCenter false
/gate/RF_box/daughters/name RF284
/gate/RF_box/daughters/insert box
/gate/RF284/setMaterial Aluminium
/gate/RF284/geometry/setXLength 0.001000 cm
/gate/RF284/geometry/setYLength 20 cm
/gate/RF284/geometry/setZLength 2.784000 cm
/gate/RF284/placement/setTranslation -9.680500 0 -1.608000 cm
/gate/RF284/vis/forceSolid
/gate/RF284/vis/setColor yellow
/gate/RF284/repeaters/insert linear
/gate/RF284/linear/setRepeatNumber 40
/gate/RF284/linear/setRepeatVector 5 0 0 mm
/gate/RF284/linear/autoCenter false
/gate/RF_box/daughters/name RF285
/gate/RF_box/daughters/insert box
/gate/RF285/setMaterial Aluminium
/gate/RF285/geometry/setXLength 0.001000 cm
/gate/RF285/geometry/setYLength 20 cm
/gate/RF285/geometry/setZLength 2.761000 cm
/gate/RF285/placement/setTranslation -9.679500 0 -1.619500 cm
/gate/RF285/vis/forceSolid
/gate/RF285/vis/setColor yellow
/gate/RF285/repeaters/insert linear
/gate/RF285/linear/setRepeatNumber 40
/gate/RF285/linear/setRepeatVector 5 0 0 mm
/gate/RF285/linear/autoCenter false
/gate/RF_box/daughters/name RF286
/gate/RF_box/daughters/insert box
/gate/RF286/setMaterial Aluminium
/gate/RF286/geometry/setXLength 0.001000 cm
/gate/RF286/geometry/setYLength 20 cm
/gate/RF286/geometry/setZLength 2.739000 cm
/gate/RF286/placement/setTranslation -9.678500 0 -1.630500 cm
/gate/RF286/vis/forceSolid
/gate/RF286/vis/setColor yellow
/gate/RF286/repeaters/insert linear
/gate/RF286/linear/setRepeatNumber 40
/gate/RF286/linear/setRepeatVector 5 0 0 mm
/gate/RF286/linear/autoCenter false
/gate/RF_box/daughters/name RF287
/gate/RF_box/daughters/insert box
/gate/RF287/setMaterial Aluminium
/gate/RF287/geometry/setXLength 0.001000 cm
/gate/RF287/geometry/setYLength 20 cm
/gate/RF287/geometry/setZLength 2.716000 cm
/gate/RF287/placement/setTranslation -9.677500 0 -1.642000 cm
/gate/RF287/vis/forceSolid
/gate/RF287/vis/setColor yellow
/gate/RF287/repeaters/insert linear
/gate/RF287/linear/setRepeatNumber 40
/gate/RF287/linear/setRepeatVector 5 0 0 mm
/gate/RF287/linear/autoCenter false
/gate/RF_box/daughters/name RF288
/gate/RF_box/daughters/insert box
/gate/RF288/setMaterial Aluminium
/gate/RF288/geometry/setXLength 0.001000 cm
/gate/RF288/geometry/setYLength 20 cm
/gate/RF288/geometry/setZLength 2.694000 cm
/gate/RF288/placement/setTranslation -9.676500 0 -1.653000 cm
/gate/RF288/vis/forceSolid
/gate/RF288/vis/setColor yellow
/gate/RF288/repeaters/insert linear
/gate/RF288/linear/setRepeatNumber 40
/gate/RF288/linear/setRepeatVector 5 0 0 mm
/gate/RF288/linear/autoCenter false
/gate/RF_box/daughters/name RF289
/gate/RF_box/daughters/insert box
/gate/RF289/setMaterial Aluminium
/gate/RF289/geometry/setXLength 0.001000 cm
/gate/RF289/geometry/setYLength 20 cm
/gate/RF289/geometry/setZLength 2.671000 cm
/gate/RF289/placement/setTranslation -9.675500 0 -1.664500 cm
/gate/RF289/vis/forceSolid
/gate/RF289/vis/setColor yellow
/gate/RF289/repeaters/insert linear
/gate/RF289/linear/setRepeatNumber 40
/gate/RF289/linear/setRepeatVector 5 0 0 mm
/gate/RF289/linear/autoCenter false
/gate/RF_box/daughters/name RF290
/gate/RF_box/daughters/insert box
/gate/RF290/setMaterial Aluminium
/gate/RF290/geometry/setXLength 0.001000 cm
/gate/RF290/geometry/setYLength 20 cm
/gate/RF290/geometry/setZLength 2.648000 cm
/gate/RF290/placement/setTranslation -9.674500 0 -1.676000 cm
/gate/RF290/vis/forceSolid
/gate/RF290/vis/setColor yellow
/gate/RF290/repeaters/insert linear
/gate/RF290/linear/setRepeatNumber 40
/gate/RF290/linear/setRepeatVector 5 0 0 mm
/gate/RF290/linear/autoCenter false
/gate/RF_box/daughters/name RF291
/gate/RF_box/daughters/insert box
/gate/RF291/setMaterial Aluminium
/gate/RF291/geometry/setXLength 0.001000 cm
/gate/RF291/geometry/setYLength 20 cm
/gate/RF291/geometry/setZLength 2.626000 cm
/gate/RF291/placement/setTranslation -9.673500 0 -1.687000 cm
/gate/RF291/vis/forceSolid
/gate/RF291/vis/setColor yellow
/gate/RF291/repeaters/insert linear
/gate/RF291/linear/setRepeatNumber 40
/gate/RF291/linear/setRepeatVector 5 0 0 mm
/gate/RF291/linear/autoCenter false
/gate/RF_box/daughters/name RF292
/gate/RF_box/daughters/insert box
/gate/RF292/setMaterial Aluminium
/gate/RF292/geometry/setXLength 0.001000 cm
/gate/RF292/geometry/setYLength 20 cm
/gate/RF292/geometry/setZLength 2.603000 cm
/gate/RF292/placement/setTranslation -9.672500 0 -1.698500 cm
/gate/RF292/vis/forceSolid
/gate/RF292/vis/setColor yellow
/gate/RF292/repeaters/insert linear
/gate/RF292/linear/setRepeatNumber 40
/gate/RF292/linear/setRepeatVector 5 0 0 mm
/gate/RF292/linear/autoCenter false
/gate/RF_box/daughters/name RF293
/gate/RF_box/daughters/insert box
/gate/RF293/setMaterial Aluminium
/gate/RF293/geometry/setXLength 0.001000 cm
/gate/RF293/geometry/setYLength 20 cm
/gate/RF293/geometry/setZLength 2.580000 cm
/gate/RF293/placement/setTranslation -9.671500 0 -1.710000 cm
/gate/RF293/vis/forceSolid
/gate/RF293/vis/setColor yellow
/gate/RF293/repeaters/insert linear
/gate/RF293/linear/setRepeatNumber 40
/gate/RF293/linear/setRepeatVector 5 0 0 mm
/gate/RF293/linear/autoCenter false
/gate/RF_box/daughters/name RF294
/gate/RF_box/daughters/insert box
/gate/RF294/setMaterial Aluminium
/gate/RF294/geometry/setXLength 0.001000 cm
/gate/RF294/geometry/setYLength 20 cm
/gate/RF294/geometry/setZLength 2.558000 cm
/gate/RF294/placement/setTranslation -9.670500 0 -1.721000 cm
/gate/RF294/vis/forceSolid
/gate/RF294/vis/setColor yellow
/gate/RF294/repeaters/insert linear
/gate/RF294/linear/setRepeatNumber 40
/gate/RF294/linear/setRepeatVector 5 0 0 mm
/gate/RF294/linear/autoCenter false
/gate/RF_box/daughters/name RF295
/gate/RF_box/daughters/insert box
/gate/RF295/setMaterial Aluminium
/gate/RF295/geometry/setXLength 0.001000 cm
/gate/RF295/geometry/setYLength 20 cm
/gate/RF295/geometry/setZLength 2.535000 cm
/gate/RF295/placement/setTranslation -9.669500 0 -1.732500 cm
/gate/RF295/vis/forceSolid
/gate/RF295/vis/setColor yellow
/gate/RF295/repeaters/insert linear
/gate/RF295/linear/setRepeatNumber 40
/gate/RF295/linear/setRepeatVector 5 0 0 mm
/gate/RF295/linear/autoCenter false
/gate/RF_box/daughters/name RF297
/gate/RF_box/daughters/insert box
/gate/RF297/setMaterial Aluminium
/gate/RF297/geometry/setXLength 0.001000 cm
/gate/RF297/geometry/setYLength 20 cm
/gate/RF297/geometry/setZLength 2.490000 cm
/gate/RF297/placement/setTranslation -9.668500 0 -1.755000 cm
/gate/RF297/vis/forceSolid
/gate/RF297/vis/setColor yellow
/gate/RF297/repeaters/insert linear
/gate/RF297/linear/setRepeatNumber 40
/gate/RF297/linear/setRepeatVector 5 0 0 mm
/gate/RF297/linear/autoCenter false
/gate/RF_box/daughters/name RF298
/gate/RF_box/daughters/insert box
/gate/RF298/setMaterial Aluminium
/gate/RF298/geometry/setXLength 0.001000 cm
/gate/RF298/geometry/setYLength 20 cm
/gate/RF298/geometry/setZLength 2.467000 cm
/gate/RF298/placement/setTranslation -9.667500 0 -1.766500 cm
/gate/RF298/vis/forceSolid
/gate/RF298/vis/setColor yellow
/gate/RF298/repeaters/insert linear
/gate/RF298/linear/setRepeatNumber 40
/gate/RF298/linear/setRepeatVector 5 0 0 mm
/gate/RF298/linear/autoCenter false
/gate/RF_box/daughters/name RF299
/gate/RF_box/daughters/insert box
/gate/RF299/setMaterial Aluminium
/gate/RF299/geometry/setXLength 0.001000 cm
/gate/RF299/geometry/setYLength 20 cm
/gate/RF299/geometry/setZLength 2.445000 cm
/gate/RF299/placement/setTranslation -9.666500 0 -1.777500 cm
/gate/RF299/vis/forceSolid
/gate/RF299/vis/setColor yellow
/gate/RF299/repeaters/insert linear
/gate/RF299/linear/setRepeatNumber 40
/gate/RF299/linear/setRepeatVector 5 0 0 mm
/gate/RF299/linear/autoCenter false
/gate/RF_box/daughters/name RF300
/gate/RF_box/daughters/insert box
/gate/RF300/setMaterial Aluminium
/gate/RF300/geometry/setXLength 0.001000 cm
/gate/RF300/geometry/setYLength 20 cm
/gate/RF300/geometry/setZLength 2.422000 cm
/gate/RF300/placement/setTranslation -9.665500 0 -1.789000 cm
/gate/RF300/vis/forceSolid
/gate/RF300/vis/setColor yellow
/gate/RF300/repeaters/insert linear
/gate/RF300/linear/setRepeatNumber 40
/gate/RF300/linear/setRepeatVector 5 0 0 mm
/gate/RF300/linear/autoCenter false
/gate/RF_box/daughters/name RF301
/gate/RF_box/daughters/insert box
/gate/RF301/setMaterial Aluminium
/gate/RF301/geometry/setXLength 0.001000 cm
/gate/RF301/geometry/setYLength 20 cm
/gate/RF301/geometry/setZLength 2.399000 cm
/gate/RF301/placement/setTranslation -9.664500 0 -1.800500 cm
/gate/RF301/vis/forceSolid
/gate/RF301/vis/setColor yellow
/gate/RF301/repeaters/insert linear
/gate/RF301/linear/setRepeatNumber 40
/gate/RF301/linear/setRepeatVector 5 0 0 mm
/gate/RF301/linear/autoCenter false
/gate/RF_box/daughters/name RF302
/gate/RF_box/daughters/insert box
/gate/RF302/setMaterial Aluminium
/gate/RF302/geometry/setXLength 0.001000 cm
/gate/RF302/geometry/setYLength 20 cm
/gate/RF302/geometry/setZLength 2.377000 cm
/gate/RF302/placement/setTranslation -9.663500 0 -1.811500 cm
/gate/RF302/vis/forceSolid
/gate/RF302/vis/setColor yellow
/gate/RF302/repeaters/insert linear
/gate/RF302/linear/setRepeatNumber 40
/gate/RF302/linear/setRepeatVector 5 0 0 mm
/gate/RF302/linear/autoCenter false
/gate/RF_box/daughters/name RF303
/gate/RF_box/daughters/insert box
/gate/RF303/setMaterial Aluminium
/gate/RF303/geometry/setXLength 0.001000 cm
/gate/RF303/geometry/setYLength 20 cm
/gate/RF303/geometry/setZLength 2.354000 cm
/gate/RF303/placement/setTranslation -9.662500 0 -1.823000 cm
/gate/RF303/vis/forceSolid
/gate/RF303/vis/setColor yellow
/gate/RF303/repeaters/insert linear
/gate/RF303/linear/setRepeatNumber 40
/gate/RF303/linear/setRepeatVector 5 0 0 mm
/gate/RF303/linear/autoCenter false
/gate/RF_box/daughters/name RF304
/gate/RF_box/daughters/insert box
/gate/RF304/setMaterial Aluminium
/gate/RF304/geometry/setXLength 0.001000 cm
/gate/RF304/geometry/setYLength 20 cm
/gate/RF304/geometry/setZLength 2.331000 cm
/gate/RF304/placement/setTranslation -9.661500 0 -1.834500 cm
/gate/RF304/vis/forceSolid
/gate/RF304/vis/setColor yellow
/gate/RF304/repeaters/insert linear
/gate/RF304/linear/setRepeatNumber 40
/gate/RF304/linear/setRepeatVector 5 0 0 mm
/gate/RF304/linear/autoCenter false
/gate/RF_box/daughters/name RF305
/gate/RF_box/daughters/insert box
/gate/RF305/setMaterial Aluminium
/gate/RF305/geometry/setXLength 0.001000 cm
/gate/RF305/geometry/setYLength 20 cm
/gate/RF305/geometry/setZLength 2.309000 cm
/gate/RF305/placement/setTranslation -9.660500 0 -1.845500 cm
/gate/RF305/vis/forceSolid
/gate/RF305/vis/setColor yellow
/gate/RF305/repeaters/insert linear
/gate/RF305/linear/setRepeatNumber 40
/gate/RF305/linear/setRepeatVector 5 0 0 mm
/gate/RF305/linear/autoCenter false
/gate/RF_box/daughters/name RF306
/gate/RF_box/daughters/insert box
/gate/RF306/setMaterial Aluminium
/gate/RF306/geometry/setXLength 0.001000 cm
/gate/RF306/geometry/setYLength 20 cm
/gate/RF306/geometry/setZLength 2.286000 cm
/gate/RF306/placement/setTranslation -9.659500 0 -1.857000 cm
/gate/RF306/vis/forceSolid
/gate/RF306/vis/setColor yellow
/gate/RF306/repeaters/insert linear
/gate/RF306/linear/setRepeatNumber 40
/gate/RF306/linear/setRepeatVector 5 0 0 mm
/gate/RF306/linear/autoCenter false
/gate/RF_box/daughters/name RF307
/gate/RF_box/daughters/insert box
/gate/RF307/setMaterial Aluminium
/gate/RF307/geometry/setXLength 0.001000 cm
/gate/RF307/geometry/setYLength 20 cm
/gate/RF307/geometry/setZLength 2.263000 cm
/gate/RF307/placement/setTranslation -9.658500 0 -1.868500 cm
/gate/RF307/vis/forceSolid
/gate/RF307/vis/setColor yellow
/gate/RF307/repeaters/insert linear
/gate/RF307/linear/setRepeatNumber 40
/gate/RF307/linear/setRepeatVector 5 0 0 mm
/gate/RF307/linear/autoCenter false
/gate/RF_box/daughters/name RF308
/gate/RF_box/daughters/insert box
/gate/RF308/setMaterial Aluminium
/gate/RF308/geometry/setXLength 0.001000 cm
/gate/RF308/geometry/setYLength 20 cm
/gate/RF308/geometry/setZLength 2.241000 cm
/gate/RF308/placement/setTranslation -9.657500 0 -1.879500 cm
/gate/RF308/vis/forceSolid
/gate/RF308/vis/setColor yellow
/gate/RF308/repeaters/insert linear
/gate/RF308/linear/setRepeatNumber 40
/gate/RF308/linear/setRepeatVector 5 0 0 mm
/gate/RF308/linear/autoCenter false
/gate/RF_box/daughters/name RF309
/gate/RF_box/daughters/insert box
/gate/RF309/setMaterial Aluminium
/gate/RF309/geometry/setXLength 0.001000 cm
/gate/RF309/geometry/setYLength 20 cm
/gate/RF309/geometry/setZLength 2.218000 cm
/gate/RF309/placement/setTranslation -9.656500 0 -1.891000 cm
/gate/RF309/vis/forceSolid
/gate/RF309/vis/setColor yellow
/gate/RF309/repeaters/insert linear
/gate/RF309/linear/setRepeatNumber 40
/gate/RF309/linear/setRepeatVector 5 0 0 mm
/gate/RF309/linear/autoCenter false
/gate/RF_box/daughters/name RF310
/gate/RF_box/daughters/insert box
/gate/RF310/setMaterial Aluminium
/gate/RF310/geometry/setXLength 0.001000 cm
/gate/RF310/geometry/setYLength 20 cm
/gate/RF310/geometry/setZLength 2.196000 cm
/gate/RF310/placement/setTranslation -9.655500 0 -1.902000 cm
/gate/RF310/vis/forceSolid
/gate/RF310/vis/setColor yellow
/gate/RF310/repeaters/insert linear
/gate/RF310/linear/setRepeatNumber 40
/gate/RF310/linear/setRepeatVector 5 0 0 mm
/gate/RF310/linear/autoCenter false
/gate/RF_box/daughters/name RF311
/gate/RF_box/daughters/insert box
/gate/RF311/setMaterial Aluminium
/gate/RF311/geometry/setXLength 0.001000 cm
/gate/RF311/geometry/setYLength 20 cm
/gate/RF311/geometry/setZLength 2.173000 cm
/gate/RF311/placement/setTranslation -9.654500 0 -1.913500 cm
/gate/RF311/vis/forceSolid
/gate/RF311/vis/setColor yellow
/gate/RF311/repeaters/insert linear
/gate/RF311/linear/setRepeatNumber 40
/gate/RF311/linear/setRepeatVector 5 0 0 mm
/gate/RF311/linear/autoCenter false
/gate/RF_box/daughters/name RF312
/gate/RF_box/daughters/insert box
/gate/RF312/setMaterial Aluminium
/gate/RF312/geometry/setXLength 0.001000 cm
/gate/RF312/geometry/setYLength 20 cm
/gate/RF312/geometry/setZLength 2.150000 cm
/gate/RF312/placement/setTranslation -9.653500 0 -1.925000 cm
/gate/RF312/vis/forceSolid
/gate/RF312/vis/setColor yellow
/gate/RF312/repeaters/insert linear
/gate/RF312/linear/setRepeatNumber 40
/gate/RF312/linear/setRepeatVector 5 0 0 mm
/gate/RF312/linear/autoCenter false
/gate/RF_box/daughters/name RF313
/gate/RF_box/daughters/insert box
/gate/RF313/setMaterial Aluminium
/gate/RF313/geometry/setXLength 0.001000 cm
/gate/RF313/geometry/setYLength 20 cm
/gate/RF313/geometry/setZLength 2.128000 cm
/gate/RF313/placement/setTranslation -9.652500 0 -1.936000 cm
/gate/RF313/vis/forceSolid
/gate/RF313/vis/setColor yellow
/gate/RF313/repeaters/insert linear
/gate/RF313/linear/setRepeatNumber 40
/gate/RF313/linear/setRepeatVector 5 0 0 mm
/gate/RF313/linear/autoCenter false
/gate/RF_box/daughters/name RF314
/gate/RF_box/daughters/insert box
/gate/RF314/setMaterial Aluminium
/gate/RF314/geometry/setXLength 0.001000 cm
/gate/RF314/geometry/setYLength 20 cm
/gate/RF314/geometry/setZLength 2.105000 cm
/gate/RF314/placement/setTranslation -9.651500 0 -1.947500 cm
/gate/RF314/vis/forceSolid
/gate/RF314/vis/setColor yellow
/gate/RF314/repeaters/insert linear
/gate/RF314/linear/setRepeatNumber 40
/gate/RF314/linear/setRepeatVector 5 0 0 mm
/gate/RF314/linear/autoCenter false
/gate/RF_box/daughters/name RF315
/gate/RF_box/daughters/insert box
/gate/RF315/setMaterial Aluminium
/gate/RF315/geometry/setXLength 0.001000 cm
/gate/RF315/geometry/setYLength 20 cm
/gate/RF315/geometry/setZLength 2.082000 cm
/gate/RF315/placement/setTranslation -9.650500 0 -1.959000 cm
/gate/RF315/vis/forceSolid
/gate/RF315/vis/setColor yellow
/gate/RF315/repeaters/insert linear
/gate/RF315/linear/setRepeatNumber 40
/gate/RF315/linear/setRepeatVector 5 0 0 mm
/gate/RF315/linear/autoCenter false
/gate/RF_box/daughters/name RF316
/gate/RF_box/daughters/insert box
/gate/RF316/setMaterial Aluminium
/gate/RF316/geometry/setXLength 0.001000 cm
/gate/RF316/geometry/setYLength 20 cm
/gate/RF316/geometry/setZLength 2.060000 cm
/gate/RF316/placement/setTranslation -9.649500 0 -1.970000 cm
/gate/RF316/vis/forceSolid
/gate/RF316/vis/setColor yellow
/gate/RF316/repeaters/insert linear
/gate/RF316/linear/setRepeatNumber 40
/gate/RF316/linear/setRepeatVector 5 0 0 mm
/gate/RF316/linear/autoCenter false
/gate/RF_box/daughters/name RF317
/gate/RF_box/daughters/insert box
/gate/RF317/setMaterial Aluminium
/gate/RF317/geometry/setXLength 0.001000 cm
/gate/RF317/geometry/setYLength 20 cm
/gate/RF317/geometry/setZLength 2.037000 cm
/gate/RF317/placement/setTranslation -9.648500 0 -1.981500 cm
/gate/RF317/vis/forceSolid
/gate/RF317/vis/setColor yellow
/gate/RF317/repeaters/insert linear
/gate/RF317/linear/setRepeatNumber 40
/gate/RF317/linear/setRepeatVector 5 0 0 mm
/gate/RF317/linear/autoCenter false
/gate/RF_box/daughters/name RF318
/gate/RF_box/daughters/insert box
/gate/RF318/setMaterial Aluminium
/gate/RF318/geometry/setXLength 0.001000 cm
/gate/RF318/geometry/setYLength 20 cm
/gate/RF318/geometry/setZLength 2.014000 cm
/gate/RF318/placement/setTranslation -9.647500 0 -1.993000 cm
/gate/RF318/vis/forceSolid
/gate/RF318/vis/setColor yellow
/gate/RF318/repeaters/insert linear
/gate/RF318/linear/setRepeatNumber 40
/gate/RF318/linear/setRepeatVector 5 0 0 mm
/gate/RF318/linear/autoCenter false
/gate/RF_box/daughters/name RF319
/gate/RF_box/daughters/insert box
/gate/RF319/setMaterial Aluminium
/gate/RF319/geometry/setXLength 0.001000 cm
/gate/RF319/geometry/setYLength 20 cm
/gate/RF319/geometry/setZLength 1.992000 cm
/gate/RF319/placement/setTranslation -9.646500 0 -2.004000 cm
/gate/RF319/vis/forceSolid
/gate/RF319/vis/setColor yellow
/gate/RF319/repeaters/insert linear
/gate/RF319/linear/setRepeatNumber 40
/gate/RF319/linear/setRepeatVector 5 0 0 mm
/gate/RF319/linear/autoCenter false
/gate/RF_box/daughters/name RF320
/gate/RF_box/daughters/insert box
/gate/RF320/setMaterial Aluminium
/gate/RF320/geometry/setXLength 0.001000 cm
/gate/RF320/geometry/setYLength 20 cm
/gate/RF320/geometry/setZLength 1.969000 cm
/gate/RF320/placement/setTranslation -9.645500 0 -2.015500 cm
/gate/RF320/vis/forceSolid
/gate/RF320/vis/setColor yellow
/gate/RF320/repeaters/insert linear
/gate/RF320/linear/setRepeatNumber 40
/gate/RF320/linear/setRepeatVector 5 0 0 mm
/gate/RF320/linear/autoCenter false
/gate/RF_box/daughters/name RF321
/gate/RF_box/daughters/insert box
/gate/RF321/setMaterial Aluminium
/gate/RF321/geometry/setXLength 0.001000 cm
/gate/RF321/geometry/setYLength 20 cm
/gate/RF321/geometry/setZLength 1.947000 cm
/gate/RF321/placement/setTranslation -9.644500 0 -2.026500 cm
/gate/RF321/vis/forceSolid
/gate/RF321/vis/setColor yellow
/gate/RF321/repeaters/insert linear
/gate/RF321/linear/setRepeatNumber 40
/gate/RF321/linear/setRepeatVector 5 0 0 mm
/gate/RF321/linear/autoCenter false
/gate/RF_box/daughters/name RF322
/gate/RF_box/daughters/insert box
/gate/RF322/setMaterial Aluminium
/gate/RF322/geometry/setXLength 0.001000 cm
/gate/RF322/geometry/setYLength 20 cm
/gate/RF322/geometry/setZLength 1.924000 cm
/gate/RF322/placement/setTranslation -9.643500 0 -2.038000 cm
/gate/RF322/vis/forceSolid
/gate/RF322/vis/setColor yellow
/gate/RF322/repeaters/insert linear
/gate/RF322/linear/setRepeatNumber 40
/gate/RF322/linear/setRepeatVector 5 0 0 mm
/gate/RF322/linear/autoCenter false
/gate/RF_box/daughters/name RF323
/gate/RF_box/daughters/insert box
/gate/RF323/setMaterial Aluminium
/gate/RF323/geometry/setXLength 0.001000 cm
/gate/RF323/geometry/setYLength 20 cm
/gate/RF323/geometry/setZLength 1.901000 cm
/gate/RF323/placement/setTranslation -9.642500 0 -2.049500 cm
/gate/RF323/vis/forceSolid
/gate/RF323/vis/setColor yellow
/gate/RF323/repeaters/insert linear
/gate/RF323/linear/setRepeatNumber 40
/gate/RF323/linear/setRepeatVector 5 0 0 mm
/gate/RF323/linear/autoCenter false
/gate/RF_box/daughters/name RF324
/gate/RF_box/daughters/insert box
/gate/RF324/setMaterial Aluminium
/gate/RF324/geometry/setXLength 0.001000 cm
/gate/RF324/geometry/setYLength 20 cm
/gate/RF324/geometry/setZLength 1.879000 cm
/gate/RF324/placement/setTranslation -9.641500 0 -2.060500 cm
/gate/RF324/vis/forceSolid
/gate/RF324/vis/setColor yellow
/gate/RF324/repeaters/insert linear
/gate/RF324/linear/setRepeatNumber 40
/gate/RF324/linear/setRepeatVector 5 0 0 mm
/gate/RF324/linear/autoCenter false
/gate/RF_box/daughters/name RF325
/gate/RF_box/daughters/insert box
/gate/RF325/setMaterial Aluminium
/gate/RF325/geometry/setXLength 0.001000 cm
/gate/RF325/geometry/setYLength 20 cm
/gate/RF325/geometry/setZLength 1.856000 cm
/gate/RF325/placement/setTranslation -9.640500 0 -2.072000 cm
/gate/RF325/vis/forceSolid
/gate/RF325/vis/setColor yellow
/gate/RF325/repeaters/insert linear
/gate/RF325/linear/setRepeatNumber 40
/gate/RF325/linear/setRepeatVector 5 0 0 mm
/gate/RF325/linear/autoCenter false
/gate/RF_box/daughters/name RF326
/gate/RF_box/daughters/insert box
/gate/RF326/setMaterial Aluminium
/gate/RF326/geometry/setXLength 0.001000 cm
/gate/RF326/geometry/setYLength 20 cm
/gate/RF326/geometry/setZLength 1.833000 cm
/gate/RF326/placement/setTranslation -9.639500 0 -2.083500 cm
/gate/RF326/vis/forceSolid
/gate/RF326/vis/setColor yellow
/gate/RF326/repeaters/insert linear
/gate/RF326/linear/setRepeatNumber 40
/gate/RF326/linear/setRepeatVector 5 0 0 mm
/gate/RF326/linear/autoCenter false
/gate/RF_box/daughters/name RF327
/gate/RF_box/daughters/insert box
/gate/RF327/setMaterial Aluminium
/gate/RF327/geometry/setXLength 0.001000 cm
/gate/RF327/geometry/setYLength 20 cm
/gate/RF327/geometry/setZLength 1.811000 cm
/gate/RF327/placement/setTranslation -9.638500 0 -2.094500 cm
/gate/RF327/vis/forceSolid
/gate/RF327/vis/setColor yellow
/gate/RF327/repeaters/insert linear
/gate/RF327/linear/setRepeatNumber 40
/gate/RF327/linear/setRepeatVector 5 0 0 mm
/gate/RF327/linear/autoCenter false
/gate/RF_box/daughters/name RF328
/gate/RF_box/daughters/insert box
/gate/RF328/setMaterial Aluminium
/gate/RF328/geometry/setXLength 0.001000 cm
/gate/RF328/geometry/setYLength 20 cm
/gate/RF328/geometry/setZLength 1.788000 cm
/gate/RF328/placement/setTranslation -9.637500 0 -2.106000 cm
/gate/RF328/vis/forceSolid
/gate/RF328/vis/setColor yellow
/gate/RF328/repeaters/insert linear
/gate/RF328/linear/setRepeatNumber 40
/gate/RF328/linear/setRepeatVector 5 0 0 mm
/gate/RF328/linear/autoCenter false
/gate/RF_box/daughters/name RF329
/gate/RF_box/daughters/insert box
/gate/RF329/setMaterial Aluminium
/gate/RF329/geometry/setXLength 0.001000 cm
/gate/RF329/geometry/setYLength 20 cm
/gate/RF329/geometry/setZLength 1.766000 cm
/gate/RF329/placement/setTranslation -9.636500 0 -2.117000 cm
/gate/RF329/vis/forceSolid
/gate/RF329/vis/setColor yellow
/gate/RF329/repeaters/insert linear
/gate/RF329/linear/setRepeatNumber 40
/gate/RF329/linear/setRepeatVector 5 0 0 mm
/gate/RF329/linear/autoCenter false
/gate/RF_box/daughters/name RF330
/gate/RF_box/daughters/insert box
/gate/RF330/setMaterial Aluminium
/gate/RF330/geometry/setXLength 0.001000 cm
/gate/RF330/geometry/setYLength 20 cm
/gate/RF330/geometry/setZLength 1.743000 cm
/gate/RF330/placement/setTranslation -9.635500 0 -2.128500 cm
/gate/RF330/vis/forceSolid
/gate/RF330/vis/setColor yellow
/gate/RF330/repeaters/insert linear
/gate/RF330/linear/setRepeatNumber 40
/gate/RF330/linear/setRepeatVector 5 0 0 mm
/gate/RF330/linear/autoCenter false
/gate/RF_box/daughters/name RF331
/gate/RF_box/daughters/insert box
/gate/RF331/setMaterial Aluminium
/gate/RF331/geometry/setXLength 0.002000 cm
/gate/RF331/geometry/setYLength 20 cm
/gate/RF331/geometry/setZLength 1.720000 cm
/gate/RF331/placement/setTranslation -9.634000 0 -2.140000 cm
/gate/RF331/vis/forceSolid
/gate/RF331/vis/setColor yellow
/gate/RF331/repeaters/insert linear
/gate/RF331/linear/setRepeatNumber 40
/gate/RF331/linear/setRepeatVector 5 0 0 mm
/gate/RF331/linear/autoCenter false
/gate/RF_box/daughters/name RF332
/gate/RF_box/daughters/insert box
/gate/RF332/setMaterial Aluminium
/gate/RF332/geometry/setXLength 0.001000 cm
/gate/RF332/geometry/setYLength 20 cm
/gate/RF332/geometry/setZLength 1.698000 cm
/gate/RF332/placement/setTranslation -9.632500 0 -2.151000 cm
/gate/RF332/vis/forceSolid
/gate/RF332/vis/setColor yellow
/gate/RF332/repeaters/insert linear
/gate/RF332/linear/setRepeatNumber 40
/gate/RF332/linear/setRepeatVector 5 0 0 mm
/gate/RF332/linear/autoCenter false
/gate/RF_box/daughters/name RF333
/gate/RF_box/daughters/insert box
/gate/RF333/setMaterial Aluminium
/gate/RF333/geometry/setXLength 0.001000 cm
/gate/RF333/geometry/setYLength 20 cm
/gate/RF333/geometry/setZLength 1.675000 cm
/gate/RF333/placement/setTranslation -9.631500 0 -2.162500 cm
/gate/RF333/vis/forceSolid
/gate/RF333/vis/setColor yellow
/gate/RF333/repeaters/insert linear
/gate/RF333/linear/setRepeatNumber 40
/gate/RF333/linear/setRepeatVector 5 0 0 mm
/gate/RF333/linear/autoCenter false
/gate/RF_box/daughters/name RF334
/gate/RF_box/daughters/insert box
/gate/RF334/setMaterial Aluminium
/gate/RF334/geometry/setXLength 0.001000 cm
/gate/RF334/geometry/setYLength 20 cm
/gate/RF334/geometry/setZLength 1.652000 cm
/gate/RF334/placement/setTranslation -9.630500 0 -2.174000 cm
/gate/RF334/vis/forceSolid
/gate/RF334/vis/setColor yellow
/gate/RF334/repeaters/insert linear
/gate/RF334/linear/setRepeatNumber 40
/gate/RF334/linear/setRepeatVector 5 0 0 mm
/gate/RF334/linear/autoCenter false
/gate/RF_box/daughters/name RF335
/gate/RF_box/daughters/insert box
/gate/RF335/setMaterial Aluminium
/gate/RF335/geometry/setXLength 0.001000 cm
/gate/RF335/geometry/setYLength 20 cm
/gate/RF335/geometry/setZLength 1.630000 cm
/gate/RF335/placement/setTranslation -9.629500 0 -2.185000 cm
/gate/RF335/vis/forceSolid
/gate/RF335/vis/setColor yellow
/gate/RF335/repeaters/insert linear
/gate/RF335/linear/setRepeatNumber 40
/gate/RF335/linear/setRepeatVector 5 0 0 mm
/gate/RF335/linear/autoCenter false
/gate/RF_box/daughters/name RF336
/gate/RF_box/daughters/insert box
/gate/RF336/setMaterial Aluminium
/gate/RF336/geometry/setXLength 0.001000 cm
/gate/RF336/geometry/setYLength 20 cm
/gate/RF336/geometry/setZLength 1.607000 cm
/gate/RF336/placement/setTranslation -9.628500 0 -2.196500 cm
/gate/RF336/vis/forceSolid
/gate/RF336/vis/setColor yellow
/gate/RF336/repeaters/insert linear
/gate/RF336/linear/setRepeatNumber 40
/gate/RF336/linear/setRepeatVector 5 0 0 mm
/gate/RF336/linear/autoCenter false
/gate/RF_box/daughters/name RF337
/gate/RF_box/daughters/insert box
/gate/RF337/setMaterial Aluminium
/gate/RF337/geometry/setXLength 0.001000 cm
/gate/RF337/geometry/setYLength 20 cm
/gate/RF337/geometry/setZLength 1.584000 cm
/gate/RF337/placement/setTranslation -9.627500 0 -2.208000 cm
/gate/RF337/vis/forceSolid
/gate/RF337/vis/setColor yellow
/gate/RF337/repeaters/insert linear
/gate/RF337/linear/setRepeatNumber 40
/gate/RF337/linear/setRepeatVector 5 0 0 mm
/gate/RF337/linear/autoCenter false
/gate/RF_box/daughters/name RF338
/gate/RF_box/daughters/insert box
/gate/RF338/setMaterial Aluminium
/gate/RF338/geometry/setXLength 0.001000 cm
/gate/RF338/geometry/setYLength 20 cm
/gate/RF338/geometry/setZLength 1.562000 cm
/gate/RF338/placement/setTranslation -9.626500 0 -2.219000 cm
/gate/RF338/vis/forceSolid
/gate/RF338/vis/setColor yellow
/gate/RF338/repeaters/insert linear
/gate/RF338/linear/setRepeatNumber 40
/gate/RF338/linear/setRepeatVector 5 0 0 mm
/gate/RF338/linear/autoCenter false
/gate/RF_box/daughters/name RF339
/gate/RF_box/daughters/insert box
/gate/RF339/setMaterial Aluminium
/gate/RF339/geometry/setXLength 0.001000 cm
/gate/RF339/geometry/setYLength 20 cm
/gate/RF339/geometry/setZLength 1.539000 cm
/gate/RF339/placement/setTranslation -9.625500 0 -2.230500 cm
/gate/RF339/vis/forceSolid
/gate/RF339/vis/setColor yellow
/gate/RF339/repeaters/insert linear
/gate/RF339/linear/setRepeatNumber 40
/gate/RF339/linear/setRepeatVector 5 0 0 mm
/gate/RF339/linear/autoCenter false
/gate/RF_box/daughters/name RF340
/gate/RF_box/daughters/insert box
/gate/RF340/setMaterial Aluminium
/gate/RF340/geometry/setXLength 0.001000 cm
/gate/RF340/geometry/setYLength 20 cm
/gate/RF340/geometry/setZLength 1.517000 cm
/gate/RF340/placement/setTranslation -9.624500 0 -2.241500 cm
/gate/RF340/vis/forceSolid
/gate/RF340/vis/setColor yellow
/gate/RF340/repeaters/insert linear
/gate/RF340/linear/setRepeatNumber 40
/gate/RF340/linear/setRepeatVector 5 0 0 mm
/gate/RF340/linear/autoCenter false
/gate/RF_box/daughters/name RF341
/gate/RF_box/daughters/insert box
/gate/RF341/setMaterial Aluminium
/gate/RF341/geometry/setXLength 0.001000 cm
/gate/RF341/geometry/setYLength 20 cm
/gate/RF341/geometry/setZLength 1.494000 cm
/gate/RF341/placement/setTranslation -9.623500 0 -2.253000 cm
/gate/RF341/vis/forceSolid
/gate/RF341/vis/setColor yellow
/gate/RF341/repeaters/insert linear
/gate/RF341/linear/setRepeatNumber 40
/gate/RF341/linear/setRepeatVector 5 0 0 mm
/gate/RF341/linear/autoCenter false
/gate/RF_box/daughters/name RF342
/gate/RF_box/daughters/insert box
/gate/RF342/setMaterial Aluminium
/gate/RF342/geometry/setXLength 0.002000 cm
/gate/RF342/geometry/setYLength 20 cm
/gate/RF342/geometry/setZLength 1.471000 cm
/gate/RF342/placement/setTranslation -9.622000 0 -2.264500 cm
/gate/RF342/vis/forceSolid
/gate/RF342/vis/setColor yellow
/gate/RF342/repeaters/insert linear
/gate/RF342/linear/setRepeatNumber 40
/gate/RF342/linear/setRepeatVector 5 0 0 mm
/gate/RF342/linear/autoCenter false
/gate/RF_box/daughters/name RF343
/gate/RF_box/daughters/insert box
/gate/RF343/setMaterial Aluminium
/gate/RF343/geometry/setXLength 0.001000 cm
/gate/RF343/geometry/setYLength 20 cm
/gate/RF343/geometry/setZLength 1.449000 cm
/gate/RF343/placement/setTranslation -9.620500 0 -2.275500 cm
/gate/RF343/vis/forceSolid
/gate/RF343/vis/setColor yellow
/gate/RF343/repeaters/insert linear
/gate/RF343/linear/setRepeatNumber 40
/gate/RF343/linear/setRepeatVector 5 0 0 mm
/gate/RF343/linear/autoCenter false
/gate/RF_box/daughters/name RF344
/gate/RF_box/daughters/insert box
/gate/RF344/setMaterial Aluminium
/gate/RF344/geometry/setXLength 0.001000 cm
/gate/RF344/geometry/setYLength 20 cm
/gate/RF344/geometry/setZLength 1.426000 cm
/gate/RF344/placement/setTranslation -9.619500 0 -2.287000 cm
/gate/RF344/vis/forceSolid
/gate/RF344/vis/setColor yellow
/gate/RF344/repeaters/insert linear
/gate/RF344/linear/setRepeatNumber 40
/gate/RF344/linear/setRepeatVector 5 0 0 mm
/gate/RF344/linear/autoCenter false
/gate/RF_box/daughters/name RF345
/gate/RF_box/daughters/insert box
/gate/RF345/setMaterial Aluminium
/gate/RF345/geometry/setXLength 0.001000 cm
/gate/RF345/geometry/setYLength 20 cm
/gate/RF345/geometry/setZLength 1.403000 cm
/gate/RF345/placement/setTranslation -9.618500 0 -2.298500 cm
/gate/RF345/vis/forceSolid
/gate/RF345/vis/setColor yellow
/gate/RF345/repeaters/insert linear
/gate/RF345/linear/setRepeatNumber 40
/gate/RF345/linear/setRepeatVector 5 0 0 mm
/gate/RF345/linear/autoCenter false
/gate/RF_box/daughters/name RF346
/gate/RF_box/daughters/insert box
/gate/RF346/setMaterial Aluminium
/gate/RF346/geometry/setXLength 0.001000 cm
/gate/RF346/geometry/setYLength 20 cm
/gate/RF346/geometry/setZLength 1.381000 cm
/gate/RF346/placement/setTranslation -9.617500 0 -2.309500 cm
/gate/RF346/vis/forceSolid
/gate/RF346/vis/setColor yellow
/gate/RF346/repeaters/insert linear
/gate/RF346/linear/setRepeatNumber 40
/gate/RF346/linear/setRepeatVector 5 0 0 mm
/gate/RF346/linear/autoCenter false
/gate/RF_box/daughters/name RF347
/gate/RF_box/daughters/insert box
/gate/RF347/setMaterial Aluminium
/gate/RF347/geometry/setXLength 0.001000 cm
/gate/RF347/geometry/setYLength 20 cm
/gate/RF347/geometry/setZLength 1.358000 cm
/gate/RF347/placement/setTranslation -9.616500 0 -2.321000 cm
/gate/RF347/vis/forceSolid
/gate/RF347/vis/setColor yellow
/gate/RF347/repeaters/insert linear
/gate/RF347/linear/setRepeatNumber 40
/gate/RF347/linear/setRepeatVector 5 0 0 mm
/gate/RF347/linear/autoCenter false
/gate/RF_box/daughters/name RF348
/gate/RF_box/daughters/insert box
/gate/RF348/setMaterial Aluminium
/gate/RF348/geometry/setXLength 0.002000 cm
/gate/RF348/geometry/setYLength 20 cm
/gate/RF348/geometry/setZLength 1.335000 cm
/gate/RF348/placement/setTranslation -9.615000 0 -2.332500 cm
/gate/RF348/vis/forceSolid
/gate/RF348/vis/setColor yellow
/gate/RF348/repeaters/insert linear
/gate/RF348/linear/setRepeatNumber 40
/gate/RF348/linear/setRepeatVector 5 0 0 mm
/gate/RF348/linear/autoCenter false
/gate/RF_box/daughters/name RF349
/gate/RF_box/daughters/insert box
/gate/RF349/setMaterial Aluminium
/gate/RF349/geometry/setXLength 0.001000 cm
/gate/RF349/geometry/setYLength 20 cm
/gate/RF349/geometry/setZLength 1.313000 cm
/gate/RF349/placement/setTranslation -9.613500 0 -2.343500 cm
/gate/RF349/vis/forceSolid
/gate/RF349/vis/setColor yellow
/gate/RF349/repeaters/insert linear
/gate/RF349/linear/setRepeatNumber 40
/gate/RF349/linear/setRepeatVector 5 0 0 mm
/gate/RF349/linear/autoCenter false
/gate/RF_box/daughters/name RF350
/gate/RF_box/daughters/insert box
/gate/RF350/setMaterial Aluminium
/gate/RF350/geometry/setXLength 0.001000 cm
/gate/RF350/geometry/setYLength 20 cm
/gate/RF350/geometry/setZLength 1.290000 cm
/gate/RF350/placement/setTranslation -9.612500 0 -2.355000 cm
/gate/RF350/vis/forceSolid
/gate/RF350/vis/setColor yellow
/gate/RF350/repeaters/insert linear
/gate/RF350/linear/setRepeatNumber 40
/gate/RF350/linear/setRepeatVector 5 0 0 mm
/gate/RF350/linear/autoCenter false
/gate/RF_box/daughters/name RF351
/gate/RF_box/daughters/insert box
/gate/RF351/setMaterial Aluminium
/gate/RF351/geometry/setXLength 0.001000 cm
/gate/RF351/geometry/setYLength 20 cm
/gate/RF351/geometry/setZLength 1.268000 cm
/gate/RF351/placement/setTranslation -9.611500 0 -2.366000 cm
/gate/RF351/vis/forceSolid
/gate/RF351/vis/setColor yellow
/gate/RF351/repeaters/insert linear
/gate/RF351/linear/setRepeatNumber 40
/gate/RF351/linear/setRepeatVector 5 0 0 mm
/gate/RF351/linear/autoCenter false
/gate/RF_box/daughters/name RF352
/gate/RF_box/daughters/insert box
/gate/RF352/setMaterial Aluminium
/gate/RF352/geometry/setXLength 0.001000 cm
/gate/RF352/geometry/setYLength 20 cm
/gate/RF352/geometry/setZLength 1.245000 cm
/gate/RF352/placement/setTranslation -9.610500 0 -2.377500 cm
/gate/RF352/vis/forceSolid
/gate/RF352/vis/setColor yellow
/gate/RF352/repeaters/insert linear
/gate/RF352/linear/setRepeatNumber 40
/gate/RF352/linear/setRepeatVector 5 0 0 mm
/gate/RF352/linear/autoCenter false
/gate/RF_box/daughters/name RF353
/gate/RF_box/daughters/insert box
/gate/RF353/setMaterial Aluminium
/gate/RF353/geometry/setXLength 0.002000 cm
/gate/RF353/geometry/setYLength 20 cm
/gate/RF353/geometry/setZLength 1.222000 cm
/gate/RF353/placement/setTranslation -9.609000 0 -2.389000 cm
/gate/RF353/vis/forceSolid
/gate/RF353/vis/setColor yellow
/gate/RF353/repeaters/insert linear
/gate/RF353/linear/setRepeatNumber 40
/gate/RF353/linear/setRepeatVector 5 0 0 mm
/gate/RF353/linear/autoCenter false
/gate/RF_box/daughters/name RF354
/gate/RF_box/daughters/insert box
/gate/RF354/setMaterial Aluminium
/gate/RF354/geometry/setXLength 0.001000 cm
/gate/RF354/geometry/setYLength 20 cm
/gate/RF354/geometry/setZLength 1.200000 cm
/gate/RF354/placement/setTranslation -9.607500 0 -2.400000 cm
/gate/RF354/vis/forceSolid
/gate/RF354/vis/setColor yellow
/gate/RF354/repeaters/insert linear
/gate/RF354/linear/setRepeatNumber 40
/gate/RF354/linear/setRepeatVector 5 0 0 mm
/gate/RF354/linear/autoCenter false
/gate/RF_box/daughters/name RF355
/gate/RF_box/daughters/insert box
/gate/RF355/setMaterial Aluminium
/gate/RF355/geometry/setXLength 0.001000 cm
/gate/RF355/geometry/setYLength 20 cm
/gate/RF355/geometry/setZLength 1.177000 cm
/gate/RF355/placement/setTranslation -9.606500 0 -2.411500 cm
/gate/RF355/vis/forceSolid
/gate/RF355/vis/setColor yellow
/gate/RF355/repeaters/insert linear
/gate/RF355/linear/setRepeatNumber 40
/gate/RF355/linear/setRepeatVector 5 0 0 mm
/gate/RF355/linear/autoCenter false
/gate/RF_box/daughters/name RF356
/gate/RF_box/daughters/insert box
/gate/RF356/setMaterial Aluminium
/gate/RF356/geometry/setXLength 0.001000 cm
/gate/RF356/geometry/setYLength 20 cm
/gate/RF356/geometry/setZLength 1.154000 cm
/gate/RF356/placement/setTranslation -9.605500 0 -2.423000 cm
/gate/RF356/vis/forceSolid
/gate/RF356/vis/setColor yellow
/gate/RF356/repeaters/insert linear
/gate/RF356/linear/setRepeatNumber 40
/gate/RF356/linear/setRepeatVector 5 0 0 mm
/gate/RF356/linear/autoCenter false
/gate/RF_box/daughters/name RF357
/gate/RF_box/daughters/insert box
/gate/RF357/setMaterial Aluminium
/gate/RF357/geometry/setXLength 0.002000 cm
/gate/RF357/geometry/setYLength 20 cm
/gate/RF357/geometry/setZLength 1.132000 cm
/gate/RF357/placement/setTranslation -9.604000 0 -2.434000 cm
/gate/RF357/vis/forceSolid
/gate/RF357/vis/setColor yellow
/gate/RF357/repeaters/insert linear
/gate/RF357/linear/setRepeatNumber 40
/gate/RF357/linear/setRepeatVector 5 0 0 mm
/gate/RF357/linear/autoCenter false
/gate/RF_box/daughters/name RF358
/gate/RF_box/daughters/insert box
/gate/RF358/setMaterial Aluminium
/gate/RF358/geometry/setXLength 0.001000 cm
/gate/RF358/geometry/setYLength 20 cm
/gate/RF358/geometry/setZLength 1.109000 cm
/gate/RF358/placement/setTranslation -9.602500 0 -2.445500 cm
/gate/RF358/vis/forceSolid
/gate/RF358/vis/setColor yellow
/gate/RF358/repeaters/insert linear
/gate/RF358/linear/setRepeatNumber 40
/gate/RF358/linear/setRepeatVector 5 0 0 mm
/gate/RF358/linear/autoCenter false
/gate/RF_box/daughters/name RF359
/gate/RF_box/daughters/insert box
/gate/RF359/setMaterial Aluminium
/gate/RF359/geometry/setXLength 0.001000 cm
/gate/RF359/geometry/setYLength 20 cm
/gate/RF359/geometry/setZLength 1.086000 cm
/gate/RF359/placement/setTranslation -9.601500 0 -2.457000 cm
/gate/RF359/vis/forceSolid
/gate/RF359/vis/setColor yellow
/gate/RF359/repeaters/insert linear
/gate/RF359/linear/setRepeatNumber 40
/gate/RF359/linear/setRepeatVector 5 0 0 mm
/gate/RF359/linear/autoCenter false
/gate/RF_box/daughters/name RF360
/gate/RF_box/daughters/insert box
/gate/RF360/setMaterial Aluminium
/gate/RF360/geometry/setXLength 0.002000 cm
/gate/RF360/geometry/setYLength 20 cm
/gate/RF360/geometry/setZLength 1.064000 cm
/gate/RF360/placement/setTranslation -9.600000 0 -2.468000 cm
/gate/RF360/vis/forceSolid
/gate/RF360/vis/setColor yellow
/gate/RF360/repeaters/insert linear
/gate/RF360/linear/setRepeatNumber 40
/gate/RF360/linear/setRepeatVector 5 0 0 mm
/gate/RF360/linear/autoCenter false
/gate/RF_box/daughters/name RF361
/gate/RF_box/daughters/insert box
/gate/RF361/setMaterial Aluminium
/gate/RF361/geometry/setXLength 0.001000 cm
/gate/RF361/geometry/setYLength 20 cm
/gate/RF361/geometry/setZLength 1.041000 cm
/gate/RF361/placement/setTranslation -9.598500 0 -2.479500 cm
/gate/RF361/vis/forceSolid
/gate/RF361/vis/setColor yellow
/gate/RF361/repeaters/insert linear
/gate/RF361/linear/setRepeatNumber 40
/gate/RF361/linear/setRepeatVector 5 0 0 mm
/gate/RF361/linear/autoCenter false
/gate/RF_box/daughters/name RF362
/gate/RF_box/daughters/insert box
/gate/RF362/setMaterial Aluminium
/gate/RF362/geometry/setXLength 0.001000 cm
/gate/RF362/geometry/setYLength 20 cm
/gate/RF362/geometry/setZLength 1.019000 cm
/gate/RF362/placement/setTranslation -9.597500 0 -2.490500 cm
/gate/RF362/vis/forceSolid
/gate/RF362/vis/setColor yellow
/gate/RF362/repeaters/insert linear
/gate/RF362/linear/setRepeatNumber 40
/gate/RF362/linear/setRepeatVector 5 0 0 mm
/gate/RF362/linear/autoCenter false
/gate/RF_box/daughters/name RF363
/gate/RF_box/daughters/insert box
/gate/RF363/setMaterial Aluminium
/gate/RF363/geometry/setXLength 0.002000 cm
/gate/RF363/geometry/setYLength 20 cm
/gate/RF363/geometry/setZLength 0.996000 cm
/gate/RF363/placement/setTranslation -9.596000 0 -2.502000 cm
/gate/RF363/vis/forceSolid
/gate/RF363/vis/setColor yellow
/gate/RF363/repeaters/insert linear
/gate/RF363/linear/setRepeatNumber 40
/gate/RF363/linear/setRepeatVector 5 0 0 mm
/gate/RF363/linear/autoCenter false
/gate/RF_box/daughters/name RF364
/gate/RF_box/daughters/insert box
/gate/RF364/setMaterial Aluminium
/gate/RF364/geometry/setXLength 0.001000 cm
/gate/RF364/geometry/setYLength 20 cm
/gate/RF364/geometry/setZLength 0.973000 cm
/gate/RF364/placement/setTranslation -9.594500 0 -2.513500 cm
/gate/RF364/vis/forceSolid
/gate/RF364/vis/setColor yellow
/gate/RF364/repeaters/insert linear
/gate/RF364/linear/setRepeatNumber 40
/gate/RF364/linear/setRepeatVector 5 0 0 mm
/gate/RF364/linear/autoCenter false
/gate/RF_box/daughters/name RF365
/gate/RF_box/daughters/insert box
/gate/RF365/setMaterial Aluminium
/gate/RF365/geometry/setXLength 0.002000 cm
/gate/RF365/geometry/setYLength 20 cm
/gate/RF365/geometry/setZLength 0.951000 cm
/gate/RF365/placement/setTranslation -9.593000 0 -2.524500 cm
/gate/RF365/vis/forceSolid
/gate/RF365/vis/setColor yellow
/gate/RF365/repeaters/insert linear
/gate/RF365/linear/setRepeatNumber 40
/gate/RF365/linear/setRepeatVector 5 0 0 mm
/gate/RF365/linear/autoCenter false
/gate/RF_box/daughters/name RF366
/gate/RF_box/daughters/insert box
/gate/RF366/setMaterial Aluminium
/gate/RF366/geometry/setXLength 0.001000 cm
/gate/RF366/geometry/setYLength 20 cm
/gate/RF366/geometry/setZLength 0.928000 cm
/gate/RF366/placement/setTranslation -9.591500 0 -2.536000 cm
/gate/RF366/vis/forceSolid
/gate/RF366/vis/setColor yellow
/gate/RF366/repeaters/insert linear
/gate/RF366/linear/setRepeatNumber 40
/gate/RF366/linear/setRepeatVector 5 0 0 mm
/gate/RF366/linear/autoCenter false
/gate/RF_box/daughters/name RF367
/gate/RF_box/daughters/insert box
/gate/RF367/setMaterial Aluminium
/gate/RF367/geometry/setXLength 0.002000 cm
/gate/RF367/geometry/setYLength 20 cm
/gate/RF367/geometry/setZLength 0.905000 cm
/gate/RF367/placement/setTranslation -9.590000 0 -2.547500 cm
/gate/RF367/vis/forceSolid
/gate/RF367/vis/setColor yellow
/gate/RF367/repeaters/insert linear
/gate/RF367/linear/setRepeatNumber 40
/gate/RF367/linear/setRepeatVector 5 0 0 mm
/gate/RF367/linear/autoCenter false
/gate/RF_box/daughters/name RF368
/gate/RF_box/daughters/insert box
/gate/RF368/setMaterial Aluminium
/gate/RF368/geometry/setXLength 0.001000 cm
/gate/RF368/geometry/setYLength 20 cm
/gate/RF368/geometry/setZLength 0.883000 cm
/gate/RF368/placement/setTranslation -9.588500 0 -2.558500 cm
/gate/RF368/vis/forceSolid
/gate/RF368/vis/setColor yellow
/gate/RF368/repeaters/insert linear
/gate/RF368/linear/setRepeatNumber 40
/gate/RF368/linear/setRepeatVector 5 0 0 mm
/gate/RF368/linear/autoCenter false
/gate/RF_box/daughters/name RF369
/gate/RF_box/daughters/insert box
/gate/RF369/setMaterial Aluminium
/gate/RF369/geometry/setXLength 0.002000 cm
/gate/RF369/geometry/setYLength 20 cm
/gate/RF369/geometry/setZLength 0.860000 cm
/gate/RF369/placement/setTranslation -9.587000 0 -2.570000 cm
/gate/RF369/vis/forceSolid
/gate/RF369/vis/setColor yellow
/gate/RF369/repeaters/insert linear
/gate/RF369/linear/setRepeatNumber 40
/gate/RF369/linear/setRepeatVector 5 0 0 mm
/gate/RF369/linear/autoCenter false
/gate/RF_box/daughters/name RF370
/gate/RF_box/daughters/insert box
/gate/RF370/setMaterial Aluminium
/gate/RF370/geometry/setXLength 0.001000 cm
/gate/RF370/geometry/setYLength 20 cm
/gate/RF370/geometry/setZLength 0.837000 cm
/gate/RF370/placement/setTranslation -9.585500 0 -2.581500 cm
/gate/RF370/vis/forceSolid
/gate/RF370/vis/setColor yellow
/gate/RF370/repeaters/insert linear
/gate/RF370/linear/setRepeatNumber 40
/gate/RF370/linear/setRepeatVector 5 0 0 mm
/gate/RF370/linear/autoCenter false
/gate/RF_box/daughters/name RF371
/gate/RF_box/daughters/insert box
/gate/RF371/setMaterial Aluminium
/gate/RF371/geometry/setXLength 0.002000 cm
/gate/RF371/geometry/setYLength 20 cm
/gate/RF371/geometry/setZLength 0.815000 cm
/gate/RF371/placement/setTranslation -9.584000 0 -2.592500 cm
/gate/RF371/vis/forceSolid
/gate/RF371/vis/setColor yellow
/gate/RF371/repeaters/insert linear
/gate/RF371/linear/setRepeatNumber 40
/gate/RF371/linear/setRepeatVector 5 0 0 mm
/gate/RF371/linear/autoCenter false
/gate/RF_box/daughters/name RF372
/gate/RF_box/daughters/insert box
/gate/RF372/setMaterial Aluminium
/gate/RF372/geometry/setXLength 0.001000 cm
/gate/RF372/geometry/setYLength 20 cm
/gate/RF372/geometry/setZLength 0.792000 cm
/gate/RF372/placement/setTranslation -9.582500 0 -2.604000 cm
/gate/RF372/vis/forceSolid
/gate/RF372/vis/setColor yellow
/gate/RF372/repeaters/insert linear
/gate/RF372/linear/setRepeatNumber 40
/gate/RF372/linear/setRepeatVector 5 0 0 mm
/gate/RF372/linear/autoCenter false
/gate/RF_box/daughters/name RF373
/gate/RF_box/daughters/insert box
/gate/RF373/setMaterial Aluminium
/gate/RF373/geometry/setXLength 0.002000 cm
/gate/RF373/geometry/setYLength 20 cm
/gate/RF373/geometry/setZLength 0.770000 cm
/gate/RF373/placement/setTranslation -9.581000 0 -2.615000 cm
/gate/RF373/vis/forceSolid
/gate/RF373/vis/setColor yellow
/gate/RF373/repeaters/insert linear
/gate/RF373/linear/setRepeatNumber 40
/gate/RF373/linear/setRepeatVector 5 0 0 mm
/gate/RF373/linear/autoCenter false
/gate/RF_box/daughters/name RF374
/gate/RF_box/daughters/insert box
/gate/RF374/setMaterial Aluminium
/gate/RF374/geometry/setXLength 0.002000 cm
/gate/RF374/geometry/setYLength 20 cm
/gate/RF374/geometry/setZLength 0.747000 cm
/gate/RF374/placement/setTranslation -9.579000 0 -2.626500 cm
/gate/RF374/vis/forceSolid
/gate/RF374/vis/setColor yellow
/gate/RF374/repeaters/insert linear
/gate/RF374/linear/setRepeatNumber 40
/gate/RF374/linear/setRepeatVector 5 0 0 mm
/gate/RF374/linear/autoCenter false
/gate/RF_box/daughters/name RF375
/gate/RF_box/daughters/insert box
/gate/RF375/setMaterial Aluminium
/gate/RF375/geometry/setXLength 0.001000 cm
/gate/RF375/geometry/setYLength 20 cm
/gate/RF375/geometry/setZLength 0.724000 cm
/gate/RF375/placement/setTranslation -9.577500 0 -2.638000 cm
/gate/RF375/vis/forceSolid
/gate/RF375/vis/setColor yellow
/gate/RF375/repeaters/insert linear
/gate/RF375/linear/setRepeatNumber 40
/gate/RF375/linear/setRepeatVector 5 0 0 mm
/gate/RF375/linear/autoCenter false
/gate/RF_box/daughters/name RF376
/gate/RF_box/daughters/insert box
/gate/RF376/setMaterial Aluminium
/gate/RF376/geometry/setXLength 0.002000 cm
/gate/RF376/geometry/setYLength 20 cm
/gate/RF376/geometry/setZLength 0.702000 cm
/gate/RF376/placement/setTranslation -9.576000 0 -2.649000 cm
/gate/RF376/vis/forceSolid
/gate/RF376/vis/setColor yellow
/gate/RF376/repeaters/insert linear
/gate/RF376/linear/setRepeatNumber 40
/gate/RF376/linear/setRepeatVector 5 0 0 mm
/gate/RF376/linear/autoCenter false
/gate/RF_box/daughters/name RF377
/gate/RF_box/daughters/insert box
/gate/RF377/setMaterial Aluminium
/gate/RF377/geometry/setXLength 0.002000 cm
/gate/RF377/geometry/setYLength 20 cm
/gate/RF377/geometry/setZLength 0.679000 cm
/gate/RF377/placement/setTranslation -9.574000 0 -2.660500 cm
/gate/RF377/vis/forceSolid
/gate/RF377/vis/setColor yellow
/gate/RF377/repeaters/insert linear
/gate/RF377/linear/setRepeatNumber 40
/gate/RF377/linear/setRepeatVector 5 0 0 mm
/gate/RF377/linear/autoCenter false
/gate/RF_box/daughters/name RF378
/gate/RF_box/daughters/insert box
/gate/RF378/setMaterial Aluminium
/gate/RF378/geometry/setXLength 0.001000 cm
/gate/RF378/geometry/setYLength 20 cm
/gate/RF378/geometry/setZLength 0.656000 cm
/gate/RF378/placement/setTranslation -9.572500 0 -2.672000 cm
/gate/RF378/vis/forceSolid
/gate/RF378/vis/setColor yellow
/gate/RF378/repeaters/insert linear
/gate/RF378/linear/setRepeatNumber 40
/gate/RF378/linear/setRepeatVector 5 0 0 mm
/gate/RF378/linear/autoCenter false
/gate/RF_box/daughters/name RF379
/gate/RF_box/daughters/insert box
/gate/RF379/setMaterial Aluminium
/gate/RF379/geometry/setXLength 0.002000 cm
/gate/RF379/geometry/setYLength 20 cm
/gate/RF379/geometry/setZLength 0.634000 cm
/gate/RF379/placement/setTranslation -9.571000 0 -2.683000 cm
/gate/RF379/vis/forceSolid
/gate/RF379/vis/setColor yellow
/gate/RF379/repeaters/insert linear
/gate/RF379/linear/setRepeatNumber 40
/gate/RF379/linear/setRepeatVector 5 0 0 mm
/gate/RF379/linear/autoCenter false
/gate/RF_box/daughters/name RF380
/gate/RF_box/daughters/insert box
/gate/RF380/setMaterial Aluminium
/gate/RF380/geometry/setXLength 0.002000 cm
/gate/RF380/geometry/setYLength 20 cm
/gate/RF380/geometry/setZLength 0.611000 cm
/gate/RF380/placement/setTranslation -9.569000 0 -2.694500 cm
/gate/RF380/vis/forceSolid
/gate/RF380/vis/setColor yellow
/gate/RF380/repeaters/insert linear
/gate/RF380/linear/setRepeatNumber 40
/gate/RF380/linear/setRepeatVector 5 0 0 mm
/gate/RF380/linear/autoCenter false
/gate/RF_box/daughters/name RF381
/gate/RF_box/daughters/insert box
/gate/RF381/setMaterial Aluminium
/gate/RF381/geometry/setXLength 0.002000 cm
/gate/RF381/geometry/setYLength 20 cm
/gate/RF381/geometry/setZLength 0.589000 cm
/gate/RF381/placement/setTranslation -9.567000 0 -2.705500 cm
/gate/RF381/vis/forceSolid
/gate/RF381/vis/setColor yellow
/gate/RF381/repeaters/insert linear
/gate/RF381/linear/setRepeatNumber 40
/gate/RF381/linear/setRepeatVector 5 0 0 mm
/gate/RF381/linear/autoCenter false
/gate/RF_box/daughters/name RF382
/gate/RF_box/daughters/insert box
/gate/RF382/setMaterial Aluminium
/gate/RF382/geometry/setXLength 0.002000 cm
/gate/RF382/geometry/setYLength 20 cm
/gate/RF382/geometry/setZLength 0.566000 cm
/gate/RF382/placement/setTranslation -9.565000 0 -2.717000 cm
/gate/RF382/vis/forceSolid
/gate/RF382/vis/setColor yellow
/gate/RF382/repeaters/insert linear
/gate/RF382/linear/setRepeatNumber 40
/gate/RF382/linear/setRepeatVector 5 0 0 mm
/gate/RF382/linear/autoCenter false
/gate/RF_box/daughters/name RF383
/gate/RF_box/daughters/insert box
/gate/RF383/setMaterial Aluminium
/gate/RF383/geometry/setXLength 0.002000 cm
/gate/RF383/geometry/setYLength 20 cm
/gate/RF383/geometry/setZLength 0.543000 cm
/gate/RF383/placement/setTranslation -9.563000 0 -2.728500 cm
/gate/RF383/vis/forceSolid
/gate/RF383/vis/setColor yellow
/gate/RF383/repeaters/insert linear
/gate/RF383/linear/setRepeatNumber 40
/gate/RF383/linear/setRepeatVector 5 0 0 mm
/gate/RF383/linear/autoCenter false
/gate/RF_box/daughters/name RF384
/gate/RF_box/daughters/insert box
/gate/RF384/setMaterial Aluminium
/gate/RF384/geometry/setXLength 0.002000 cm
/gate/RF384/geometry/setYLength 20 cm
/gate/RF384/geometry/setZLength 0.521000 cm
/gate/RF384/placement/setTranslation -9.561000 0 -2.739500 cm
/gate/RF384/vis/forceSolid
/gate/RF384/vis/setColor yellow
/gate/RF384/repeaters/insert linear
/gate/RF384/linear/setRepeatNumber 40
/gate/RF384/linear/setRepeatVector 5 0 0 mm
/gate/RF384/linear/autoCenter false
/gate/RF_box/daughters/name RF385
/gate/RF_box/daughters/insert box
/gate/RF385/setMaterial Aluminium
/gate/RF385/geometry/setXLength 0.002000 cm
/gate/RF385/geometry/setYLength 20 cm
/gate/RF385/geometry/setZLength 0.498000 cm
/gate/RF385/placement/setTranslation -9.559000 0 -2.751000 cm
/gate/RF385/vis/forceSolid
/gate/RF385/vis/setColor yellow
/gate/RF385/repeaters/insert linear
/gate/RF385/linear/setRepeatNumber 40
/gate/RF385/linear/setRepeatVector 5 0 0 mm
/gate/RF385/linear/autoCenter false
/gate/RF_box/daughters/name RF386
/gate/RF_box/daughters/insert box
/gate/RF386/setMaterial Aluminium
/gate/RF386/geometry/setXLength 0.002000 cm
/gate/RF386/geometry/setYLength 20 cm
/gate/RF386/geometry/setZLength 0.475000 cm
/gate/RF386/placement/setTranslation -9.557000 0 -2.762500 cm
/gate/RF386/vis/forceSolid
/gate/RF386/vis/setColor yellow
/gate/RF386/repeaters/insert linear
/gate/RF386/linear/setRepeatNumber 40
/gate/RF386/linear/setRepeatVector 5 0 0 mm
/gate/RF386/linear/autoCenter false
/gate/RF_box/daughters/name RF387
/gate/RF_box/daughters/insert box
/gate/RF387/setMaterial Aluminium
/gate/RF387/geometry/setXLength 0.002000 cm
/gate/RF387/geometry/setYLength 20 cm
/gate/RF387/geometry/setZLength 0.453000 cm
/gate/RF387/placement/setTranslation -9.555000 0 -2.773500 cm
/gate/RF387/vis/forceSolid
/gate/RF387/vis/setColor yellow
/gate/RF387/repeaters/insert linear
/gate/RF387/linear/setRepeatNumber 40
/gate/RF387/linear/setRepeatVector 5 0 0 mm
/gate/RF387/linear/autoCenter false
/gate/RF_box/daughters/name RF388
/gate/RF_box/daughters/insert box
/gate/RF388/setMaterial Aluminium
/gate/RF388/geometry/setXLength 0.002000 cm
/gate/RF388/geometry/setYLength 20 cm
/gate/RF388/geometry/setZLength 0.430000 cm
/gate/RF388/placement/setTranslation -9.553000 0 -2.785000 cm
/gate/RF388/vis/forceSolid
/gate/RF388/vis/setColor yellow
/gate/RF388/repeaters/insert linear
/gate/RF388/linear/setRepeatNumber 40
/gate/RF388/linear/setRepeatVector 5 0 0 mm
/gate/RF388/linear/autoCenter false
/gate/RF_box/daughters/name RF389
/gate/RF_box/daughters/insert box
/gate/RF389/setMaterial Aluminium
/gate/RF389/geometry/setXLength 0.003000 cm
/gate/RF389/geometry/setYLength 20 cm
/gate/RF389/geometry/setZLength 0.407000 cm
/gate/RF389/placement/setTranslation -9.550500 0 -2.796500 cm
/gate/RF389/vis/forceSolid
/gate/RF389/vis/setColor yellow
/gate/RF389/repeaters/insert linear
/gate/RF389/linear/setRepeatNumber 40
/gate/RF389/linear/setRepeatVector 5 0 0 mm
/gate/RF389/linear/autoCenter false
/gate/RF_box/daughters/name RF390
/gate/RF_box/daughters/insert box
/gate/RF390/setMaterial Aluminium
/gate/RF390/geometry/setXLength 0.002000 cm
/gate/RF390/geometry/setYLength 20 cm
/gate/RF390/geometry/setZLength 0.385000 cm
/gate/RF390/placement/setTranslation -9.548000 0 -2.807500 cm
/gate/RF390/vis/forceSolid
/gate/RF390/vis/setColor yellow
/gate/RF390/repeaters/insert linear
/gate/RF390/linear/setRepeatNumber 40
/gate/RF390/linear/setRepeatVector 5 0 0 mm
/gate/RF390/linear/autoCenter false
/gate/RF_box/daughters/name RF391
/gate/RF_box/daughters/insert box
/gate/RF391/setMaterial Aluminium
/gate/RF391/geometry/setXLength 0.003000 cm
/gate/RF391/geometry/setYLength 20 cm
/gate/RF391/geometry/setZLength 0.362000 cm
/gate/RF391/placement/setTranslation -9.545500 0 -2.819000 cm
/gate/RF391/vis/forceSolid
/gate/RF391/vis/setColor yellow
/gate/RF391/repeaters/insert linear
/gate/RF391/linear/setRepeatNumber 40
/gate/RF391/linear/setRepeatVector 5 0 0 mm
/gate/RF391/linear/autoCenter false
/gate/RF_box/daughters/name RF392
/gate/RF_box/daughters/insert box
/gate/RF392/setMaterial Aluminium
/gate/RF392/geometry/setXLength 0.002000 cm
/gate/RF392/geometry/setYLength 20 cm
/gate/RF392/geometry/setZLength 0.340000 cm
/gate/RF392/placement/setTranslation -9.543000 0 -2.830000 cm
/gate/RF392/vis/forceSolid
/gate/RF392/vis/setColor yellow
/gate/RF392/repeaters/insert linear
/gate/RF392/linear/setRepeatNumber 40
/gate/RF392/linear/setRepeatVector 5 0 0 mm
/gate/RF392/linear/autoCenter false
/gate/RF_box/daughters/name RF393
/gate/RF_box/daughters/insert box
/gate/RF393/setMaterial Aluminium
/gate/RF393/geometry/setXLength 0.003000 cm
/gate/RF393/geometry/setYLength 20 cm
/gate/RF393/geometry/setZLength 0.317000 cm
/gate/RF393/placement/setTranslation -9.540500 0 -2.841500 cm
/gate/RF393/vis/forceSolid
/gate/RF393/vis/setColor yellow
/gate/RF393/repeaters/insert linear
/gate/RF393/linear/setRepeatNumber 40
/gate/RF393/linear/setRepeatVector 5 0 0 mm
/gate/RF393/linear/autoCenter false
/gate/RF_box/daughters/name RF394
/gate/RF_box/daughters/insert box
/gate/RF394/setMaterial Aluminium
/gate/RF394/geometry/setXLength 0.003000 cm
/gate/RF394/geometry/setYLength 20 cm
/gate/RF394/geometry/setZLength 0.294000 cm
/gate/RF394/placement/setTranslation -9.537500 0 -2.853000 cm
/gate/RF394/vis/forceSolid
/gate/RF394/vis/setColor yellow
/gate/RF394/repeaters/insert linear
/gate/RF394/linear/setRepeatNumber 40
/gate/RF394/linear/setRepeatVector 5 0 0 mm
/gate/RF394/linear/autoCenter false
/gate/RF_box/daughters/name RF395
/gate/RF_box/daughters/insert box
/gate/RF395/setMaterial Aluminium
/gate/RF395/geometry/setXLength 0.002000 cm
/gate/RF395/geometry/setYLength 20 cm
/gate/RF395/geometry/setZLength 0.272000 cm
/gate/RF395/placement/setTranslation -9.535000 0 -2.864000 cm
/gate/RF395/vis/forceSolid
/gate/RF395/vis/setColor yellow
/gate/RF395/repeaters/insert linear
/gate/RF395/linear/setRepeatNumber 40
/gate/RF395/linear/setRepeatVector 5 0 0 mm
/gate/RF395/linear/autoCenter false
/gate/RF_box/daughters/name RF396
/gate/RF_box/daughters/insert box
/gate/RF396/setMaterial Aluminium
/gate/RF396/geometry/setXLength 0.003000 cm
/gate/RF396/geometry/setYLength 20 cm
/gate/RF396/geometry/setZLength 0.249000 cm
/gate/RF396/placement/setTranslation -9.532500 0 -2.875500 cm
/gate/RF396/vis/forceSolid
/gate/RF396/vis/setColor yellow
/gate/RF396/repeaters/insert linear
/gate/RF396/linear/setRepeatNumber 40
/gate/RF396/linear/setRepeatVector 5 0 0 mm
/gate/RF396/linear/autoCenter false
/gate/RF_box/daughters/name RF397
/gate/RF_box/daughters/insert box
/gate/RF397/setMaterial Aluminium
/gate/RF397/geometry/setXLength 0.006000 cm
/gate/RF397/geometry/setYLength 20 cm
/gate/RF397/geometry/setZLength 0.226000 cm
/gate/RF397/placement/setTranslation -9.528000 0 -2.887000 cm
/gate/RF397/vis/forceSolid
/gate/RF397/vis/setColor yellow
/gate/RF397/repeaters/insert linear
/gate/RF397/linear/setRepeatNumber 40
/gate/RF397/linear/setRepeatVector 5 0 0 mm
/gate/RF397/linear/autoCenter false
/gate/RF_box/daughters/name RF398
/gate/RF_box/daughters/insert box
/gate/RF398/setMaterial Aluminium
/gate/RF398/geometry/setXLength 0.003000 cm
/gate/RF398/geometry/setYLength 20 cm
/gate/RF398/geometry/setZLength 0.204000 cm
/gate/RF398/placement/setTranslation -9.523500 0 -2.898000 cm
/gate/RF398/vis/forceSolid
/gate/RF398/vis/setColor yellow
/gate/RF398/repeaters/insert linear
/gate/RF398/linear/setRepeatNumber 40
/gate/RF398/linear/setRepeatVector 5 0 0 mm
/gate/RF398/linear/autoCenter false
/gate/RF_box/daughters/name RF400
/gate/RF_box/daughters/insert box
/gate/RF400/setMaterial Aluminium
/gate/RF400/geometry/setXLength 0.003000 cm
/gate/RF400/geometry/setYLength 20 cm
/gate/RF400/geometry/setZLength 0.158000 cm
/gate/RF400/placement/setTranslation -9.520500 0 -2.921000 cm
/gate/RF400/vis/forceSolid
/gate/RF400/vis/setColor yellow
/gate/RF400/repeaters/insert linear
/gate/RF400/linear/setRepeatNumber 40
/gate/RF400/linear/setRepeatVector 5 0 0 mm
/gate/RF400/linear/autoCenter false
/gate/RF_box/daughters/name RF401
/gate/RF_box/daughters/insert box
/gate/RF401/setMaterial Aluminium
/gate/RF401/geometry/setXLength 0.019000 cm
/gate/RF401/geometry/setYLength 20 cm
/gate/RF401/geometry/setZLength 0.136000 cm
/gate/RF401/placement/setTranslation -9.509500 0 -2.932000 cm
/gate/RF401/vis/forceSolid
/gate/RF401/vis/setColor yellow
/gate/RF401/repeaters/insert linear
/gate/RF401/linear/setRepeatNumber 40
/gate/RF401/linear/setRepeatVector 5 0 0 mm
/gate/RF401/linear/autoCenter false

/gate/RF_box/placement/setRotationAxis 0 1 0
/gate/RF_box/placement/setRotationAngle 180 deg
/gate/world/daughters/name mul_collimator
/gate/world/daughters/insert box
/gate/mul_collimator/geometry/setXLength 200 mm
/gate/mul_collimator/geometry/setYLength 200 mm
/gate/mul_collimator/geometry/setZLength 64.8 mm
/gate/mul_collimator/placement/setTranslation 0 0 -720 mm
/gate/mul_collimator/setMaterial MLC
/gate/mul_collimator/vis/forceWireframe
/gate/mul_collimator/daughters/name openhole
/gate/mul_collimator/daughters/insert box
/gate/openhole/geometry/setXLength 100 mm
/gate/openhole/geometry/setYLength 100 mm
/gate/openhole/geometry/setZLength 64.8 mm
/gate/openhole/placement/setTranslation 0 0 0 mm
/gate/openhole/setMaterial Air
/gate/openhole/vis/forceSolid

/gate/world/daughters/name watertank
/gate/world/daughters/insert box
/gate/watertank/setMaterial Water
/gate/watertank/geometry/setXLength 20.0 cm
/gate/watertank/geometry/setYLength 20.0 cm
/gate/watertank/geometry/setZLength 35.0 cm
/gate/watertank/placement/setTranslation 0 0 0 cm
/gate/watertank/vis/forceWireframe
/gate/watertank/vis/setColor blue

/gate/physics/addPhysicsList QGSP_BERT_HP_EMY
/gate/geometry/setIonisationPotential Water 75 eV
/gate/physics/displayCuts
/gate/physics/print output/physics.txt
/gate/physics/Gamma/SetCutInRegion world 10 m
/gate/physics/Electron/SetCutInRegion world 10 m
/gate/physics/Positron/SetCutInRegion world 10 m
/gate/physics/Gamma/SetCutInRegion pre_collimator 1 mm
/gate/physics/Electron/SetCutInRegion pre_collimator 1 mm
/gate/physics/Positron/SetCutInRegion pre_collimator 1 mm
/gate/physics/Gamma/SetCutInRegion pre_hole 10 m
/gate/physics/Electron/SetCutInRegion pre_hole 10 m
/gate/physics/Positron/SetCutInRegion pre_hole 10 m
/gate/physics/Gamma/SetCutInRegion RF_box 1 mm
/gate/physics/Electron/SetCutInRegion RF_box 1 mm
/gate/physics/Positron/SetCutInRegion RF_box 1 mm
/gate/physics/Gamma/SetCutInRegion mul_collimator 1 mm
/gate/physics/Electron/SetCutInRegion mul_collimator 1 mm
/gate/physics/Positron/SetCutInRegion mul_collimator 1 mm
/gate/physics/Gamma/SetCutInRegion watertank 1 mm
/gate/physics/Electron/SetCutInRegion watertank 1 mm
/gate/physics/Positron/SetCutInRegion watertank 1 mm
/gate/physics/SetMaxStepSizeInRegion world 1 cm
/gate/physics/SetMaxStepSizeInRegion pre_collimator 1 mm
/gate/physics/SetMaxStepSizeInRegion RF_box 1 mm
/gate/physics/SetMaxStepSizeInRegion mul_collimator 1 mm
/gate/physics/SetMaxStepSizeInRegion watertank 1mm
/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter deuteron
/gate/physics/ActivateStepLimiter triton
/gate/physics/ActivateStepLimiter alpha
/gate/physics/ActivateStepLimiter GenericIon
/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter e-
/gate/physics/displayCuts
/gate/actor/addActor DoseActor doseDistribution
/gate/actor/doseDistribution/save output/braggpeak_water46.root
/gate/actor/doseDistribution/attachTo watertank
/gate/actor/doseDistribution/stepHitType random
/gate/actor/doseDistribution/setPosition 0 0 0 mm
/gate/actor/doseDistribution/setVoxelSize 150 150 0.2 mm
/gate/actor/doseDistribution/enableEdep false
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableDose true
/gate/actor/doseDistribution/enableSquaredDose false
/gate/actor/doseDistribution/enableUncertaintyDose false
/gate/actor/doseDistribution/enableNumberOfHits false
/gate/actor/doseDistribution/saveEveryNSeconds 20

/gate/run/initialize
/gate/source/addSource C12 gps
/gate/source/C12/gps/particle ion
/gate/source/C12/gps/ion 6 12
/gate/source/C12/gps/ene/type Gauss
/gate/source/C12/gps/energy 4800 MeV
/gate/source/C12/gps/ene/sigma 0.0 MeV
/gate/source/C12/gps/pos/type Plane
/gate/source/C12/gps/pos/shape Square
/gate/source/C12/gps/pos/halfx 7.5 cm
/gate/source/C12/gps/pos/halfy 7.5 cm
/gate/source/C12/gps/ang/minphi 0 deg
/gate/source/C12/gps/ang/maxphi 360 deg
/gate/source/C12/gps/ang/mintheta 0 deg
/gate/source/C12/gps/ang/maxtheta 0 deg
/gate/source/C12/gps/pos/centre 0. 0. -450 cm
/gate/source/C12/gps/direction 0 0 1
/gate/random/setEngineName MersenneTwister

/gate/application/setTotalNumberOfPrimaries 209000
/gate/random/setEngineSeed 3250855336105021505
/gate/application/setTimeStart 0. s
/gate/application/addSlice     1. s
/gate/application/startDAQCluster 0.9375 0.958333 0 s

