 ######################
 # Pre_Collimator #
######################
/gate/world/daughters/name pre_collimator
/gate/world/daughters/insert box
/gate/pre_collimator/geometry/setXLength 200 mm
/gate/pre_collimator/geometry/setYLength 200 mm
/gate/pre_collimator/geometry/setZLength  46 mm
/gate/pre_collimator/placement/setTranslation 0 0 -3575 mm
/gate/pre_collimator/setMaterial Copper
/gate/pre_collimator/vis/forceWireframe
#/gate/pre_collimator/vis/setColor Blue

/gate/pre_collimator/daughters/name pre_hole
/gate/pre_collimator/daughters/insert box
/gate/pre_hole/geometry/setXLength 150 mm
/gate/pre_hole/geometry/setYLength 150 mm
/gate/pre_hole/geometry/setZLength  46 mm
/gate/pre_hole/placement/setTranslation 0 0 0 mm
/gate/pre_hole/setMaterial Air
#/gate/pre_hole/vis/setColor Yellow
/gate/pre_hole/vis/forceSolid


  #################
 #  Ridge filter #
#################


/control/execute mac/RF_data/RF_300MeV_6cm_Al.mac

/gate/RF_box/placement/setRotationAxis 0 1 0
/gate/RF_box/placement/setRotationAngle 180 deg



  ##################
 #  Range shifter #
##################
  #########################
 # Four-leaf collimator #
#########################
/gate/world/daughters/name four_collimator_1
/gate/world/daughters/insert box
/gate/four_collimator_1/geometry/setXLength 140 mm
/gate/four_collimator_1/geometry/setYLength 360 mm
/gate/four_collimator_1/geometry/setZLength  200 mm
/gate/four_collimator_1/placement/setTranslation 105 0 -1090 mm
/gate/four_collimator_1/setMaterial Iron
#/gate/four_collimator_1/vis/setColor Blue
/gate/four_collimator_1/vis/forceSolid

/gate/world/daughters/name four_collimator_2
/gate/world/daughters/insert box
/gate/four_collimator_2/geometry/setXLength 140 mm
/gate/four_collimator_2/geometry/setYLength 360 mm
/gate/four_collimator_2/geometry/setZLength  200 mm
/gate/four_collimator_2/placement/setTranslation -105 0 -1090 mm
/gate/four_collimator_2/setMaterial Iron
#/gate/four_collimator_2/vis/setColor Blue
/gate/four_collimator_2/vis/forceSolid

/gate/world/daughters/name four_collimator_3
/gate/world/daughters/insert box
/gate/four_collimator_3/geometry/setXLength 360 mm
/gate/four_collimator_3/geometry/setYLength 140 mm
/gate/four_collimator_3/geometry/setZLength  200 mm
/gate/four_collimator_3/placement/setTranslation 0 109 -890 mm
/gate/four_collimator_3/setMaterial Iron
#/gate/four_collimator_3/vis/setColor Blue
/gate/four_collimator_3/vis/forceSolid

/gate/world/daughters/name four_collimator_4
/gate/world/daughters/insert box
/gate/four_collimator_4/geometry/setXLength 360 mm
/gate/four_collimator_4/geometry/setYLength 140 mm
/gate/four_collimator_4/geometry/setZLength  200 mm
/gate/four_collimator_4/placement/setTranslation 0 -109 -890 mm
/gate/four_collimator_4/setMaterial Iron
#/gate/four_collimator_4/vis/setColor Blue
/gate/four_collimator_4/vis/forceSolid

  #########################
 # Multi-leaf collimator #
#########################
/gate/world/daughters/name mul_collimator
/gate/world/daughters/insert box
/gate/mul_collimator/geometry/setXLength 154 mm
/gate/mul_collimator/geometry/setYLength 600 mm
/gate/mul_collimator/geometry/setZLength  140 mm
/gate/mul_collimator/placement/setTranslation 0 0 -720 mm
/gate/mul_collimator/setMaterial Iron
#/gate/mul_collimator/vis/setColor Blue
/gate/mul_collimator/vis/forceWireframe

/gate/mul_collimator/daughters/name openhole
/gate/mul_collimator/daughters/insert box
/gate/openhole/geometry/setXLength 58 mm
/gate/openhole/geometry/setYLength 50 mm
/gate/openhole/geometry/setZLength  140 mm
/gate/openhole/placement/setTranslation 0 0 0 mm
/gate/openhole/setMaterial Air
#/gate/openhole/vis/setColor Yellow
/gate/openhole/vis/forceSolid

