void plot3()
{
    TFile *ipf=new TFile("mergefile.root");
    TTree *ipt=(TTree*)ipf->Get("t");
    TCanvas *c0=new TCanvas("c0","c0",0,0,700,500);
    c0->cd();
    TPad *pad=new TPad("pad","pad",0,0,1,1);
    pad->Draw();
    pad->cd();
    pad->Range(0,0,15,15);
    
    ipt->Draw("HD_pre/HD_mc:distance","energy==400   && width==2 && location <=10 && size <=120","goff");
    TGraph *gr1=new TGraph(ipt->GetSelectedRows(),ipt->GetV2(),ipt->GetV1());
    gr1->SetMarkerStyle(34);
    gr1->SetMarkerColor(7);
    gr1->SetMarkerSize(1.5);
    ipt->Draw("HD_pre/HD_mc:distance","energy==400  && width==4 && location <=10 && size <=0 ","goff");
    TGraph *gr2=new TGraph(ipt->GetSelectedRows(),ipt->GetV2(),ipt->GetV1());
    gr2->SetMarkerStyle(21);
    gr2->SetMarkerColor(6);
    gr2->SetMarkerSize(1.5);
    ipt->Draw("HD_pre/HD_mc:distance","energy==400   && width==6 && location <=10 && size <=0 ","goff");
    TGraph *gr3=new TGraph(ipt->GetSelectedRows(),ipt->GetV2(),ipt->GetV1());
    gr3->SetMarkerStyle(20);
    gr3->SetMarkerColor(4);
    gr3->SetMarkerSize(1.5);
    ipt->Draw("HD_pre/HD_mc:distance","energy==400   && width==8 && location <=10 && size <=0 ","goff");
    TGraph *gr4=new TGraph(ipt->GetSelectedRows(),ipt->GetV2(),ipt->GetV1());
    gr4->SetMarkerStyle(23);
    gr4->SetMarkerColor(3);
    gr4->SetMarkerSize(1.5);
    ipt->Draw("HD_pre/HD_mc:distance","energy==400   && width==10 &&location <=10 && size <=0 ","goff");
    TGraph *gr5=new TGraph(ipt->GetSelectedRows(),ipt->GetV2(),ipt->GetV1());
    gr5->SetMarkerStyle(22);
    gr5->SetMarkerColor(2);
    gr5->SetMarkerSize(1.5);
    ipt->Draw("HD_pre/HD_mc:distance","energy==400   && width==12 && location <=10 && size <=0 ","goff");
    TGraph *gr6=new TGraph(ipt->GetSelectedRows(),ipt->GetV2(),ipt->GetV1());
    gr6->SetMarkerStyle(43);
    gr6->SetMarkerColor(9);
    gr6->SetMarkerSize(1.5);

    ipt->Draw("HD_pre/HD_mc:distance","energy==165   && width==6 && location <=10 && size <=0 ","goff");
    TGraph *gr7=new TGraph(ipt->GetSelectedRows(),ipt->GetV2(),ipt->GetV1());
    gr7->SetMarkerStyle(29);
    gr7->SetMarkerColor(46);
    gr7->SetMarkerSize(1.5);
    ipt->Draw("HD_pre/HD_mc:distance","energy==200   && width==6 && location <=10 && size <=0 ","goff");
    TGraph *gr8=new TGraph(ipt->GetSelectedRows(),ipt->GetV2(),ipt->GetV1());
    gr8->SetMarkerStyle(33);
    gr8->SetMarkerColor(21);
    gr8->SetMarkerSize(1.5);
    ipt->Draw("HD_pre/HD_mc:distance","energy==250   && width==6 &&location <=10 && size <=0 ","goff");
    TGraph *gr9=new TGraph(ipt->GetSelectedRows(),ipt->GetV2(),ipt->GetV1());
    gr9->SetMarkerStyle(39);
    gr9->SetMarkerColor(38);
    gr9->SetMarkerSize(1.5);
    ipt->Draw("HD_pre/HD_mc:distance","energy==300   && width==6 && location <=10 && size <=0 ","goff");
    TGraph *gr10=new TGraph(ipt->GetSelectedRows(),ipt->GetV2(),ipt->GetV1());
    gr10->SetMarkerStyle(41);
    gr10->SetMarkerColor(41);
    gr10->SetMarkerSize(1.5);
    ipt->Draw("HD_pre/HD_mc:distance","energy==350   && width==6 && location <=10 && size <=0 ","goff");
    TGraph *gr11=new TGraph(ipt->GetSelectedRows(),ipt->GetV2(),ipt->GetV1());
    gr11->SetMarkerStyle(47);
    gr11->SetMarkerColor(28);
    gr11->SetMarkerSize(1.5);


    TMultiGraph *mgp=new TMultiGraph();
    mgp->Add(gr1,"p");
    mgp->Add(gr2,"p");
    mgp->Add(gr3,"p");
    mgp->Add(gr4,"p");
    mgp->Add(gr5,"p");
    mgp->Add(gr6,"p");
    mgp->Add(gr7,"p");
    mgp->Add(gr8,"p");
    mgp->Add(gr9,"p");
    mgp->Add(gr10,"p");
    mgp->Add(gr11,"p");
    mgp->Draw("a");
    mgp->GetYaxis()->SetLimits(0,1.2);
    //mgp->GetXaxis()->SetLimits(40,310);
    mgp->GetYaxis()->SetRangeUser(0,1.2);
    //mgp->GetXaxis()->SetRangeUser(40,310);
    mgp->GetXaxis()->SetTitle("d (cm)");
    mgp->GetXaxis()->CenterTitle(true);
    mgp->GetYaxis()->SetTitle("(H/D)_{pred} / (H/D)_{mc}");
    mgp->GetYaxis()->CenterTitle(true);
    TLegend *leg;
    leg=new TLegend(0.6,0.5,0.8,0.8);
    leg->AddEntry(gr7,"165 MeV/u,  6cm SOBP","p");
    leg->AddEntry(gr8,"200 MeV/u,  6cm SOBP","p");
    leg->AddEntry(gr9,"250 MeV/u,  6cm SOBP","p");
    leg->AddEntry(gr10,"300 MeV/u,  6cm SOBP","p");
    leg->AddEntry(gr11,"350 MeV/u,  6cm SOBP","p");
    leg->AddEntry(gr1,"400 MeV/u,  2cm SOBP","p");
    leg->AddEntry(gr2,"400 MeV/u,  4cm SOBP","p");
    leg->AddEntry(gr3,"400 MeV/u,  6cm SOBP","p");
    leg->AddEntry(gr4,"400 MeV/u,  8cm SOBP","p");
    leg->AddEntry(gr5,"400 MeV/u, 10cm SOBP","p");
    leg->AddEntry(gr6,"400 MeV/u, 12cm SOBP","p");
    //leg->AddEntry(f1,"Power law fit","l");
    leg->SetTextSize(0.03);
    leg->Draw();
}