#=====================================================
# OUTPUT - DETECTOR
#=====================================================

#receptor11
/gate/actor/addActor                                 EnergySpectrumActor  receptor11
/gate/actor/receptor11/save                           output/90deg/25cm/11_receptor.root
/gate/actor/receptor11/attachTo                       volume11
/gate/actor/receptor11/addFilter                      particleFilter
/gate/actor/receptor11/particleFilter/addParticle     neutron
/gate/actor/receptor11/energySpectrum/setEmin         1e-6 MeV
/gate/actor/receptor11/energySpectrum/setEmax         1e3 MeV
/gate/actor/receptor11/energySpectrum/setNumberOfBins 480
/gate/actor/receptor11/setLogBinWidth		      true
/gate/actor/receptor11/enableFluenceTrackSpectrum     true
/gate/actor/receptor11/enableEdepSpectrum             false
/gate/actor/receptor11/enableNbPartSpectrum           true

#receptor12
/gate/actor/addActor                                 EnergySpectrumActor  receptor12
/gate/actor/receptor12/save                           output/90deg/50cm/12_receptor.root
/gate/actor/receptor12/attachTo                       volume12
/gate/actor/receptor12/addFilter                      particleFilter
/gate/actor/receptor12/particleFilter/addParticle     neutron
/gate/actor/receptor12/energySpectrum/setEmin         1e-6 MeV
/gate/actor/receptor12/energySpectrum/setEmax         1e3 MeV
/gate/actor/receptor12/energySpectrum/setNumberOfBins 480
/gate/actor/receptor12/setLogBinWidth		      true
/gate/actor/receptor12/enableFluenceTrackSpectrum     true
/gate/actor/receptor12/enableEdepSpectrum             false
/gate/actor/receptor12/enableNbPartSpectrum           true

#receptor13
/gate/actor/addActor                                 EnergySpectrumActor  receptor13
/gate/actor/receptor13/save                           output/90deg/100cm/13_receptor.root
/gate/actor/receptor13/attachTo                       volume13
/gate/actor/receptor13/addFilter                      particleFilter
/gate/actor/receptor13/particleFilter/addParticle     neutron
/gate/actor/receptor13/energySpectrum/setEmin         1e-6 MeV
/gate/actor/receptor13/energySpectrum/setEmax         1e3 MeV
/gate/actor/receptor13/energySpectrum/setNumberOfBins 480
/gate/actor/receptor13/setLogBinWidth		      true
/gate/actor/receptor13/enableFluenceTrackSpectrum     true
/gate/actor/receptor13/enableEdepSpectrum             false
/gate/actor/receptor13/enableNbPartSpectrum           true


#receptor14
/gate/actor/addActor                                 EnergySpectrumActor  receptor14
/gate/actor/receptor14/save                           output/90deg/150cm/14_receptor.root
/gate/actor/receptor14/attachTo                       volume14
/gate/actor/receptor14/addFilter                      particleFilter
/gate/actor/receptor14/particleFilter/addParticle     neutron
/gate/actor/receptor14/energySpectrum/setEmin         1e-6 MeV
/gate/actor/receptor14/energySpectrum/setEmax         1e3 MeV
/gate/actor/receptor14/energySpectrum/setNumberOfBins 480
/gate/actor/receptor14/setLogBinWidth		      true
/gate/actor/receptor14/enableFluenceTrackSpectrum     true
/gate/actor/receptor14/enableEdepSpectrum             false
/gate/actor/receptor14/enableNbPartSpectrum           true

#receptor15
/gate/actor/addActor                                 EnergySpectrumActor  receptor15
/gate/actor/receptor15/save                           output/90deg/200cm/15_receptor.root
/gate/actor/receptor15/attachTo                       volume15
/gate/actor/receptor15/addFilter                      particleFilter
/gate/actor/receptor15/particleFilter/addParticle     neutron
/gate/actor/receptor15/energySpectrum/setEmin         1e-6 MeV
/gate/actor/receptor15/energySpectrum/setEmax         1e3 MeV
/gate/actor/receptor15/energySpectrum/setNumberOfBins 480
/gate/actor/receptor15/setLogBinWidth		      true
/gate/actor/receptor15/enableFluenceTrackSpectrum     true
/gate/actor/receptor15/enableEdepSpectrum             false
/gate/actor/receptor15/enableNbPartSpectrum           true


